### ISSUE TITLE
Art is not visible in offline mode (+other offline and download bugs)

### ISSUE THREAD

**Issue by dab2020** [jmshrv/finamp#102]
Hi,
Finamp is amazing and I have been using it as my main music player to stream media from my Jellyfin server. However in offline mode, Album art + cover art is missing. This makes the interface look dull. Plus when we download even just one song from an album, the album should show up. Instead it shows them under songs.

When downloading a large amount of music ~20-50 songs, most of the downloads end up corrupted or unable to play. Only a handful will play.
Other wise Finamp looks amazing and works exactly as I like it. I can't wait for Android Auto support in ~0.6.0

**Comment by UnicornsOnLSD** [comment]
Thanks for submitting the issue :)

* I'm thinking of ways to add offline album art so it should be added in the next release
* Downloading individual songs isn't supported yet so I don't know how you've managed that, but when I add it in properly I will also show the album for it
* Are the downloads marked as failed in the downloads screen? Do you have any logs?

**Comment by dab2020** [comment]
1. I created a playlist and downloaded that.
2. They don't show up as failed but as completed, however they refuse to play. It has happened thrice on multiple devices I can clear data and try to recreate that. Once I do it I will post the logs here.

**Comment by ShiniGandhi** [comment]
> Thanks for submitting the issue :)
> 
> * Downloading individual songs isn't supported yet so I don't know how you've managed that, but when I add it in properly I will also show the album for it
> * Are the downloads marked as failed in the downloads screen? Do you have any logs?

Also downloading favorites automatically would be nice

**Comment by arvidortwig** [comment]
Artwork for downloads would be splendid !

**Comment by czadikem** [comment]
I would love to see this as this is one of the reasons I don't use this daily instead I use vlc.

**Comment by jmshrv** [comment]
This was added in 0.6.0, forgot to close :)
