### ISSUE TITLE
Problems with songs always repeating

### ISSUE THREAD

**Issue by notarobot63** [jmshrv/finamp#121]
Hello 
I have a playback problem with Finamp, the songs keeps repeating even though the song is not finished or there is another one in the queue. Repeating is of course disabled. 
Finamp Version: 0.5.1
Jellyfin version: 10.7.6
I can't seem to attach logs as they are too big for Github and Pastebin

Edit: wrong Jellyfin version number, my bad

**Comment by UnicornsOnLSD** [comment]
What platform are you on, and are you transcoding, streaming, or playing downloaded songs? Also, I haven't tested Finamp against Jellyfin 10.6, so updating your server could potentially help too

**Comment by notarobot63** [comment]
Server is on last update behind a nginx reverse proxy under Debian 10 and client is under Android 11
Yes I'm transcoding and playing through 4G mobile network

**Comment by UnicornsOnLSD** [comment]
Transcoding is a bit jank right now, but it should be improved in the next release. Here's a build from the master branch that changes how transcoding audio is done: [release.zip](https://github.com/UnicornsOnLSD/finamp/files/7098749/release.zip)

The master branch may be a bit jank, but I can't think of any issues of the top of my head.

**Comment by notarobot63** [comment]
I'll try this out thanks

**Comment by notarobot63** [comment]
OK so with the version you provided, instead of repeating the songs just stop playing but the playing cursor still moves. 
The problem is not present if I don't use transcoding

**Comment by UnicornsOnLSD** [comment]
That's weird, does it happen in other clients? It may be an issue with your server, but I doubt it. Check your transcoding logs just in case.

**Comment by Chaphasilor** [comment]
@notarobot63 is this still a problem? If yes, does it only happen with specific songs/codecs?

**Comment by Chaphasilor** [comment]
I see. I'll then close this, if someone else has this problem we can always open a new issue for it :)
