### ISSUE TITLE
[Feature Request] Jump to Letter when scrolling

### ISSUE THREAD

**Issue by Necronar** [jmshrv/finamp#125]
From a UX standpoint, there should be some way to jump straight to the letter of the artist or album when scrolling. If I want to play an artists whose name starts with a W, I have to scroll to the bottom of 600+ Artists every single time. I feel like a jump-to nav on the right side should solve that problem, kind of like how there is in the Contacts app on the iPhone. 

![TinyContactView-Before-and-After](https://user-images.githubusercontent.com/28360107/132258781-6b5bcf88-6830-4cd2-a222-7850783c8157.jpg)

**Comment by lhoggatt17** [comment]
This would be a killer feature for those of us with lots of artists. Awesome app by the way!

**Comment by mminklet** [comment]
This is a big issue for me, +1

**Comment by Guillergood** [comment]
Hello @jmshrv , do you want me to help with this? I may have some ideas to do this.

**Comment by jmshrv** [comment]
Feel free, although it may be way more awkward than expected because items are paginated, so we don't know the whole list upfront
