### ISSUE TITLE
Delete downloads in offline mode

### ISSUE THREAD

**Issue by alculete** [jmshrv/finamp#136]
I have some files that I would like to remove from local storage but I'm unable to delete it and also if I download an album I'm unable to redownload the files that failed to download

**Comment by UnicornsOnLSD** [comment]
Do you get any error messages in the logs?

**Comment by alculete** [comment]
for the failed download, yes. For downloaded files I get the location grayed out

**Comment by foss-** [comment]
> Other thing that I noticed, I have to be online to delete this files (offline mode disabled). For large downloaded files it will be hard to find

Sorry for the +1 comment. But I was scratching my head for ~30 minutes. Clearly deleting downloaded files should also be possible in offline mode. Having to switch back to online mode, then search for artist > album is unnecessarily complicated.

**Comment by dpraul** [comment]
I also just ran into this - I thought deleting was broken after the most recent updater. Very unintuitive to only be able to delete from online mode.

**Comment by jmshrv** [comment]
This will be implemented soon in #331

**Comment by Y0ngg4n** [comment]
@jmshrv can this be closed?
