### ISSUE TITLE
WebRadio Support

### ISSUE THREAD

**Issue by czadikem** [jmshrv/finamp#140]
Can you add support for this https://jellyfin.org/docs/general/server/media/internet-radio.html ?  I would really appreciate this since I am now trying to use Jellyfin for my music to.

**Comment by Chaphasilor** [comment]
I think this would require significant changes to work. Live streaming itself should work, but we'd probably want to update the track information during the stream too. The queue is also pretty useless for live streams. Internet radio in Jellyfin is part of the "Live TV" category, and therefore has different metadata.  
I'm really not sure this is feasible for now...
