### ISSUE TITLE
Automate from another app

### ISSUE THREAD

**Issue by nickmoss-2** [jmshrv/finamp#145]
Hi,

Is it currently possible to automate Finamp from another app, in particular to instruct it to play music? My use case is to start music when my phone connects to my car's Bluetooth so I don't need to fiddle with it between starting the car and leaving. If it's pertinent, my only real attempt at this is with the 'Automation' app from F-Droid (https://f-droid.org/en/packages/com.jens.automation2/), though as a first pass I'm not necessarily tied to that. Automation offers the ability to start a specific Activity and pass in Intent parameters, however I'm not familiar enough with Android development to find these in a quick look at the Finamp code.

If it's not currently possible, please consider this a feature request, again not bound to any specific implementation detail. A generic ability to start playback on connection of selected external audio providers seems a useful feature in general and may be better for most people's use cases (if less globally flexible) than specifically designing for external automation.

**Comment by UnicornsOnLSD** [comment]
I don't know if that would be possible, sadly. Finamp uses Flutter, so it doesn't have activities or intents.
