### ISSUE TITLE
[Feature Request] Option to download favourites automatically

### ISSUE THREAD

**Issue by pietropatelli** [jmshrv/finamp#146]
First of all thanks for the app! 

It would be great if there was an option to automatically download all favourite songs/albums/artists. Ideally separate options for each would be useful. In general, being able to select something as favourite (e.g. from the web player) and then have it automatically sync to my phone would be amazing.

**Comment by UnicornsOnLSD** [comment]
That’s a good idea. I may add a download button to the appbar for each category and add some special case for category favourites.

**Comment by Chaphasilor** [comment]
A dynamic playlist could work, where the whole playlist is always downloaded offline and it dynamically contains all liked songs

**Comment by Guillergood** [comment]
I may research on this! Please @Chaphasilor or @jmshrv assign this to me and put the hacktoberfest label please 😄

**Comment by jmshrv** [comment]
Go ahead @Guillergood :)

**Comment by Chaphasilor** [comment]
@pietropatelli the download system has been improved as part of the redesign beta. There's now an option in the download settings to download all favorites, and this will also include albums, playlists and artists. Favorites will also be synced when starting the app in online mode.  
You can check the beta out here: https://github.com/jmshrv/finamp/releases/tag/0.9.2-beta

I'll close this issue for now since it should be resolved.

**Comment by morgan55555** [comment]
@Chaphasilor, checked new beta, found only option to download favourites as a button, can it be an option please?
Should work like this: if checked, then adding to favourites will start download automatically, without another buttons and options. Also it will be great to has opposite option for removing songs, which no more in favourites.

**Comment by Chaphasilor** [comment]
@morgan55555 that is actually how it works already. If you have the "Favorites" thing downloaded in Finamp, then Finamp will keep track of your favorites and download/delete things whenever your favorites change. If you toggle the favorite status within Finamp, the downloads should be updated right away. If you use another app, it should happen the next time you open Finamp, at the latest.

I do think you have a valid point though, a section that says "Download all Favorites" doesn't imply that this will keep the favorites up-to-date. I'll think about how this could be improved!

**Comment by morgan55555** [comment]
@Chaphasilor, think that it will be enough to change button style to a on/off switch.

**Comment by lukaslindnermusic** [comment]
Or a toggle + a better string, i.e.:

"Automatically download Favorites"

"Download Favorites automatically"

"Auto-Download Favorites"

...
