### ISSUE TITLE
Grid view shows incorrect albums if user switches libraries while in offline mode

### ISSUE THREAD

**Issue by rom4nik** [jmshrv/finamp#157]
https://user-images.githubusercontent.com/46846000/146149016-a835749e-141a-4a62-8caf-39726c58db7a.mp4

*Ultraviolet* belongs to *Muzyka* library, the other two albums belong to *Soundtracki*.

**Comment by Chaphasilor** [comment]
Is this still happening?

**Comment by rom4nik** [comment]
Not anymore, thanks for reminding me of this old issue :sweat_smile:

**Comment by Chaphasilor** [comment]
Glad to hear that! Let me know if you have any other issues :D
