### ISSUE TITLE
Minimum iOS version

### ISSUE THREAD

**Issue by Harteex** [jmshrv/finamp#159]
Is there any feature in iOS 11 you use, or would it be possible to lower the minimum requirement to for example iOS 10 / iPadOS 10?
(I have an older iPad and it would be nice to be able to use finamp on it)

**Comment by UnicornsOnLSD** [comment]
Selecting custom directories requires iOS 11, but I may remove custom directories on iOS since they're broken anyway. If I do that, I should be able to go down to iOS 10.

**Comment by Harteex** [comment]
That sounds good!
It's always possible to raise it to iOS 11 again in the future if there is enough demand for custom directories.

**Comment by jmshrv** [comment]
Flutter 3.3 removes support for iOS 9 and 10

https://medium.com/flutter/whats-new-in-flutter-3-3-893c7b9af1ff
