### ISSUE TITLE
Allow deleting local files from "Downloads" view

### ISSUE THREAD

**Issue by mwip** [jmshrv/finamp#160]
First of all thanks for your awesome work on this. :+1: love the app.

I think it would be a nice feature to be able to delete local files from the Downloads view. 

**current behavior**  
When I want to delete an album that I downloaded, say to free up space, I need to go to the Downloads view and check which albums are local, then go to the Album view and delete the local copy. I know it is also possible to do this a bit easier through "offline mode", but overall I think it is a bit unintuitive. 

**desired behavior**  
It would be nice if the Downloads view would add some possibility to delete downloaded files. Maybe through a " long-press-context-menu" (for lack of a better word, sorry for the probably incorrect term)? This menu could also be used for additional context functionality such as sharing a media file etc...

**Comment by UnicornsOnLSD** [comment]
I've been meaning to do this for a while, and there's probably some old issue that I can't find. I think at one point I was going to do it before initial release lol

**Comment by HumerousTwist** [comment]
Adding a vote to this as well.  Potentially a swipe to delete with confirmation popup?
