### ISSUE TITLE
Display Artist in Library similar to now current playlist

### ISSUE THREAD

**Issue by btzs** [jmshrv/finamp#161]
Hi!
Would it be possible to add an option to display the artist in the library view for each song? Especially for albums and playlist this would be very helpful for me.
![image](https://user-images.githubusercontent.com/55090626/146899295-a0b5ebe0-3e79-491e-91cf-fe1f7a09d740.png)

Thanks a lot!

**Comment by Chaphasilor** [comment]
Is that an album view on the right? For playlists this is already shown, and for artists it will be shown once #220 is done, and possibly even earlier as this is a very simple fix :)

**Comment by btzs** [comment]
Hi Chaphasilor! Thanks for looking at this! Yes, my screenshot is an album view. Especially for albums with various artists I would love an option to see each track's artist!

**Comment by Chaphasilor** [comment]
It's already designed, but could take some time to be implemented :)

**Comment by Chaphasilor** [comment]
@btzs this has already been implemented in a way where the song artist are shown if they don't exactly match the album artists. Does that work for you?  
I think it should also be in the latest released version 🤔
