### ISSUE TITLE
UX: Confirmation for deleting downladed music

### ISSUE THREAD

**Issue by gw2princeps** [jmshrv/finamp#165]
While updating my downloaded music I went through albums rather rapidly and I accidently deleted albums due to the button being in the same location with no confirmation. I think the better UX design would be to have a confirmation dialog for deleting media.

**Comment by Y0ngg4n** [comment]
Would be also nice if we could delete downloads from downloads tab in the menu.

**Comment by gw2princeps** [comment]
> @gw2princeps What if instead of a dialog, there is a timeout and "Undo" button so you have a few seconds to prevent the file from actually being downloaded?  
> I'd imagine having a dialog open every time you want to delete a downloaded song would be a hassle for longer lists...

Sounds great!
