### ISSUE TITLE
[Bug] Inconsistent List Gaps

### ISSUE THREAD

**Issue by seniorm0ment** [jmshrv/finamp#183]
The gaps between albums, artists, tracks, etc. tabs are all different from each other. For example graps between items in the list om albums is bigger where artists tab has zero gaps and art is touching.

**Comment by UnicornsOnLSD** [comment]
Yeah, I've been aware of that lol, I was thinking of adding something like "X albums" under the artist name, but I couldn't get Jellyfin to actually return the value

**Comment by Chaphasilor** [comment]
> The gaps between albums, artists, tracks, etc. tabs are all different from each other. For example graps between items in the list om albums is bigger where artists tab has zero gaps and art is touching.

Just to clarify, there are only two different layouts: Albums, Playlists and Songs have the exact same layout and spacing, and so do Artists and Genres.

@jmshrv there's an `AlbumCount` property, but only when fetching the individual artist. However, it seems like you can get the album count for the `/Artists` endpoint by requesting the `ChildCount` field (`Artists?Fields=ChildCount%2CPrimaryImageAspectRatio%2CSortName%2CBasicSyncInfo&Recursive=true&StartIndex=0&ImageTypeLimit=1&Limit=100`). A property `ChildCount` will be added to the JSON response if it is greater than `0`.  
Maybe you can use that for the artists?

For the genres I couldn't get the API to return the ChildCount, but maybe you could perform individual queries for those (to fetch the amount of albums for each genre), given that there shouldn't be too many different genres...

**Comment by jmshrv** [comment]
I'll definitely try that, thanks for letting me know :)

As for genres, we could probably just manually add padding or something, it'd be a lot of individual web requests for something that doesn't really matter too much

**Comment by Chaphasilor** [comment]
> As for genres, we could probably just manually add padding or something

Right, just adding a white space " " for the second text field should be the easiest fix :)

**Comment by jmshrv** [comment]
That would move the title text up, I'll see what padding Flutter uses when a subtitle is provided and use that when there's no subtitle
