### ISSUE TITLE
What about automatically caching songs?

### ISSUE THREAD

**Issue by basings** [jmshrv/finamp#185]
E.g. the 1000 most played songs and/or favourites.

**Comment by meonkeys** [comment]
How about just caching each song as it is played, and always playing songs from cache? If a cached copy doesn't exist, it can't be played offline. Sorry in advance if this is a silly suggestion, I haven't read the source to know for sure.

**Comment by UnicornsOnLSD** [comment]
Caching songs as they play would be #90

**Comment by meonkeys** [comment]
Ah! Yep, that's exactly what I was thinking of.

**Comment by jmshrv** [comment]
Duplicate of #90
