### ISSUE TITLE
Autoplay next album feature

### ISSUE THREAD

**Issue by Brandonbart** [jmshrv/finamp#186]
Hello,  i love finamp so far. I am not at all knowledgeable about how the work is done and not sure how difficult it would be but:
I listen to music all day long. Im not a playlist guy, i am an album guy. Is it possible to add a feature to play the artists next album automatically? 
Thanks (:

**Comment by UnicornsOnLSD** [comment]
I could likely get this done at the same time as artist shuffling (#35) and the artist screen redesign.

**Comment by Brandonbart** [comment]
For me i often start a first album from an artist and just keep going on thru, but i can also see anyone who listens at work with dirty hands or physical labor who would prefer to keep the music flowing all day long. I previously used plexamp and loved that i could set it and forget it for 6-8 hours. Less of an issue with people who listen to playlists. I listen to full albums without skips so this would be really handy

**Comment by Chaphasilor** [comment]
This will be part of the redesign beta. You can now "Play Artist" (will play all songs, grouped by album release date) and "Shuffle Albums" (plays albums in random order, album tracks are played in order). We could add more playback options if needed.

**Comment by Chaphasilor** [comment]
@Brandonbart this has now been released as part of the redesign beta. You can check it out here: https://github.com/jmshrv/finamp/releases/tag/0.9.2-beta

Let me know if that works for you, or if you were looking for something else!
