### ISSUE TITLE
Album playback not possible when not all songs of album completely downloaded

### ISSUE THREAD

**Issue by arvidortwig** [jmshrv/finamp#188]
Plattform: Android 11 and Finamp 0.5.1

Current behaviour:
I have experienced that it is not possible to play a single song of a downloaded album (in offline mode) if not all of the songs are properly downloaded e.g. one is missing. 

Expected behaviour:
It should be possible to play all already downloaded songs even if one is missing.

**Comment by UnicornsOnLSD** [comment]
Are you seeing an error like this?

https://github.com/UnicornsOnLSD/finamp/blob/3668e7d14fd93ac251371aa3c1d8f040b0cca9bb/lib/services/AudioServiceHelper.dart#L200

I think the current behaviour is just to fail entirely if a song is missing, but I could change it to just skip non-downloaded songs.

**Comment by joestrong** [comment]
It should definitely skip. If you press any single song on album view in offline mode, when one of the others isn't downloaded nothing happens at all.
