### ISSUE TITLE
[Feature Request] Colourise Player Elements

### ISSUE THREAD

**Issue by nathancoooper** [jmshrv/finamp#208]
It'd be cool to see the pause, shuffle, repeat buttons, and progression bar change colour depending on the colour of the album art of the current playing song- like is done in Plexamp.

**Comment by UnicornsOnLSD** [comment]
That would be interesting, I think Flutter added a thing to generate a Material pallete from a colour like in Android 12, so assuming theres a thing to get the dominant colour of an image, it shouldn't be too hard

**Comment by rom4nik** [comment]
That might also help with progress bar contrast issues when blurred cover in player background is enabled.

**Comment by Chaphasilor** [comment]
Although this was already partially implemented in the redesign branch, #484 will improve upon this further

**Comment by jmshrv** [comment]
Closing since this is basically fully implemented in the redesign
