### ISSUE TITLE
Please add ability to retry downloading missing/new files from playlist or album

### ISSUE THREAD

**Issue by JPinSPACE** [jmshrv/finamp#214]
If a user downloads a playlist or album for offline listening and a song fails to download there is no way to fix the situation without deleting what has downloaded and starting again from scratch.

I encounter this frequently when downloading large playlists. If I don't keep focus on Finamp, files will fail to download. Then, even if only one file failed and 300 worked, I have to delete all 300 and start the giant download over again.

The ability to say "please try downloading missing files again" without having to start from scratch would be greatly appreciated.

This feature could also solve the problem of updating an existing large playlist. Right now, if I use my main Jellyfin client to add music to a large playlist, the only way to update it for offline listening in Finamp is to delete the playlist and re-download the entire thing.

**Comment by ryanwwest** [comment]
I agree this would be great. Also, the 'Downloads' page shows all downloads, including the failed ones - ideally, it would be nice to automatically retry the failed ones, but it would be nice if you could at least manually trigger a retry from here as long as the number of failures is > 0.

And to add, it would be nice to be able to also delete downloads by song or album from that page, as well as start playing or add to queue by clicking songs on that page.

**Comment by axelsimon** [comment]
Related te #213.

**Comment by k1llerk3ks** [comment]
@axelsimon i'll close this issue in that case, thx.

**Comment by jmshrv** [comment]
Will be fixed in #330
