### ISSUE TITLE
Songs - Sort by Name broken

### ISSUE THREAD

**Issue by perniczech** [jmshrv/finamp#223]
this is what sorting songs by name looks like in the app:

![Screenshot_20220426-225746](https://user-images.githubusercontent.com/76674812/165391409-e4be552e-b42a-4d37-9c92-202e32c1bd92.png)

vs what it's actually supposed to be:

![image](https://user-images.githubusercontent.com/76674812/165391766-af01a859-d149-445a-9b8c-6ebf89d31cc9.png)

Flipping the sorting (Descending) doesn't work properly either.

Btw. I think the arrow button should be inverted i.e. Ascending (A-Z) should be arrow pointing up and vice versa, currently it's the other way around.

**Comment by Chaphasilor** [comment]
is this still an issue?

**Comment by jmshrv** [comment]
Is this in online or offline mode? They both use different methods for sorting, which can sometimes cause inconsistent results.

**Comment by perniczech** [comment]
Sorting now seems to correspond with what Jellyfin (web) does, so I'd say it's fixed. That being said, and this is apparently a JF issue, it sorts taking the English articles (A, An, The) into account which is "funny" because JF doesn't do that in the video libraries.

**Comment by jmshrv** [comment]
#276 changed sorting a bit, maybe that fixed it
