### ISSUE TITLE
Some songs won't transcode at 320kbps

### ISSUE THREAD

**Issue by Chryma** [jmshrv/finamp#226]
Not sure what is happening but the logs say "Player error code 0: Source error" logs can be found here: https://pastebin.com/bj20hqDL

If I change the transcoding to anything below 320 it will work but I want it transcoded at 320 if possible. There's no bandwidth limit on the user account in jellyfin and this doesn't happen to every song just some of them. Let me know if there's anything else I can do to help diagnose.

**Comment by UnicornsOnLSD** [comment]
What platform are you on, and can you transcode these songs at 320kbps on other clients? Also, what format are the songs (MP3, FLAC etc)?

**Comment by Chryma** [comment]
I'm on Android and I can transcode using Gelli. One of the songs is an .ogg and another is .mp3.

I also have some issues with playback randomly stopping and starting again after a couple seconds. Mostly happens when I first start playing tracks and it will play for like 2-3 seconds, stop for 3-5 seconds and then resume. Was also happening with downloaded songs.

I should also mention I recently updated my Jellyfin to the latest stable release and had recently turned synology snapshots on which clogged up my library. I tried to fix my library.db file but I ended up just removing it and rebuilding the library.db file. I've since removed all data from Finamp and reinstalled it and it mostly works apart from these two issues. Unsure if that is unrelated or not to my issue.

**Comment by OfficiallyMellow** [comment]
I might be experiencing the same issue. For me, the problem seems to be songs that have a bitrate lower than 320. Songs with a bitrate of 320 or higher transcode perfectly fine, but if I try to play a song with a lower bitrate it just won't play. If I then lower the transcoding bitrate to the songs bitrate, it works again.

**Comment by Chryma** [comment]
> I might be experiencing the same issue. For me, the problem seems to be songs that have a bitrate lower than 320. Songs with a bitrate of 320 or higher transcode perfectly fine, but if I try to play a song that has a lower bitrate, it just won't play. If I then lower the transcoding bitrate to the songs bitrate, it works again.

It looks like this is also what's happening to me.

**Comment by Chaphasilor** [comment]
I think this issue has been fixed a while ago
