### ISSUE TITLE
http basic auth username and password in URL not always preserved

### ISSUE THREAD

**Issue by mdemoss** [jmshrv/finamp#233]
https://github.com/UnicornsOnLSD/finamp/blob/014184daff8d5cc8c8c2e08a93db0d883ec2a94d/lib/services/JellyfinApiData.dart#L410

When using a URL with a userinfo subcomponent (like `https://username:password@example.com/jellyfin`) for a server behind an authenticating reverse proxy, some requests will carry the username and password and pass the proxy, and others will not.

**Comment by jmshrv** [comment]
Is this still an issue? I've messed about with how URLs are handled since then

**Comment by mdemoss** [comment]
I think it could still be dropped at https://github.com/jmshrv/finamp/blob/194c1db14ef7a3a793b41299809ed1f0d5c785cd/lib/services/jellyfin_api_helper.dart#L467 but using the app and watching my logs I don't see any problems anymore.

**Comment by jmshrv** [comment]
Added a fix to explicitly specify userInfo in 797535d, although if it already works for you it may be unnecessary
