### ISSUE TITLE
[Feature Request] Mix Builder. Pick a set of artists and launch a mix

### ISSUE THREAD

**Issue by faizzzzz** [jmshrv/finamp#234]
The ability to create a mix that plays songs randomly from selected artists. Plexamp has this feature and I would love to have it in finamp as well. The mix builder screen suggests a bunch of artists for the user to select. It also offers a search bar to search for artists that are not suggested. After adding the artists, I can then click on "Play Mix", which randomly selects songs from those artists and makes a queue.

**Comment by faizzzzz** [comment]
I've figured out the jellyfin API endpoint to get the random songs only from selected artists.
We can use the 
`<base_url>/Users/<user_ud>/Items?ArtistIds=artist1,artist2&Filters=IsNotFolder&Recursive=true&SortBy=Random&MediaTypes=Audio&Limit=300&Fields=Chapters&ExcludeLocationTypes=Virtual&EnableTotalRecordCount=false&CollapseBoxSetItems=false` to get a queue of songs. Just need to figure out how to create a UI around it.

**Comment by faizzzzz** [comment]
I was thinking of having a `NowPlayingBar` like UI with a play button to the left and all the artist names in the middle. Similar to this
![image](https://user-images.githubusercontent.com/27871755/172640793-70ce2039-6036-4067-94f7-1cd475dce60f.png)

[image_src](https://www.ctnet.co.uk/how-to-use-the-plexamp-mix-builder/)

Long pressing the artist would show an option to "add to mix builder" and "remove from mix builder". If there are no artists in the mix builder, then the bar would not show up. Pressing on the play button would start the mix.

**Comment by faizzzzz** [comment]
Also realized that the mix can be started with Albums as well. The api looks like this:
```<base_url>/Users/<user_id>/Items?AlbumIds=albumId1,albumId2&Filters=IsNotFolder&Recursive=true&SortBy=Random&MediaTypes=Audio&Limit=300&Fields=Chapters&ExcludeLocationTypes=Virtual&EnableTotalRecordCount=false&CollapseBoxSetItems=false```

**Comment by Chaphasilor** [comment]
This is already implemented, right? There's a mix builder both for albums and artists and it seems to do what you'd expect it to do.

UI improvements for this will be handled in #220, but if you have any specific issues/ideas/requirements, you can leave them here in this issue :D

**Comment by jmshrv** [comment]
Closing as this was implemented a while ago
