### ISSUE TITLE
[Feature request] Increased streaming cache

### ISSUE THREAD

**Issue by B16WLL** [jmshrv/finamp#239]
I use Finamp for music when driving, but don't always have signal for data. I used to use DSub, which had a control to choose how far ahead tracks were cached. I had mine set to 10 tracks, meaning I could be out of coverage for 35-40 minutes without any issue. Is there a way of doing this for Finamp?

Oh , and Android Auto support would be awesome 😉
The official Jellyfin app has that but it sucks.

**Comment by Chaphasilor** [comment]
I agree that the streaming cache should be increased. It seems like currently it's caching about 30 seconds to one minute, and I frequently encounter interruptions in playback :)

Maybe it would be possible to fully cache the currently playing track as a start, that shouldn't require a huge code change...

**Comment by UnicornsOnLSD** [comment]
I'll have a look to see if the caching method can be changed. It may be platform-dependent, as on iOS the whole song is buffered as long as it isn't massive

**Comment by seniorm0ment** [comment]
I notice caching issues on Android, it's a massive pain when driving on mobile data because of spotty reception. Realistically it'd be nice for it to be able to cache the whole song, plus preload the next one or two. Or at least the option to. I presume we can just set a size limit, I've seen that on other apps.

**Comment by jmshrv** [comment]
This looks quite easy to do - https://pub.dev/documentation/just_audio/latest/just_audio/AudioLoadConfiguration-class.html

Looks like the buffer size can't be changed on iOS, but as I said it caches quite a lot anyway

**Comment by BloodyIron** [comment]
@B16WLL the thread for Android Auto is : https://github.com/jmshrv/finamp/issues/24

@jmshrv what kind of a timeline are you anticipating for this to be mainlined/released?

**Comment by jmshrv** [comment]
I don't really have a timeline for anything, I try not to give time estimates/deadlines since I never actually keep up with them. Finamp is a project that I work on in my time, so the amount of work I put into it can vary significantly.

For this issue specifically, it should be pretty easy to add so I might look at it today or some other time.

**Comment by jmshrv** [comment]
> Looks like the buffer size can't be changed on iOS

Nevermind, https://pub.dev/documentation/just_audio/latest/just_audio/DarwinLoadControl/preferredForwardBufferDuration.html

**Comment by jmshrv** [comment]
Added in 2938e51 (sometimes I'm inconsistently quick 🙃)

**Comment by BloodyIron** [comment]
@jmshrv reading through that commit it looks like the buffer setting is only in seconds, and not number of tracks. Maybe I missed it in your code somewhere, but the original ask (which I myself am also interested in) is asking for the ability to auto-cache # of tracks (and/or a setting to just cache the whole queue/album/wtvr).

While I applaud your speedy solution (how dare you! /s ), I would like to hear your response on this aspect please, as this detail is particularly important/useful to me, OP, and likely others.

**Comment by jmshrv** [comment]
From my (very limited) testing, it looks like it'll cache beyond the current song if you set a really long buffer size. I'd assume at some point it'll get limited by memory, but this should suffice for now.
