### ISSUE TITLE
Song keeps playing but no audio

### ISSUE THREAD

**Issue by drazil100** [jmshrv/finamp#249]
If I leave finamp playing long enough it frequently just stops playing. The seek bar keeps moving and if you leave it alone long enough it will resume playing halfway into the next song. While it's silent you can't fix it by changing tracks with either next or previous buttons or by manually selecting a new track however you can fix it by stopping playback (not pause) and THEN selecting a new track. 

It should be noted all of these songs I'm playing are downloaded and not playing off the server and playing the tracks again does not repeat the issue so the files are fine.

finamp 0.6.2
iOS 15.5
iPhone SE 2020

**Comment by UnicornsOnLSD** [comment]
Could you send logs? It would help to see whether or not this is a player issue or not. If GitHub doesn't like you dumping a massive string of logs, try using a pastebin service

**Comment by drazil100** [comment]
[logs.txt](https://github.com/UnicornsOnLSD/finamp/files/8868774/logs.txt)

**Comment by drazil100** [comment]
it happened on this song in the logs `2022-06-09 03:37:20.207419` and resumed partway through the next song

**Comment by Chaphasilor** [comment]
Is this still happening with recent versions / the beta?

**Comment by drazil100** [comment]
Sorry. This has been resolved years ago at this point. Been stable (even on the beta) for a long time. 

Never updated the issue cause it happened infrequently enough that when it stopped happening it I just didn't notice it.

**Comment by Chaphasilor** [comment]
Wonderful, thanks for letting us know!
