### ISSUE TITLE
Can't play albums and playlists with download errors

### ISSUE THREAD

**Issue by abstractionmage** [jmshrv/finamp#252]
Songs with download errors in them still show up alonglide regular songs in playlists and albums (see image below). In offline mode, upon trying to play (or shuffle play) downloaded albums or playlists containing both properly downloaded songs and songs with download errors, nothing happens. I would expect the app to still play the albums or playlists and skip any songs with download errors.

In combination with #251 this issue renders the app unusable for me unfortunately, since I can't play most of my playlists offline.

![Screenshot_20220612-113058](https://user-images.githubusercontent.com/37195767/173227037-ae319468-eefb-4585-ac1c-5118070a4287.jpg)

**Comment by jeremyswright** [comment]
I'm seeing this same behaviour.

**Comment by jmshrv** [comment]
Fixed in #346
