### ISSUE TITLE
Issue with now playing queue behaviour

### ISSUE THREAD

**Issue by Elbullazul** [jmshrv/finamp#255]
I noticed that since version 0.6.2, the playing queue behaves differently. [Here's a video of the issue](https://imgur.com/R6Oc5Ht)

The weird thing is that the changes will apply in the background (ex. I change the next song, then skip to the next queued song. The song I moved will start playing, even if the UI shows another song.)

**Comment by Chaphasilor** [comment]
I believe this is a duplicate of #212 :) So the dev is aware of this. But the queue is probably due for a rework anyway \^\^

**Comment by jmshrv** [comment]
Yeah, this is a duplicate of #212 which I really need to fix lol
