### ISSUE TITLE
"repeat one" function broken for some file types

### ISSUE THREAD

**Issue by jacobrham** [jmshrv/finamp#263]
Using Finamp 0.6.2 on a Samsung Note 10+ with Android 12 enabling repeat one causes some tracks to stop early and restart before the entire song has been played. In my library the only two tracks this bug seems to occur with were downloaded from SoundCloud using soundcloud-dl. Able to share track metadata or files if it would help.

Steps to reproduce:
Open finamp in online or offline mode:
Play a song (downloaded from soundcloud-dl?)
Turn on repeat one by pressing the repeat icon
Listen until music stops or the music restarts early (may be accompanied by an erratic progress bar)

**Comment by JengaMasterG** [comment]
I can confirm this affects m4a (iTunes) formatted songs. I'm on Android 12L with the Microsoft Surface Duo with Finamp 0.6.9.

**Comment by Chaphasilor** [comment]
@jacobrham is this still happening for you?
