### ISSUE TITLE
Misc. Scrobbling Issues

### ISSUE THREAD

**Issue by TinDefacto** [jmshrv/finamp#270]
Hi! I tried searching around but don't think these two scrobbling issues have been mentioned:

1. On one of the latest updates, the player now defaults to displaying (though not playing) the first track when an album finishes. This seems to have led to a) the album's first song often not scrobbling when it plays, and b) the album's first song then scrobbling _after_ the album finishes. (I personally would prefer this to be fixed by _not_ displaying the first song again after the album finishes, but I don't really mind so long as the scrobbling gets fixed.)

2. The second issue, which has been an issue since I started using Finamp, is that some songs simply refuse to scrobble. It's always the same songs, and there almost always seems to be at least one per album. This does seem to be a Finamp-specfic issue, as when I play music from Jellyfin's browser UI, all songs scrobble fine. And strangely, last.fm does show when one of these songs is _playing_ on Finamp, but simply does not log it as played once completed. (The song also shows up just fine in Jellyfin's "Activity" panel.) I'm not sure what information you'll need for this, but here is a short selection of songs that never scrobble:

"Evilest Man" by King Gizzard & The Lizard Wizard on _Omnium Gatherum_, 7:39, "07 Evilest Man.m4a"
"6 Shooter" by Viagra Boys on _Welfare Jazz_, 4:51, "07 6 Shooter.m4a"
"gallons of spiders went flying thru the stratosphere" by Foxtails on _fawn_, 2:53, "06 Gallons Of Spiders Went Flying Th.m4a"
"Cheer Up, Chihiro!" by Ovlov on _Buds_, 4:30, "06 Cheer Up, Chihiro!.m4a"

Let me know what other info would be helpful here.

Thank you so much for this and all of your hard work on Finamp. :)

**Comment by Chaphasilor** [comment]
Are you still experiencing these issues?

**Comment by TinDefacto** [comment]
Hi! I actually literally realized last night when curating my last.fm stats that issue #2 listed above doesn't seem to happen anymore. I just played one of these tracks via Finamp to confirm this, and whatever happened, it seems fixed! :D

Alas, the first issue -- the one in which, at the conclusion of an album, the first song from that album will scrobble again instead of the first song from the next album -- is still a big problem. Again, this only started happening when Finamp was updated to display the first song from an album when the album finishes playing through. After that happens, when I start a new album, Finamp seems to think I'm relistening to the previous album's first song.

To illustrate what I mean, let's say I'm listening to a trio of 4-song EP's. This is how they will end up scrobbling:

- EP1, Track 1
- EP1, Track 2
- EP1, Track 3
- EP1, Track 4
- **_EP1, Track 1_** (when I was really listening to EP2, Track 1)
- EP2, Track 2
- EP2, Track 3
- EP2, Track 4
- **_EP2, Track 1_** (when I was really listening to EP3, Track 1)
- EP3, Track 2
- EP3, Track 3
- EP3, Track 4

This is leading to a lot of extra time spent to curate my last.fm, so I would really appreciate it if this were able to be fixed. :D Thankee. :)

**Comment by Chaphasilor** [comment]
@TinDefacto awesome to hear that the first issue is fixed now!  
> > Regarding the second issue, this will be fixed with #484 and should be available as a beta release in the coming weeks. Hang in there!

**Comment by Chaphasilor** [comment]
@TinDefacto this should now be fixed as part of the redesign beta. I think there are still some visual bugs when playback stops, but Finamp shouldn't report the first track to the server anymore. You can check it out here: https://github.com/jmshrv/finamp/releases/tag/0.9.2-beta

I'll close this issue for now since it should be resolved.

**Comment by TinDefacto** [comment]
Oh, the issue had already become randomly resolved a couple of months ago :D But thank you!! I'm excited to check out the new design once it's stable!
