### ISSUE TITLE
Green Outline On Display

### ISSUE THREAD

**Issue by seniorm0ment** [jmshrv/finamp#290]
After latest update, there is a noticeable green outline along the edge of the display in the app.
Pixel 6 Pro

**Comment by rom4nik** [comment]
Could you add a screenshot of this green outline? I don't see it on my device.

**Comment by UnicornsOnLSD** [comment]
I've only ever seen the outline while debugging on Android, pretty sure it's a Flutter thing because it's happened with other apps. My only guess is that some keyboard input causes it.

**Comment by seniorm0ment** [comment]
I do not see it anymore, not sure what happened.

**Comment by Y0ngg4n** [comment]
@seniorm0ment if you don´t see it anymore please close the issue.
