### ISSUE TITLE
[Feature]Localization?

### ISSUE THREAD

**Issue by charleypeng** [jmshrv/finamp#295]
I can help with this

**Comment by ChrisB85** [comment]
I am willing to prepare a Polish translation of the application.

**Comment by UnicornsOnLSD** [comment]
I'll set up a Weblate project this week :)

**Comment by charleypeng** [comment]
cool

**Comment by jmshrv** [comment]
Weblate has been set up at https://hosted.weblate.org/projects/finamp/ :)

Feel free to ask if you need more context for strings

**Comment by rom4nik** [comment]
I'm not familiar with Weblate so I'm not sure if that's on you as the translation "admin", but could you look into enabling triple translations for phrases where a number might be plural? Example: https://weblate.nheko.im/translate/nheko/nheko-master/pl/?q=cz%C5%82onkowie&sort_by=-priority%2Cposition&offset=2, when the number ends on 2, 3 or 4 the word following it in Polish sometimes has different form than if the number ends on 5-0.

**Comment by jmshrv** [comment]
Using plurals is documented here: https://docs.google.com/document/d/10e0saTfAv32OZLRmONy866vnaw0I2jwL8zukykpgWBc/edit#heading=h.yfh1gyd78g7g

In theory, you should be able to type a string like in the document. There are a few strings in Finamp that use this plural handling in English, such as `downloadedMissingImages`.

**Comment by MrPotatoBobx** [comment]
![image](https://user-images.githubusercontent.com/63403023/186370804-4cd0c9e8-0b1f-48e7-a010-955e616a040b.png)

do I ignore those things in the curly brackets and just write the translation?

**Comment by jmshrv** [comment]
The curly braces are placeholders where information is inserted. You'll need to insert them into the new translation wherever they fit the sentence.

**Comment by MrPotatoBobx** [comment]
Got it, thanks.

**Comment by MrPotatoBobx** [comment]
![image](https://user-images.githubusercontent.com/63403023/186764796-6d78a15f-0395-4add-924e-3d7188300623.png)
is this "to list" (verb) or "a list" (noun)?

**Comment by jmshrv** [comment]
It's used as a noun to reference a list layout (same goes for "grid")

**Comment by MrPotatoBobx** [comment]
ِArabic has fully been translated. If you are an Arabic speaker, I urge you to double check and look for errors in grammar, or places where better words could be used.

**Comment by alaincao** [comment]
Heylow,
for french, I think we'd need some context for these:
1) premiereDate - Premiere Date
    is it the "Release date" of a movie (eg. as shown on a movie's Wikipedia pages) ? (ie. "date de sortie")
2) revenue - Revenue
    is the "Box office" number (eg. shown on a movie's Wikipedia pages) ?
2) invalidNumber - Invalid Number
    is it "a number" like in "You picked an invalid lottery number, the winning one was 5" (ie. "numéro")  
    or is it "an amount" like in "The number of items is invalid ; cannot be that high" (ie. "nombre")

**Comment by jmshrv** [comment]
1. Premiere date is the release of a film
2. Revenue is like the amount of money a film gets from the box office
3. `invalidNumber` is used when the user gives an invalid number to the sleep timer dialog, such as if they somehow got text into that input.

(note that Revenue isn't exposed in Finamp, it's just there because its part of the Jellyfin API. Premiere date can be found in the sort options)

**Comment by comradekingu** [comment]
@jmshrv 
The main component should not be marked as a glossary.
Doing that makes translating it harder.

**Comment by jmshrv** [comment]
Fixed :)

**Comment by Chaphasilor** [comment]
We are moving discussion for localization/translations to GitHub's "Discussion" section, which is better suited for this. I'll go ahead and close this issue.  
If you subscribed to this issue to the past and want to continue to receive updates about translation issues, you could subscribe to updates about discussions:
![image](https://github.com/jmshrv/finamp/assets/18015147/fa330bdc-fdb5-4c59-8095-a5e1cd6f97a0)
Sadly, filtering specific topics isn't possible (although I don't think this is a problem for anyone)
