### ISSUE TITLE
[Feature] Dynamic color blur player

### ISSUE THREAD

**Issue by florinsdistortedvision** [jmshrv/finamp#296]
Similar to Apple Music, it would work very well to add a dynamically color change of the player based on artwork.

**Comment by UnicornsOnLSD** [comment]
Blurred backgrounds are in the latest release, which is pretty much a blurred colour gradient.

**Comment by UnicornsOnLSD** [comment]
Discussion on how we could make the blue look better is at #273

**Comment by florinsdistortedvision** [comment]
Don't seem to have that, is it not implemented already in iOS version?

**Comment by UnicornsOnLSD** [comment]
It was released recently in 0.6.5 so it may not have updated on your device yet. You can check the version by tapping on the info button on the top right of the settings screen

**Comment by florinsdistortedvision** [comment]
I have checked and it is 0.6.5 but no blur happens on my device, it always remains black ![image](https://user-images.githubusercontent.com/97384306/182950266-506cd713-4299-478e-b290-fda88cd946b5.png)

**Comment by UnicornsOnLSD** [comment]
So you have it enabled in the Layout & Theme settings?

![image](https://user-images.githubusercontent.com/44349936/182950594-b77b7bae-257e-49cb-8f14-d1087590553e.jpeg)

**Comment by florinsdistortedvision** [comment]
![image](https://user-images.githubusercontent.com/97384306/182950804-e8890d77-93aa-4757-b732-434070ddd3f4.png)

![image](https://user-images.githubusercontent.com/97384306/182950817-850d3c80-a05b-41ce-bb41-992944753d97.png)

**Comment by UnicornsOnLSD** [comment]
Oh I forgot that I didn't push blurred backgrounds in the current release in case anything in it was broken (I'm away for a bit so wouldn't be able to push a fix if it was broken). Sorry about that 🙃

**Comment by florinsdistortedvision** [comment]
No worries, I'll wait for the official update on App Store 😄
