### ISSUE TITLE
[Bug] Player interface is backwards when using a RTL language

### ISSUE THREAD

**Issue by MrPotatoBobx** [jmshrv/finamp#310]
![IMG_٢٠٢٢٠٨٢٥_١٠٣٤٤٩](https://user-images.githubusercontent.com/63403023/186604023-d8a515aa-ee9a-40d7-b86a-5870d7a9b28d.jpg)
 The progress bar is backwards, and the skip buttons are flipped, (this doesn't occur in the music notification so that's fine).
 
 The sleep icon also needs to be mirrored.

**Comment by jmshrv** [comment]
Fixed in 66ea02053a529e204df374dd4856f57e3b1b840a and bdce269c0451be2800cc5d5cba70e4bd9f97bae4
