### ISSUE TITLE
No Italian translation on 0.6.7

### ISSUE THREAD

**Issue by I-G-1-1** [jmshrv/finamp#316]
I just updated to Finamp 0.6.7.

I saw in the changelog that this version should include the Italian translation from weblate, however when installed the app is still in English.

My phone language in MiUI settings is set to Italian.

I also tried to delete all app data and began from scratch, but the app is still in English.

Thanks

**Comment by jmshrv** [comment]
Fixed in 9c57216, will quickly make release now 🙃
