### ISSUE TITLE
Radio (random music)

### ISSUE THREAD

**Issue by markster22** [jmshrv/finamp#320]
The app is great and I use it every day. I have about 70 albums in my collection totaling about 7k songs all together.
I miss this feature from Plexamp called Radio. It would simply random play music from my library. I did not have to configure any sort of play lists or mix. Just one button to start. We could go even further (if you want) and have Radio by gender.

Also, I am not sure why we need to show Jellyfin playlists since they are useless.

**Comment by jmshrv** [comment]
There's a shuffle all button on the songs tab which should do what you want. Shuffling genres could probably be done at the same time as #35 since I'm pretty sure they're implemented the same way

**Comment by jmshrv** [comment]
Also, playlists still serve a purpose for organising music. If you don't use them, you can disable them (and any other tab) from the Layout & Theme settings

**Comment by Y0ngg4n** [comment]
I organize all my music in playlists so i don´t think they are useless.

**Comment by markster22** [comment]
So you like when Jellyfin creates default play lists? These you cannot delete. Hmmm

**Comment by Y0ngg4n** [comment]
@markster22 Jellyfin never created default playlists for me.

**Comment by jmshrv** [comment]
Do you mean m3us? If any of your albums have an m3u file, Jellyfin will make a playlist for it. As far as I know, the only way to remove those playlists is to delete the m3u.
