### ISSUE TITLE
Update Queue Position

### ISSUE THREAD

**Issue by nathancoooper** [jmshrv/finamp#322]
When I start playing a song, a queue is created. After getting a little way through the queue, I have to scroll quite far to find the song I'm currently on. It would be great if the queue position would update so the current song remains at the top of the queue (and, perhaps, there is some gesture to view the queue that has already been listened to).

![image](https://user-images.githubusercontent.com/100081814/187989145-0983f511-1920-4143-b4df-ca14019482dc.png)

**Comment by Chaphasilor** [comment]
You should take a look at #142, there quite a few changes that should be coming to the queue eventually. For now, maybe a button could be added that simply scrolls to the current song :)
