### ISSUE TITLE
Offline Artists View

### ISSUE THREAD

**Issue by djohnson1865** [jmshrv/finamp#323]
Apologies if this is tracked somewhere else that I've missed. But wanted to get some information about the Artists tab in offline mode. I use offline mode somewhat regularly and not having the artists tab available is definitely a pain point.

Not sure if there is a technical/architecture road block that will require lower level reworking of the download feature or it just isn't hasn't been brought up enough to warrant development time. In either case I figure putting the issue out there might help in case other's are in a similar boat.

Thanks for all the excellent work, Finamp is and has continued to be a fantastic project.

**Comment by jmshrv** [comment]
This will be addressed in #213 as the current system doesn't have the capability to store and sync artists alongside albums.

**Comment by djohnson1865** [comment]
Awesome, thanks for the info. I had a feeling something like that was the case. Appreciate the quick response!
