### ISSUE TITLE
Album covers are cropped on very slim/tall screens

### ISSUE THREAD

**Issue by Maxr1998** [jmshrv/finamp#324]
On screens with a high aspect ratio that are tall but slim (like the cover screen on the Samsung Z Fold 4), covers are cropped on the sides.

Instead of cropping them, they should be fit inside the screen dimensions, with some additional padding, e.g. at the top to visually center the cover.

![Screenshot_20220907_142329.png](https://user-images.githubusercontent.com/5903699/188878065-534fcf8a-5cfa-4de3-bd66-6c08ddd63607.png)

**Comment by Chaphasilor** [comment]
This will eventually be fixed by #220, not sure if @jmshrv wants to add a temporary fix for this...

**Comment by jmshrv** [comment]
I'll look in to this :)

**Comment by Chaphasilor** [comment]
@Maxr1998 can you try it on the latest redesign branch? I made some changes to hopefully better support different screen sizes with the redesign :)

**Comment by Maxr1998** [comment]
Seems pretty good! During my quick test I noticed the album screen is a little odd now, but that's another issue.

<details>
<summary>Screenshots</summary>

![Screenshot_20240208_234442.png](https://github.com/jmshrv/finamp/assets/5903699/fcb92189-db69-41ac-bad6-0a84ff8a69f6)
![Screenshot_20240208_234436.png](https://github.com/jmshrv/finamp/assets/5903699/1ba95f10-cb0b-4cc7-be70-043bc84f32da)
</details>

**Comment by Chaphasilor** [comment]
Awesome, thanks. Yeah that screen will be redesigned anyway so I won't dive into cosmetic fixed for the time being ^^

**Comment by Maxr1998** [comment]
Understood. A popup menu or something might be preferable anyway so that it's not so crowded.

Anyways, sorry for taking so long to reply and thanks for fixing the album art issue. The redesign branch already looks really nice, great work!
