### ISSUE TITLE
No media is present in the app

### ISSUE THREAD

**Issue by souldessin** [jmshrv/finamp#326]
I have v0.6.8.

After opening Finamp and logging into my server, I am prompted to select a library. After selecting the music library named "Podcasts," I am presented with nothing but a single entry in the "Artist" tab. The app just goes grey after selecting the artist. I've tried clearing all of the settings and re-logging in, selecting a different folder as the library, reselecting the library. Nothing shows any content.

Thank you

**Comment by jmshrv** [comment]
Podcasts aren't supported just yet, this issue is being tracked in #230

**Comment by souldessin** [comment]
I don't need special podcast support, it just won't even list the mp3s. Is it ignoring them because of tag data?

**Comment by Chaphasilor** [comment]
What does the Jellyfin app show if you go into your "Podcast" library/folder?

**Comment by souldessin** [comment]
The web jellyfin interface shows all of the mp3s as a very large album. I even went through the trouble of putting in track numbers on everything so that they would show in order.

**Comment by jmshrv** [comment]
Do the podcasts show in an Album tab? Finamp works by asking the server for albums, artists, genres etc so it won't notice a dedicated podcast type. If you could send logs after navigating to the grey screen that would be great too :)

**Comment by souldessin** [comment]
Good afternoon,

  Well, I spent some time really looking into things. I was finally able to get the files to display, but there was a process. Unfortunately, there may be a few reasons. To get to the point right away, I don't believe that it was the fault of Finamp.

As for what I ended up doing to get the podcasts episodes to show in Finamp, I'll list them below.
1. I ensured that all tracks were tagged with track numbers. I used EasyTAG to do this.
   - The episodes would show in Jellyfin, but not with the usual music interface, but were playable.
2. All podcasts had an album, but the genre was non-standard as "Podcast." This was changed to "Gospel."
   - Still no change.
3. I recreated another music library in Jellyfin and placed just one episode that had all tags removed and rewritten, this time with MP3info, via the command line.

   - Still no change; furthermore, KDE's Dolphin file browser was reading all of the tags correctly.
4. I removed the single test file from the test music library and placed a copy of some music into it.
   - Finamp now showed everything correctly, as did jellyfin (as a music setup with things like album & genre at the top).
5. Removing the copied music, I copied the same podcast folder into the new test music library.
   - Everything showed correctly on Jellyfin & Finamp.

I have a feeling that there is some kind of initialization by Jellyfin when the first proper scan finishes. Even though I labeled it as a "music" library, it just wouldn't work properly as one. I was even able to mark episodes as played. It just didn't register that this wasn't proper. Once everything was acting as music, Finamp worked as expected.

As requested, here is that log when the screen when grey after clicking the "Podcast" genre.
[finamp.log](https://github.com/jmshrv/finamp/files/9586651/finamp.log)

**Comment by jmshrv** [comment]
Interesting, I'm not sure how well Jellyfin supports podcasts so maybe your server got into some weird state. Glad that it's sort of working though, of course proper support with stuff like remembering where you left off would be great.

Regarding the logs, it looks like a bug in Finamp where splitting albums up into disks fails if the list is empty. It fails on this specific line, where we try to get the first element without checking if it is empty.

https://github.com/jmshrv/finamp/blob/d8f098ed024d74631100edb703dfdfa3fadacf96/lib/components/AlbumScreen/album_screen_content.dart#L29

I'll fix this :)
