### ISSUE TITLE
Apple's Shortcut APP command to set up automatic song playing

### ISSUE THREAD

**Issue by LoyaltyMu** [jmshrv/finamp#332]
Finamp is very useful, thank the author very much. How can I use Apple's Shortcut APP command to set up automatic song playing

**Comment by Y0ngg4n** [comment]
As far as i know that needs custom Swift development for ios.

**Comment by jmshrv** [comment]
Yeah, as far as I know the iOS shortcut API basically depends on the app being structured as a native iOS app, so this won't be feasible (unless Flutter somehow adds support).
