### ISSUE TITLE
32 bit AIFF streaming

### ISSUE THREAD

**Issue by justjakka** [jmshrv/finamp#339]
noticed that when trying to stream 32 bit AIFF files theres no sound

**Comment by jmshrv** [comment]
Which platform?

**Comment by justjakka** [comment]
android

**Comment by jmshrv** [comment]
Looks like AIFF isn't supported in Exoplayer, which Finamp uses to play audio on Android (https://exoplayer.dev/supported-formats.html).

In the short term, enabling transcoding in Finamp should let you play those files. In the long term, this will be fixed by #177.
