### ISSUE TITLE
Can't remove songs from playlists??

### ISSUE THREAD

**Issue by MisterSirCode** [jmshrv/finamp#340]
When I added some songs to my playlist, I accidentally added one I didn't want in it, so I tried to remove it, but theres no button anywhere I can see to remove it.

Swiping just adds to the queue which is strange, most apps use that as the delete function, you swipe and it shows a red delete button. Otherwise, holding down on the song just shows the normal stuff, I can't remove it from the playlist.

**Comment by MisterSirCode** [comment]
On a side note... why are there so many open issues and PRs...

**Comment by Chaphasilor** [comment]
> On a side note... why are there so many open issues and PRs... 

Because it's mostly just one person making the app and there are a lot of users with different expectations :)

So if you happen to know some Flutter, that would be amazing!

**Comment by jmshrv** [comment]
Removing songs from playlists has been something that I was meant to add for a while, it shouldn't be too hard to implement™

As @Chaphasilor said, I'm only one person doing this in my free time. I've been meaning to look through all the issues to clean up duplicates and issues that have been completed, and @Y0ngg4n recently made quite a few PRs that I'm getting through slowly. Feel free to help with getting some of those issues closed though ;)

**Comment by jmshrv** [comment]
Implemented in #382
