### ISSUE TITLE
[Feature Request] Converter for downloaded file type

### ISSUE THREAD

**Issue by LoganJFisher** [jmshrv/finamp#342]
I have all of my music in Jellyfin in a .flac filetype because I prefer to own lossless media and my home server has enough capacity that this feels warranted. My phone, however, only has so much space to go around and so the smaller file size of mp3 files would be preferable. I'd like to request a filetype conversion option when downloading music to your phone in the app.

**Comment by Chaphasilor** [comment]
This is a duplicate of #215 and can be worked on as soon as #213 is resolved.

It would be nice if you could subscribe to these issues instead and close this one, to prevent fragmentation 😁

**Comment by LoganJFisher** [comment]
Will do! Sorry about that - I scrolled through and missed those.

**Comment by Chaphasilor** [comment]
Not a problem, there is a lot to scroll through :p
