### ISSUE TITLE
Feature: Add optional Request View

### ISSUE THREAD

**Issue by Y0ngg4n** [jmshrv/finamp#348]
Maybe we should add an optional (enable by settings) view to send requests to a deemix instance or a lidarr instance.

**Comment by jmshrv** [comment]
I'd say that's a bit out of scope for Finamp, also piracy is a touchy subject that the Jellyfin maintainers stay very far from so it's probably a good idea that we do the same

**Comment by Y0ngg4n** [comment]
@jmshrv ok can understand that
