### ISSUE TITLE
Warning when asking to download an album in FLAC 

### ISSUE THREAD

**Issue by arthurlutz** [jmshrv/finamp#351]
I have a music collection comprised of a mix of MP3s and FLACs. When downloading some albums for offline listening, it would be great if finamp could warn me when trying to download a FLAC album which might fill up my SD card, I would  rather have 5 MP3 albums to listen to than 1 FLAC album (the sound quality of the android device can't really make it worthwhile to have FLAC in this usecase).

**Comment by jmshrv** [comment]
We could probably add a size indicator on the album screen (may already be planned in the redesign? I can't remember off the top of my head), what constitutes a warning changes depending on the person.

**Comment by Chaphasilor** [comment]
Size indicator isn't planned, only a codec/quality indicator.  

There could also be a setting that allows users to specify which codecs should trigger a confirmation?

And if we can get the actual file sizes from the Jellyfin API that could also be added to that setting as a simple threshold (per-track size maybe)...

**Comment by 3ThumbsUp** [comment]
I'm not sure how feasible it is, but for me a preferable solution would be to have the jellyfin server transcode flac to mp3 and download it. My entire music collection is in flac, but I have no use for that on my phone.

**Comment by jmshrv** [comment]
I'd like to add transcoded downloads, there's an open issue for it at #215

**Comment by jmshrv** [comment]
File size has been implemented as part of transcoded downloads, closing this
