### ISSUE TITLE
Quick Connect/SSO Support

### ISSUE THREAD

**Issue by alx-alexpark** [jmshrv/finamp#354]
I use an sso plugin, making the normal password auth disabled. Is there a way to simply add an auth token or api key to get the app working?

**Comment by jmshrv** [comment]
I could probably add a way to pass an API key manually, although proper quick connect support would be much better

**Comment by alx-alexpark** [comment]
I am actually somewhat familiar with flutter, I might try to implement it
myself.

**Comment by Flexusma** [comment]
@alx-alexpark are you actively working on this? I'm tempted to join as well, or start my own branch if you're not working on it atm.

**Comment by 9p4** [comment]
Hi, author of the SSO plugin here. I'm wondering about the status of this as well :)

**Comment by 9p4** [comment]
Although you can set the fallback login mechanism, it isn't ideal.

**Comment by Flexusma** [comment]
I think I might just start working on this.
I don't know if I'll have the time to finish it but we'll see

**Comment by xkcdstickfigure** [comment]
Has anyone started working on this? I might start a branch if not, it'd be a great feature to have :)

**Comment by Flexusma** [comment]
> Has anyone started working on this? I might start a branch if not, it'd be a great feature to have :)

I didn’t end up working on this, I shifted my focus to writing my own management panel, that just utilises the apis. It is a little more work than I expected and I have not had the resources to work on this :/. If you end up doing this though, lmk I’d be happy to help :)

**Comment by Chaphasilor** [comment]
I'll be giving the sign in screen a makeover in the coming days and would like to add some alternative login methods (auth token, QuickConnect). So if any of you want to start implementing some of that functionality, I might be able to use it for the redesign :)

**Comment by Chaphasilor** [comment]
Okay, so Quick Connect is working now. Does anyone here use the [jellyfin-plugin-sso](https://github.com/9p4/jellyfin-plugin-sso), or something similar, and could help with testing?

**Comment by 9p4** [comment]
I'd love to help out with testing. Let me know what needs to be done.

**Comment by Chaphasilor** [comment]
If you're on Android, you just need to install the debug build below. It will install alongside the regular Finamp app, so you can keep using that without issues.

Download link (GitHub doesn't allow APK attachments): https://gofile.io/d/nAkfqF

Then just start the app and log into your server using Quick Connect :)

Alternatively, or if you're on iOS, you'd need to build the `new-login-flow` branch out yourself to test things.

**Comment by 9p4** [comment]
Seems like quick connect works.

**Comment by Chaphasilor** [comment]
Sweet, thanks! Is there anything else that you need or that would make sense for SSO? Anything that the Jellyfin app supports but Finamp does not?

**Comment by 9p4** [comment]
Quick connect is the recommended flow for using the SSO plugin on non-web-enabled apps/devices. As long as quick connect works fine, then it's good!

**Comment by xkcdstickfigure** [comment]
Thanks for implementing this, @Chaphasilor :)

**Comment by TheRealGramdalf** [comment]
> Download link (GitHub doesn't allow APK attachments): https://gofile.io/d/nAkfqF

This link has expired, but I'm eager to try the revamp - is there another dev build link, or should I just wait for the beta to release officially? I'm using jellyfin-sso, so the new version is somewhat necessary as 9p4 said.

**Comment by TheRealGramdalf** [comment]
Also for reference see the [issue about native client support](https://github.com/9p4/jellyfin-plugin-sso/issues/61)

**Comment by Chaphasilor** [comment]
You can wait for the official release or build the branch yourself :)

Regarding the client support issue you linked, that appears to make use of URL handlers, so if anyone has set the Jellyfin app as the default handler, it won't work with Finamp anymore. As long as no default is set, both should work (once this ends up in the server and we implemented support for it). But Quick Connect should work for the time being...

**Comment by TheRealGramdalf** [comment]
Got it, many thanks. I'll have to get around to building it at some point. 
About native support I mainly meant it for "eventually" - definitely not part of the initial UI revamp release. Just something to put on your radar.

**Comment by Chaphasilor** [comment]
@alx-alexpark @xkcdstickfigure @9p4 Quick connected support has now been released as part of the redesign beta. You can check it out here: https://github.com/jmshrv/finamp/releases/tag/0.9.2-beta

I'll close this issue for now since it should be resolved.
