### ISSUE TITLE
Build fails due to chopper 5.1.0 and missing `pubspec.lock`

### ISSUE THREAD

**Issue by Maxr1998** [jmshrv/finamp#360]
`chopper` was recently updated to 5.1.0, pulling this version breaks the build because `baseUrl` was removed from the `Request` class.
According to the [dart glossary](https://dart.dev/tools/pub/glossary#lockfile), the application's `pubspec.lock` should be checked into source control to prevent issues like these.

**Comment by jmshrv** [comment]
I've been meaning to debug that, it's broken on F-Droid because of it. I've removed .lock from .gitignore so this should be fine. I'll also have a look at what I'm meant to use instead of baseUrl

**Comment by jmshrv** [comment]
This has been properly fixed in 5aaa20a3033abab5e33122bebdceac289dbe9219
