### ISSUE TITLE
Download errors that aren't removed when retry download

### ISSUE THREAD

**Issue by arthurlutz** [jmshrv/finamp#364]
The new feature of "redownload" when failed downloads works great, kudos for this improvement. 

I now have another problem : I still have "12 failed". The list has and id as title, and below "Failed to get song from download ID". Clicking the reload button says "No redownloads needed".

**Comment by ryanwwest** [comment]
I encountered a similar problem and included it here: https://github.com/jmshrv/finamp/issues/415

**Comment by Y0ngg4n** [comment]
Asi i fink this is a duplicate of #415 i think we can close this then

**Comment by Chaphasilor** [comment]
Right, thanks for the heads-up @Y0ngg4n 😁
