### ISSUE TITLE
"Add to Mix" bugs

### ISSUE THREAD

**Issue by jmshrv** [jmshrv/finamp#365]
### Discussed in https://github.com/jmshrv/finamp/discussions/357

<div type='discussions-op-text'>

<sup>Originally posted by **unarmedpawn** November 10, 2022</sup>
Not sure how to file a bug report so I'll start a discussion.  
The "add to mix" feature will add albums and the discography of an artist, but will only begin playing the mix from the albums tab.  If invoked on the artists tab a message appears ("long press on an artist...")  directing how to use the "add to mix" feature.  

Also being able to save a mix would be great.

The app is great by the way.  

Specs:
Phone:  Moto g power
OS: android 11
Finamp version:  0.6.8</div>

**Comment by jmshrv** [comment]
@unarmedpawn The mix button on the artists tab is for playing artist mixes, so it's giving that message because you haven't added any artists to the mix.

I'll think about the possibility of saving mixes :)

**Comment by Chaphasilor** [comment]
Saving a mix will be possible when #586 is implemented.

And the interaction for instant mixes will be handled in #271

Closing this in favor of these two issues
