### ISSUE TITLE
Playlists tab constantly spins

### ISSUE THREAD

**Issue by jgoerzen** [jmshrv/finamp#368]
Hello,

Thank you for finamp!  I find it is working well; the Albums, Artists, Genres, and Songs tabs all work fine.  But when I tap on Playlists, I get a constant spinner.  It never loads even one of my playlists.

I have a couple dozen playlists, and some of them have several hundred songs in them.  Nothing too vastly huge AFAIK.

I tried various things to get the tab to work - no luck.

But after stopping finamp and restarting it, playlists seem to work!

**Comment by jmshrv** [comment]
That's odd. Could you send a copy of your logs next time it happens? Logs are sanitised, but double check just in case (the login call isn't sanitised just yet so if you happen to login during that session make sure to remove that line lol)

**Comment by jgoerzen** [comment]
I actually did grab the logs.  There didn't seem to be anything relevant; just enoooormous dumps from the artists/songs views.  I could send them to you privately; you can send me an email address to jgoerzen ..atsign.. complete ..dot.. org

**Comment by Chaphasilor** [comment]
This does happen sometimes if the connection to the server is temporarily lost. A proper refresh (gesture/button) should fix these issues, but needs to be implemented

**Comment by Chaphasilor** [comment]
The proper refresh has been implemented in the beta version now
