### ISSUE TITLE
Allow different sorting for different tabs

### ISSUE THREAD

**Issue by Maxr1998** [jmshrv/finamp#372]
Currently, the sort setting is synchronized between the tabs, so sorting albums by date added also sorts artists by their library addition date.

Preferably, the sort options would be independent. If that is desired, I can look into implementing this in a PR.

**Comment by jmshrv** [comment]
Yeah that would be a nice idea, shouldn't be *too* hard to implement (basically turn the sort option into a hashmap that can be indexed by library type). It would need a migration on FinampSettings, but that shouldn't be too bad
