### ISSUE TITLE
No playback for WMA

### ISSUE THREAD

**Issue by Ombrelin** [jmshrv/finamp#385]
I have a music album using the WMA codec. 
When playing a title from this album, no sound is played. 
See attached logs for the error.
[Logs](https://cloud.arsenelapostolet.fr/s/PEQ9jTtpeemxDTr)

Thanks in advance

**Comment by jmshrv** [comment]
> [MusicPlayerBackgroundTask/SEVERE] 2023-01-18 18:36:23.389611: Player error code 0: Source error

I doubt WMA is supported in ExoPlayer/iOS (depending on platform). Your best course of action will be to encode the album into a more common format, like FLAC or MP3 (if on Android, you could also do Vorbis or OPUS). Eventually, Finamp will support basically every format with #177

**Comment by Ombrelin** [comment]
Thanks for your response, but shouldn't unsupported codec cause the music to by transcoded by jellyfin ?

**Comment by jmshrv** [comment]
Hmm yeah, although Jellyfin's API for automatic transcoding is kind of dodgy so Finamp currently doesn't do it.
