### ISSUE TITLE
The picture is not displayed clearly on iOS

### ISSUE THREAD

**Issue by yuruxuan** [jmshrv/finamp#390]
I manage a large number of music on jellyfin, they have complete metadata and cover art higher than 1000x1000 pixels, but I found that the album art image is still not clear on the play page of finamp.

I checked the source code and found that AlbumImageProvider only requests the cover image as big as the widget. Maybe this is no problem on android or low-density screen devices, but it may not be suitable on iPhone. I hope to check the request image size  on iPhone. 

```
_albumImageContentFuture = AlbumImageProvider.init(
      widget.item,
      maxWidth: widget.maxWidth,
      maxHeight: widget.maxHeight,
      itemsToPrecache: widget.itemsToPrecache,
      context: context,
    );
```

**Comment by jmshrv** [comment]
`AlbumImage` takes pixel density into account, so in theory it should work fine.

https://github.com/jmshrv/finamp/blob/35a65ca0412b3e23846d217c501c85f43e768ee3/lib/components/album_image.dart#L53-L62

Could you send a screenshot of a low-res image being loaded, as well as logs?

**Comment by jmshrv** [comment]
Added a bit of extra logging code in 4e31658, should make it easier (I can't remember if album image loading currently shows up in logs). There's one last thing that I want to add in this release, but it'll be ready soon

**Comment by yuruxuan** [comment]
I review the issue again. I found that the jellyfin server would download album art from the internet to overwrite my original saved art, even if they were blurry.

It's not clear to me why jellyfin does this, but I'm pretty sure it's not finamp's problem. I will close this issue.

**Comment by jmshrv** [comment]
You can disable fetching images in the "manage library" settings of your music library, although it probably shouldn't be overwriting what you already have.

![Screenshot of Jellyfin's manage library settings](https://user-images.githubusercontent.com/44349936/215231866-1180c81a-24e4-459a-801a-bd42c7b51e1b.png)
