### ISSUE TITLE
Big album name ruins bottom of the player

### ISSUE THREAD

**Issue by YSPESHNUY** [jmshrv/finamp#392]
I think it doesn’t require much explanation. Maybe it’s not a thing on a bigger smartphones, but this is what happens on my SE

![46867FEE-9F1D-4EEB-B1AE-03DF28D0A873](https://user-images.githubusercontent.com/79416318/215458015-0272f766-5887-4b76-9627-160d52ce0a14.png)

**Comment by jmshrv** [comment]
The redesign (#230) makes albums one line, I'll apply the same fix to the main branch

**Comment by PowerUser64** [comment]
A related problem is that when there's a long song title, it gets cut off (as seen in @YSPESHNUY's screenshot), and there's no marqee or anything to make the rest of it visible. (I can open a separate issue for this if you want.)

**Comment by jmshrv** [comment]
Yeah go ahead, I'd like something like that :)

**Comment by Chaphasilor** [comment]
@YSPESHNUY the player screen layout has been improved as part of the redesign beta. If there isn't enough space, the album cover should now shrink instead. You can check it out here: https://github.com/jmshrv/finamp/releases/tag/0.9.2-beta

I'll close this issue for now since it should be resolved.
