### ISSUE TITLE
Make adding to favourites visually instant

### ISSUE THREAD

**Issue by YSPESHNUY** [jmshrv/finamp#393]
When adding track to favourites, heart fills with red after a second or so. I think it should be instant, and if it fails to be added to favourite, it should turn grey again and display error message, otherwise app just feels ***slow***

**Comment by jmshrv** [comment]
Changed in fc116227c4c25bfe8c4309f152cb311f92c4a8d1

Instead of going grey, it just disappears again since that's easier to implement 🙃

**Comment by YSPESHNUY** [comment]
Yeah, that's what I meant, sorry
