### ISSUE TITLE
Support .scrobbler.log files?

### ISSUE THREAD

**Issue by powellc** [jmshrv/finamp#395]
Any chance of supporting writing out a .scrobbler.log file when playing songs in offline mode?  This is something that Rockbox supports for last.fm scrobbling and the file format looks like this:

```
#AUDIOSCROBBLER/1.1
#TZ/UNKNOWN
#CLIENT/Rockbox sansaclipplus $Revision$
75 Dollar Bill	I Was Real	I Was Real	4	1015	S	1740494944	64ff5f53-d187-4512-827e-7606c69e66ff
75 Dollar Bill	I Was Real	I Was Real	4	1015	S	1740494990	64ff5f53-d187-4512-827e-7606c69e66ff
311	311	Down	1	173	S	1740495003	00476c23-fd9e-464b-9b27-a62d69f3d4f4
311	311	Jackolantern’s Weather	3	204	L	1740495382	cc3b2dec-5d99-47ea-8930-20bf258be4ea
311	311	All Mixed Up	4	182	L	1740495586	980a78b5-5bdd-4f50-9e3a-e13261e2817b
311	311	Hive	5	179	L	1740495768	18f6dc98-d3a2-4f81-b967-97359d14c68c
311	311	Guns (Are for Pussies)	6	137	L	1740495948	5e97ed9f-c8cc-4282-9cbe-f8e17aee5128
311	311	Misdirected Hostility	7	179	S	1740496085	61ff2c1a-fc9c-44c3-8da1-5e50a44245af
```

Would be pretty sweet to be able to auto upload these files when coming out of offline mode as well. Of course, this whole idea may be crazy when scrobblers usually get connected at the server side for Jellyfin.  But in the absence of a "scrobble from server when back online" a .scrobbler.log file may be simple alternative for offline mode for the time being.

**Comment by jmshrv** [comment]
It would probably be easier to actually implement offline playback tracking/reporting. It's something that I also personally want, so I might start working on it soon :)

**Comment by powellc** [comment]
Awesome news that you're motivated to add it ❤️  One of those times I wish I was more fluent in Android dev to be able to help!

**Comment by powellc** [comment]
Additionally, not to hijack an issue thread. But I love this app. It's the missing link in a perfect home-lab replacement to Spotify. Excellent work, and stewardship!
