### ISSUE TITLE
support .ape file

### ISSUE THREAD

**Issue by zha0yangchen** [jmshrv/finamp#408]
thank you for your great job, but is there any plan to support .ape file?

**Comment by jmshrv** [comment]
Finamp depends on the OS's underlying audio stuff for playback (ExoPlayer on Android, and AVQueuePlayer on iOS). I'd like to instead use something like GStreamer/mpv to support everything on every platform (#177), but that's a big task that I haven't started. For now, I'd recommend converting your .ape files to FLAC.
