### ISSUE TITLE
[Feature Request] Playback speed

### ISSUE THREAD

**Issue by YourSandwich** [jmshrv/finamp#412]
Hi and thank you for developing this awesome app!

I would like to request a playback speed change option.

I'm a speed freak, so please give me an option to get a hearth stroke, I need this 250bpm. 
Ideally without changing the pitch of the sound.

**Comment by jmshrv** [comment]
This should be easy to add, as just_audio can handle it: https://pub.dev/documentation/just_audio/latest/just_audio/AudioPlayer/setSpeed.html

**Comment by Chaphasilor** [comment]
@YourSandwich this is now available with the latest beta update, 0.9.6. Let me know if you have any issues with it!

**Comment by YourSandwich** [comment]
@Chaphasilor Hi, thank you for implementing the feature. 
I noticed there is a pretty big delay between changing the speed, but that's not so important.

There is a big quality decrease by increasing the playback speed, at least for songs. 
Mostly noticeable at the lower spectrum 20-300hz I was testing at x1.5 and comparing against the game osu!

To make sure osu is not implementing any special filter or something, I've also tried mpv which offers similar quality to osu.
But since from reading the changelog I assume this was primarily implemented for podcasts, I assume music is a second priority.

I hope this can be improved.

Thank you for your contributions <3

**Comment by Chaphasilor** [comment]
Hi, thanks for the report. I confirmed that it takes almost a second to update the speed, but that sadly isn't handled by Finamp. Same for the audio quality; this is handled by a plugin that applies the speed change using the native implementations on Android and iOS, and not something we do ourself.

So I don't think there's any improvement to be had in that regard 😅

For the upcoming desktop support we are actually using anpv-based audio backend in some cases, but I'm not sure if a) it supports changing the playback speed or b) it works on Android and iOS. I'll try to remember testing that out at some point...

**Comment by YourSandwich** [comment]
Thank you for clarifying!

**Comment by YourSandwich** [comment]
I just found out that MPV uses the rubberband filter for pitch correction, which is imported from librubberband
Maybe the Plugin @Chaphasilor you were talking about can specify one of the filters.

Also, there is a filter called scaletempo which is worse but still much better what Finamp currently does :<

All the details can be found in the Manual pages for MPV under section AUDIO FILTERS

**Comment by YourSandwich** [comment]
Hi, was this feature removed?
Cannot see it in the menu anymore.
