### ISSUE TITLE
[Feature request] Play directly from artist page

### ISSUE THREAD

**Issue by manuel-rw** [jmshrv/finamp#424]
Hello,
first I would like to thank you for this project.
It has helped me out a lot.

One thing, that bothers me a lot though is, that playing all albums of an artist is incredibly cumbersome.

I think there should be a button to play all albums of an artist, without adding them to the mixer.

Maybe a simple button here would do the job?
![Screenshot_2023-04-05-08-43-52-888-edit_com.unicornsonlsd.finamp.jpg](https://user-images.githubusercontent.com/30572287/230001843-f658a2e0-bf72-4c8f-9a2a-68afe4e61e78.jpg)

**Comment by jmshrv** [comment]
Very similar to #35, but I'll leave this separately. I like the idea of that UI implementation, would be very easy to throw together. #220 has more plans for the artist screen :)

**Comment by manuel-rw** [comment]
Sorry, didn't see those issues. But leaving this separate is fine too :)
