### ISSUE TITLE
[Feature request] Could this app support 2-steps verifacation login on Jellyfin server?

### ISSUE THREAD

**Issue by 702781** [jmshrv/finamp#425]
Jellyfin server which I am using is installed on a Synology NAS which has 2-step verifacation while login, but I find this APP can only support username+pwd login, so always failed, could you consider to add  2-step verifacation on server login?

**Comment by jmshrv** [comment]
What plugin are you using to use 2FA?

**Comment by 702781** [comment]
> What plugin are you using to use 2FA?

It's a Google 2FA, attached by Synology DSM system.

**Comment by jmshrv** [comment]
Does it make you go through some kind of redirect to put in the 2FA? I can't find much about how it works online

**Comment by Chaphasilor** [comment]
I'm guessing Synology is redirecting you to a login page, where you log in with SSO and it then sets a HTTP cookie, before redirecting you to the actual Jellyfin login page. If the Synology cookie is missing, any request would be redirected.  
The only two ways to support this that I see would be to a) support configuring custom cookies (should be simple enough to implement if needed), or b) allow opening the login page in a webview, and extracting any cookies that were set at the end, including the Synology and Jellyfin/EmbyAuth tokens.

However I'll only look into this further if anyone actually needs such a feature. I'll go ahead and close this issue in a few days/weeks unless there's activity, and if someone does has such a problem later on they can open a new issue.

**Comment by jmshrv** [comment]
It's probably not really worth supporting weird auth stuff like this, it'd be pretty hacky and Jellyfin has dedicated plugins for SSO that still allow clients to work via Quick Connect (which @Chaphasilor has been working on :) )
