### ISSUE TITLE
Switching between different music libraries does not automatically change the color of the selected library

### ISSUE THREAD

**Issue by StayBlue** [jmshrv/finamp#428]
If you try switching between two different libraries, at least on iOS, the selected library will not change color properly. Collapsing the menu and re-opening it again does fix it, though.

**Comment by jmshrv** [comment]
Could you send a screen recording of this? I don't use multiple libraries, so it hasn't been tested since I last used it

**Comment by StayBlue** [comment]
> Could you send a screen recording of this? I don't use multiple libraries, so it hasn't been tested since I implemented it

https://user-images.githubusercontent.com/23127866/232859249-5db7c351-61c7-4806-9477-82f2a5472e3f.MOV

**Comment by jmshrv** [comment]
Ah yeah I can imagine what would cause that, will have a look

**Comment by Chaphasilor** [comment]
@StayBlue this has now been fixed and released as part of the redesign beta. You can check it out here: https://github.com/jmshrv/finamp/releases/tag/0.9.2-beta

I'll close this issue for now since it should be resolved.
