### ISSUE TITLE
[Feature request] App language selection

### ISSUE THREAD

**Issue by SuperDumbTM** [jmshrv/finamp#429]
I don't know whether this functionality is already on the roadmap, but it would be great if the app supports language selection.

**Comment by jmshrv** [comment]
This is doable in iOS via iOS Settings, but it looks like the equivalent on Android has only just been introduced (and Finamp needs to actually tell it what languages it supports).

https://developer.android.com/guide/topics/resources/app-languages

**Comment by SuperDumbTM** [comment]
Ohhh I didn't know that. But my suggestion is that a dropdown box inside the app to choose the app language.

I once did something similar. Maybe I could create a PR after I have studied the Finamp if this is not your priority.

```dart
class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State MyApp> createState() =>  MyAppState();

  /// Sets the locale of the app to the specified [newLocale].
  static void setLocale(BuildContext context, Locale newLocale) {
     MyAppState? state = context.findAncestorStateOfType< MyAppState>();
    state!.setLocale(newLocale);
  }
}

class  MyAppState extends State MyApp> {
  Locale _locale = Locale('en');

  void setLocale(Locale value) => setState(() => _locale = value);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'MyApp',
      locale: _locale,
      localizationsDelegates: L10n.localizationsDelegates,
      supportedLocales: L10n.supportedLocales,
      theme: ThemeData(
        primarySwatch: def.AppColor.theme,
      ),
      home: MyAppLayout(),
      routes: routes,
    );
  }
}
```

**Comment by jmshrv** [comment]
It shouldn't be too hard to add, I'll work on it now :)

**Comment by SuperDumbTM** [comment]
appreciate it!!

**Comment by jmshrv** [comment]
An initial implementation has been added in 26754a7. There are a few things left to do:

* Switching from system to a locale with the same value causes weird things to happen in the selection UI (e.g., going from English to System when the system language is English)
* We need a button to access the language screen at login

**Comment by jmshrv** [comment]
Done, making a release now :)
