### ISSUE TITLE
I've came across the app just now and want to try it for the offline playback capability. I've used Gelli so far (a fork of Phonograph) and while finamp's UI is not terrible, I think Gelli/Phonograph – while still quite minimal – are a wee bit neater.

### ISSUE THREAD

**Issue by Vladimirovicp402** [jmshrv/finamp#436]
I've came across the app just now and want to try it for the offline playback capability. I've used Gelli so far (a fork of Phonograph) and while finamp's UI is not terrible, I think Gelli/Phonograph – while still quite minimal – are a wee bit neater.

Some colors go a long way to make it more readable and the "now playing" screen is considerably more slick – it infers a matching background colour from the album art (the audio notification also follows that colour, which is neat) and has a really nice quick playlist access, you can even swipe it up to easily navigate to past items. It also has an alternative layout for the landscape mode that works well (I think finamp doesn't). The navigation is also more fluid – for example when you're in the track list mode and you have that bar at bottom showing the current track, then swiping it up has a continuous fluid motion of it transforming into a full screen view (while finamp has a basic fade instead), making it a subjectively more smooth experience.

I'm not sure how much exactly should you ape Gelli/Phonograph, but I'd give them a spin and try navigating around (Gelli should be easier one to try, since it's also a Jellyfin client) and see how a very similar basic layout of the application feels much more polished due to just a few small differences and consistent attention to UX details. I feel like you don't have to reinvent the UI totally (it's already quite similar to Gelli/Phonograph, which I think works well), just invest a bit into polish. Also, the UI seems to lag quite a bit (and even sometimes crashes) when you're batch downloading stuff, I'd look into it (I queued some whole artists for ~5k downloads).

Hopefully it's an useful 2 cents.

_Originally posted by @jaen in https://github.com/jmshrv/finamp/issues/220#issuecomment-1116738929_

**Comment by Chaphasilor** [comment]
wtf is this? a bot that extracts comments into issues?

**Comment by jmshrv** [comment]
Closing as this seems to just be quoting another issue
