### ISSUE TITLE
Crash on iOS 13.7

### ISSUE THREAD

**Issue by yuruxuan** [jmshrv/finamp#437]
Hello every great developer, I see new iOS version(0.6.11) was pubilshed on app store. After update 0.6.11, I can not open Finamp. And I try to uninstall and reinstall. But the new version of the app was still not successfully run. I'm pretty sure there was nothing wrong with the last version. Please review these commit until last release version and fix it 🤪.  By the way, I use another iPhone(iOS 16.4.1) to install new Finamp. It works without problem.

I don't have Xcode on my old mac. So I can't provide detailed logs. But I see there is a line say 'terminationReasonNamespace":"DYLD"'. Does this mean that some dylib is missing on iOS13 ? This is just my guess😆. 

```
Default	20:27:23.555217+0800	runningboardd	Started job UIKitApplication:com.unicornsonlsd.finamp-ios[11a2][rb-legacy]
Default	20:27:23.558415+0800	runningboardd	[application<com.unicornsonlsd.finamp-ios>:8250] This process will be managed.
Default	20:27:23.558492+0800	runningboardd	Now tracking process: [application<com.unicornsonlsd.finamp-ios>:8250]
Default	20:27:23.558749+0800	runningboardd	Calculated state for application<com.unicornsonlsd.finamp-ios>: running-active (role: UserInteractiveNonFocal)
Default	20:27:23.559410+0800	SpringBoard	[application<com.unicornsonlsd.finamp-ios>:8250] Bootstrap success!
Default	20:27:23.559653+0800	runningboardd	Finished acquiring assertion 28-56-87433 (target:application<com.unicornsonlsd.finamp-ios>)
Default	20:27:23.560597+0800	SpringBoard	[application<com.unicornsonlsd.finamp-ios>:8250] Setting process task state to: Running
Default	20:27:23.564326+0800	runningboardd	Acquiring assertion targeting application<com.unicornsonlsd.finamp-ios>(com.apple.frontboard.workspace) from originator [daemon<com.apple.SpringBoard>:56] with description <RBSAssertionDescriptor; "injecting "com.apple.frontboard"-"com.apple.frontboard.workspace-service" to 8250<com.apple.frontboard.workspace>"; ID: 28-56-87435; target: 8250<com.apple.frontboard.workspace>> attributes = {
    <RBSHereditaryGrant: 0x113d85f20> {
        endowmentNamespace = com.apple.boardservices.endpoint-injection;
        hasEncodedEndowment = YES;
    };
}
Default	20:27:23.564357+0800	runningboardd	Assertion 28-56-87435 (target:application<com.unicornsonlsd.finamp-ios>(com.apple.frontboard.workspace)) will be created as active
Default	20:27:23.566792+0800	runningboardd	Calculated state for application<com.unicornsonlsd.finamp-ios>: running-active (role: UserInteractiveNonFocal)
Default	20:27:23.566942+0800	runningboardd	[application<com.unicornsonlsd.finamp-ios>:8250] Set jetsam priority to 10 [0] flag[1]
Default	20:27:23.566982+0800	runningboardd	[application<com.unicornsonlsd.finamp-ios>:8250] Resuming task.
Default	20:27:23.567586+0800	runningboardd	[application<com.unicornsonlsd.finamp-ios>:8250] Set darwin role to: UserInteractiveNonFocal
Default	20:27:23.567670+0800	runningboardd	[application<com.unicornsonlsd.finamp-ios>:8250] Set GPU priority to "allow"
Default	20:27:23.568140+0800	mediaserverd	-CMSessionMgr- CMSessionMgrHandleApplicationStateChange: CMSession: Client com.unicornsonlsd.finamp-ios with pid '8250' is now Foreground Running. Background entitlement: YES ActiveLongFormVideoSession: NO WhitelistedLongFormVideoApp NO
Default	20:27:23.569601+0800	powerd	Process runningboardd.28 Created SystemIsActive "application<com.unicornsonlsd.finamp-ios>28-56-87433:FBApplicationProcess" age:00:00:00  id:51539643855 [System: SysAct]
Default	20:27:23.572782+0800	runningboardd	Finished acquiring assertion 28-56-87435 (target:application<com.unicornsonlsd.finamp-ios>(com.apple.frontboard.workspace))
Default	20:27:23.576178+0800	runningboardd	Acquiring assertion targeting application<com.unicornsonlsd.finamp-ios> from originator [daemon<com.apple.SpringBoard>:56] with description <RBSAssertionDescriptor; "Subordinate Process"; ID: 28-56-87436; target: 8250> attributes = {
    <RBSSubordinateProcessAttribute: 0x113d16b90>;
}
Default	20:27:23.576221+0800	runningboardd	Assertion 28-56-87436 (target:application<com.unicornsonlsd.finamp-ios>) will be created as active
Default	20:27:23.576586+0800	SpringBoard	Now tracking: <FBScene: 0x280b17240; sceneID: sceneID:com.unicornsonlsd.finamp-ios-default; valid: YES>
Default	20:27:23.576628+0800	SpringBoard	[sceneID:com.unicornsonlsd.finamp-ios-default] Setting deactivation reasons to: 'systemAnimation' for reason: scene settings update - settings are eligible for deactivation reasons.
Default	20:27:23.577164+0800	runningboardd	Calculated state for application<com.unicornsonlsd.finamp-ios>: running-active (role: UserInteractiveNonFocal)
Default	20:27:23.577446+0800	runningboardd	Finished acquiring assertion 28-56-87436 (target:application<com.unicornsonlsd.finamp-ios>)
Default	20:27:23.583471+0800	SpringBoard	Application process state changed for com.unicornsonlsd.finamp-ios: <SBApplicationProcessState: 0x283f760a0; pid: 8250; taskState: Running; visibility: Unknown>
Default	20:27:23.599549+0800	locationd	{"msg":"#CLIUA Marking change", "clientKey":"com.unicornsonlsd.finamp-ios", "reason":"Process state from RunningBoard", "assertionLevel":4, "coming":1}
Default	20:27:23.613459+0800	symptomsd	com.unicornsonlsd.finamp-ios: Foreground: true
Default	20:27:23.786880+0800	runningboardd	[application<com.unicornsonlsd.finamp-ios>:8250] Death sentinel fired!
Default	20:27:23.877114+0800	SpringBoard	[sceneID:com.unicornsonlsd.finamp-ios-default] Setting deactivation reasons to: '(none)' for reason: updateAllScenesForBand - Assertion removed.
Default	20:27:23.894591+0800	ReportCrash	Sending event: com.apple.stability.crash {"appVersion":"0.6.11","bundleID":"com.unicornsonlsd.finamp-ios","exceptionCodes":"0x0000000000000000, 0x0000000000000000","logwritten":1,"process":"Runner","terminationReasonExceptionCode":"0x9","terminationReasonNamespace":"DYLD"}
Default	20:27:23.896100+0800	runningboardd	Removing process: [application<com.unicornsonlsd.finamp-ios>:8250]
Default	20:27:23.896807+0800	runningboardd	[application<com.unicornsonlsd.finamp-ios>:8250] Deleting job: UIKitApplication:com.unicornsonlsd.finamp-ios[11a2][rb-legacy]
Default	20:27:23.896856+0800	runningboardd	Removing job: <RBLaunchdJob: 0x113d3e9b0; pid=8250 UIKitApplication:com.unicornsonlsd.finamp-ios[11a2][rb-legacy]>
Default	20:27:23.896984+0800	runningboardd	Removed job with label: UIKitApplication:com.unicornsonlsd.finamp-ios[11a2][rb-legacy]
Default	20:27:23.897036+0800	runningboardd	Removing assertions for terminated process: [application<com.unicornsonlsd.finamp-ios>:8250]
Default	20:27:23.897106+0800	runningboardd	Removed last relative-start-date-defining assertion for process application<com.unicornsonlsd.finamp-ios>
Default	20:27:23.897614+0800	runningboardd	Calculated state for application<com.unicornsonlsd.finamp-ios>: none (role: None)
Default	20:27:23.898698+0800	powerd	Process runningboardd.28 Released SystemIsActive "application<com.unicornsonlsd.finamp-ios>28-56-87433:FBApplicationProcess" age:00:00:00  id:51539643855 [System: PrevIdle SysAct]

```

**Comment by yuruxuan** [comment]
My iPhone is iPhone SE2 with iOS 13.7.

**Comment by jmshrv** [comment]
Thanks for the detailed logs, I'll get a Catalina VM up and hope that I can reproduce the issue in a simulator there. If not, would you be happy to join a TestFlight so that I could collect crash logs? I can't send a link now because Apple wants to review it (even when using the same release lol).

iOS 13 is pretty old, but I'd still like to support it if possible

**Comment by yuruxuan** [comment]
OK, waiting your good msg : )

**Comment by jmshrv** [comment]
I can't reproduce on a simulator, could you try this TestFlight link? Hopefully it'll cause a crash log to get sent

https://testflight.apple.com/join/AyqD6mj7

**Comment by yuruxuan** [comment]
I joined it. I try to open Finamp twice and App crashes twice.

**Comment by jmshrv** [comment]
Thanks, I can see the crash reports on App Store Connect, hopefully they show up in Xcode soon. Just wondering, why are you running such an old iOS version?

<img width="816" alt="Screenshot of crash feedback" src="https://user-images.githubusercontent.com/44349936/233418308-1e5e13d3-07a7-4f9f-95ea-45d13e2f812d.png">

**Comment by yuruxuan** [comment]
LOL. Because my Macbook system version is old, it seems that it can only work with the same old iOS version, such as relay and airdrop.

**Comment by jmshrv** [comment]
Ah ok lol, still no crash reports just yet :upside_down_face: 

As for your old Mac, have you considered [OpenCore Legacy Patcher](https://dortania.github.io/OpenCore-Legacy-Patcher/)?

**Comment by yuruxuan** [comment]
Too strange. 😞 

I set up  Flutter development environment on a Mac. However, I found that the compiled APP will not crash on my iPhone SE2 (whether it is Debug or Release). Even if I rolled back the code to 0.6.11+29 (commit b4c330e0), Finamp still works fine.

But, but I still can't run the Testflight version and the App Store version of Finamp on my SE2.

I see new finamp was published on Github. You can publish it on Testflight. Maybe nothing wrong happened.

By the way, could you tell me what which xcode and [CocoaPods](https://github.com/CocoaPods/CocoaPods) version you used?

**Comment by jmshrv** [comment]
That's very weird. 0.6.14 is currently in app review, I've put it in review for Testflight too.

I'm using XCode 14.3, and CocoaPods 1.11.3.

**Comment by yuruxuan** [comment]
The new Testflight version has been received, unfortunately it still doesn't work on my phone.

After a little effort, I found the local logs, which you may have seen in the Testflight background. I attach it here. Similarly, I uploaded my packaged iOS Archive.

I want to compare the difference between the ipa I packaged and the ipa you packaged in the dynamic link library, maybe this will find some differences.

PS: If you are tired of fixing my old iOS-specific problems, you can tell me and close this question. After all, developers' time is precious. 🥱 

Archive pkg: https://drive.google.com/file/d/1lo9BDpCxVHKNkLh_Vu-cBfLD_OHHiF3e/view?usp=share_link
Crash log is in attch file: [Runner-2023-04-26-075852.ips.beta.zip](https://github.com/jmshrv/finamp/files/11327960/Runner-2023-04-26-075852.ips.beta.zip)

**Comment by yuruxuan** [comment]
> ode 14.3, and CocoaPods

Oh！I think I found the cause of the problem. You can see this [Xcode 14.3: App built is not able to open on iOS 13.6](https://developer.apple.com/forums/thread/727680). 

I see a developer say: 'Don't upgrade to xcode 14.3, unless your app need just work on iOS above 13.0 version, if you have upgraded, delete it and download xcode 14.2 from 'https://developer.apple.com/download/all/'.'

**Comment by jmshrv** [comment]
Thanks for looking into this! Hopefully this gets fixed soon, for now I'll build Finamp with 14.2.

Building Flutter apps for iOS is horrible sometimes, everytime I wipe my laptop I have to fight Cocoapods to get anything working.

**Comment by yuruxuan** [comment]
😆OK, Waiting new version on App Store or Testflight.

**Comment by jmshrv** [comment]
TestFlight submission sent, should be ready in about a day

**Comment by yuruxuan** [comment]
Nice job! The new Testflight version is work. 👍

**Comment by jmshrv** [comment]
Thanks for your help diagnosing the issue, I'll stick to Xcode 14.2 until the issue is fixed :)

**Comment by yuruxuan** [comment]
> Thanks for your help diagnosing the issue, I'll stick to Xcode 14.2 until the issue is fixed :)

Xcode 14.3.1 RC fix this issue. You can see https://developer.apple.com/documentation/xcode-release-notes/xcode-14_3_1-release-notes
