### ISSUE TITLE
Feature: Remove from Playlist

### ISSUE THREAD

**Issue by Emporea** [jmshrv/finamp#439]
It would be very useful to have the counterpart of the new "Add to Playlist" feature.

**Comment by jmshrv** [comment]
Removing from playlists was added in 0.6.11 (#382). Did you mean something else?

**Comment by Chaphasilor** [comment]
> Finamp would have to monitor the current playlist that is played

This will be part of the redesign, so it's absolutely doable!

**Comment by Chaphasilor** [comment]
This was initially added in 0.9.7, and will be improved in 0.9.9
