### ISSUE TITLE
Crashing when in background (iOS 16.4.1)

### ISSUE THREAD

**Issue by ttrv65ebyng** [jmshrv/finamp#440]
Unfortunately since the app doesn't seem to show logs from before the most recent launch, I don't seem to have a way to check what's causing the crashing until I'm back at my computer. I'll update when I do so, but in the meantime, is anyone else having this issue? This is on 0.6.14 but I've also tried updating to the Testflight (0.6.15) with no luck. I also restarted my phone thinking memory consumption from some other app was killing it, but no dice there either.

**Comment by yuruxuan** [comment]
I try to use App Store version on my iPhone 8 Plus(16.4.1). And I don't meet crash when music playing in background.  😞 
Give the developer  crash log so the problem might be easier to fix. 

1. If you using testflight version, after the app crashes, a window will pop up asking whether to share the crash information to the developer. Click "Share" and fill in your email and other information. In this way, developers will see the crash information in the Testflight management interface.
2. You can also found the log at: Settings > Privacy > Analytics & Improvements > Analytics Data > Found item like 'Runner-2023-04-27-075852.ips.beta', this is crash log.

**Comment by ttrv65ebyng** [comment]
Thanks! Appears the app was at 99% CPU usage for too long? 
[Runner.cpu_resource_fatal-2023-04-28-071526.txt](https://github.com/jmshrv/finamp/files/11353038/Runner.cpu_resource_fatal-2023-04-28-071526.txt)

(Relevant part):
```
Event:            cpu usage
Action taken:     Process killed
CPU:              48 seconds cpu time over 48 seconds (99% cpu average), exceeding limit of 80% cpu over 60 seconds
CPU limit:        48s
Limit duration:   60s
CPU used:         48s
CPU duration:     48s
Duration:         48.37s
Duration Sampled: 46.67s
Steps:            25
```

**Comment by ttrv65ebyng** [comment]
As far as the TestFlight popup, because it only happens in background with other apps fronting or on a locked device, I am for some not getting that pop up that appears after a crash :(

**Comment by jmshrv** [comment]
Looks like yet another issue with downloading :upside_down_face: 

How much storage do you have on your phone, and how many downloads did you have in Finamp?

**Comment by ttrv65ebyng** [comment]
Any update on this issue? It's been crashing for the last week about 9 out of 10 times I attempt to background the app (every once in a while it surprises me by not crashing when my phone locks after going into Low Power Mode). The only solution I can see right now, which I'd prefer to avoid, is to delete all my downloaded music, remove and re-add my server to then redownload all the music.

**Comment by jmshrv** [comment]
It sounds like the download plugin has died on you, your best course of action is probably reinstalling the app :(

Stuff like this should be fixed in #213

**Comment by ttrv65ebyng** [comment]
I can still download new items however, strangely enough, so I don't think the downloader has died. But I'll try reinstallation when I get a chance.

**Comment by ttrv65ebyng** [comment]
Reinstalling has indeed fixed the issue.
