### ISSUE TITLE
Download of favorite Tracks

### ISSUE THREAD

**Issue by Y0ngg4n** [jmshrv/finamp#449]
We should provide a way to download all tracks that are marked as favorite. Currentlx you need to place them in a playlist and download them. Maybe we can create a "static playlist" internally for all favorited tracks so we can map all favorited tracks to it.

**Comment by Chaphasilor** [comment]
Yeah, smart playlists with all kinds of filters makes sense. And some smart playlists, like favorite tracks, could be immutable (always there, no way to edit or delete them).  
The hard part will be handling downloaded tracks that are removed from favorites, those could then be deleted from the device during the next sync. But of course they should only be deleted if they aren't part of another playlist that is set to be downloaded.

**Comment by Y0ngg4n** [comment]
@Chaphasilor that sounds great 🙂👍

**Comment by Chaphasilor** [comment]
Will probably require some rework though, and the new downloader. I wouldn't try to integrate this with the current implementation 😅

**Comment by Y0ngg4n** [comment]
@Chaphasilor how far is the issue with the new downloader currently?

**Comment by Chaphasilor** [comment]
Afaik, the work on https://github.com/jmshrv/flutter_download_manager has been abandoned in favor of https://pub.dev/packages/background_downloader.  
That's it so far. So the next steps would probably be to familiarize ourselves with that package, plan how the new system should work, and then implement it :)

**Comment by Chaphasilor** [comment]
So the new download system will add support for this, although without using "smart playlists" :)

**Comment by Chaphasilor** [comment]
The download system has been improved as part of the redesign beta. There's now an option to download all favorites in the download settings. It will download all favorites, including albums, artists, playlists, and of course songs.  
You can check the beta out here: https://github.com/jmshrv/finamp/releases/tag/0.9.2-beta

The issue of some kind of "smart playlist" or maybe "smart *collection*" still remains though, but I think that's a different issue.
