### ISSUE TITLE
Cover Art not showing in 'Now Playing' Screen

### ISSUE THREAD

**Issue by prasta** [jmshrv/finamp#450]
When you visit the now playing screen, the Album cover art does not appear, but it does elsewhere. This seems to be related to having no cover art stored with the sound files in the folder (ie. cover.jpg or front.jpg) yet in certain scenarios (captured below) the art is able to be extracted from the .NFO file. I've reached the limit of my technical know-how here, but figured I'd share in case this is not expected behavior. 

iPad Pro (11-inch) (2nd generation) running iPadOS 16.6 (20G5026e)

I've attached some screenshots demonstrating what I'm referring to:  

** The 'Now Playing Screen' **

![image](https://github.com/jmshrv/finamp/assets/2895959/00952d6b-91ef-4352-b392-455c90047ac5)

** The song queue, when expanded from the now playing screen **

![image](https://github.com/jmshrv/finamp/assets/2895959/77681817-ba63-455f-a296-8cad3650d940)

** The Album View **

![image](https://github.com/jmshrv/finamp/assets/2895959/b5d95d7c-6523-4800-8feb-0321d3f10d23)

** The Library View showing the track playing along the bottom of the UI **

![image](https://github.com/jmshrv/finamp/assets/2895959/9b572afb-8437-4e9f-8909-a55c70fec52e)

🤘

**Comment by Chaphasilor** [comment]
@prasta could you please check if the redesign beta solved this bug for you? You can find it at https://github.com/jmshrv/finamp/releases/tag/0.9.2-beta :)

**Comment by prasta** [comment]
Thanks for following up, this appears to have been resolved on my iPhone, but attempting to reproduce on the iPad I sent you the screenshots from, I’m now met with following error, when attempting to view songs by album, artist, etc. I’m currently logging out and attempting to log back in, hoping that will refresh the underlying caches, etc. On Feb 28, 2024, at 8:19 AM, Chaphasilor ***@***.***> ***@***.*** could you please check if the redesign beta solved this bug for you? You can find it at https://github.com/jmshrv/finamp/releases/tag/0.9.2-beta :)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by prasta** [comment]
Re-forwarding with smaller image, since GitHub didnt seem to like my original file size. 
￼


> Begin forwarded message:
> 
> From: Patrick Ruster ***@***.***>
> Subject: Re: [jmshrv/finamp] Cover Art not showing in 'Now Playing' Screen (Issue #450)
> Date: February 28, 2024 at 8:44:18 AM EST
> To: jmshrv/finamp ***@***.***>
> Cc: jmshrv/finamp ***@***.***>, Mention ***@***.***>
> 
> 
> Confirming. Logging out and back in has resolved the error. Now playing screen seems to appear as designed. 
> 
> 
>

**Comment by Chaphasilor** [comment]
I sadly can't see the image, you might have to attach it via the GitHub website. You might also wanna join our Discord server if that's possible for you, that would make debugging your issue a bit easier :)

**Comment by Chaphasilor** [comment]
@prasta could you try again with the most recent beta update (0.9.5)?
