### ISSUE TITLE
[Feature Request] Sort Tabs

### ISSUE THREAD

**Issue by djohnson1865** [jmshrv/finamp#452]
I would love to be able to change the sort order/default tab for Finamp. 
Currently you can toggle on/of different tabs, but cannot sort them in any way. 

Personally I prefer a different sort order and would love for Artists to be the default view. If the Tabs UI setting page had a drag/drop sort with the first tab always being default, that would be excellent.

**Comment by jmshrv** [comment]
Added in 7289eb0
