### ISSUE TITLE
120hz support on iOS?

### ISSUE THREAD

**Issue by Sukuratchi** [jmshrv/finamp#455]
App runs at 60fps on 120hz capable iPhones

**Comment by jmshrv** [comment]
This is caused by Finamp not having `CADisableMinimumFrameDurationOnPhone` set to `true` in `Info.plist`, as new Flutter apps do by default. I'll fix it for the next release :)

**Comment by jmshrv** [comment]
Forgot to put it in 0.6.15, fixed now in e86c5d7
