### ISSUE TITLE
Want to add the function of displaying lyrics

### ISSUE THREAD

**Issue by mlb0925** [jmshrv/finamp#456]
Repo: https://raw.githubusercontent.com/1hitsong/jellylyrics/main/manifest.json
Source Code & API info: https://github.com/1hitsong/jellylyrics
api address http://localhost:8096/Items/e3d3f64aed2c96b45d84f6ad0318a0c0/Lyrics
Hope to display the lyrics UI

**Comment by Chaphasilor** [comment]
This plugin is outdated and unmaintained. @1hitsong already made a successful PR to the main repo, so Jellyfin 10.9 will have built-in lyrics support:

https://features.jellyfin.org/posts/285/add-lyrics-to-songs

https://github.com/jellyfin/jellyfin/pull/8381

**Comment by 1hitsong** [comment]
I've archived the plugin repo. Since the functionality was merged into core, there is no need for the plugin.

**Comment by mlb0925** [comment]
@Chaphasilor @1hitsong  Thanks!
