### ISSUE TITLE
Feature request: ReplayGain/ normalize volume support

### ISSUE THREAD

**Issue by halnine** [jmshrv/finamp#468]
This would be a great thing to have, especially since I haven't found an Android Jellyfin client that supports it.

**Comment by Chaphasilor** [comment]
Server-side support should land in Jellyfin 10.9: https://github.com/jellyfin/jellyfin/pull/9222

We are planning to add support for this in time, at least for the upcoming redesign beta :)

**Comment by Chaphasilor** [comment]
I've started working on this feature and made good progress so far, at least for Android. iOS seems to be a bit more tricky and won't work perfectly, but I hope it'll be better than nothing :)

**Comment by Chaphasilor** [comment]
@halnine @sersorrel this has been implemented as part of the redesign beta. However, it will only start working once Jellyfin 10.9 is released with proper server-side support for volume normalization. You can check the beta out here: https://github.com/jmshrv/finamp/releases/tag/0.9.2-beta
