### ISSUE TITLE
Downloads stuck in queue.

### ISSUE THREAD

**Issue by FatherMcGruder** [jmshrv/finamp#470]
I'm running Finamp version 0.6.14 on my OnePlus 7t smartphone with Android 12. Whenever I try to download an album or playlist in Finamp, nothing actually downloads. The enqueued count just increases. The download location is set to default. I am able to download individual songs with the Jellyfin app (connected to the same server) just fine.

I discovered the problem a few days ago when I was not connected to wifi and tried to play some songs that I thought I already downloaded. I switched Finamp to offline mode, but couldn't play anything. When I checked later on, I realized that none of the songs had been downloaded. The Finamp downloads menu just says I have 62 songs enqueued and none downloaded. Am I doing something wrong or is there something wrong with Finamp (perhaps in combination with my device)?

**Comment by jmshrv** [comment]
Could you try downloading something, and then send your logs? The current download system is a bit finicky, I plan to replace it when I can

**Comment by FatherMcGruder** [comment]
I tried it again and it apparently works now, at least for the music files. It seems like image files (I guess for the album art) will not download. Not sure how to efficiently grab the relevant portion of the logs from my smartphone.

**Comment by jmshrv** [comment]
You can send all of it, I'll sort through it lol

Are downloads getting stuck in the "enqueued" status?

**Comment by FatherMcGruder** [comment]
The problem seems to have resolved itself. If it comes back, I will share the logs.
