### ISSUE TITLE
Cannot download huge playlists at slow connections

### ISSUE THREAD

**Issue by asgardius** [jmshrv/finamp#48]
I can download CD quality FLAC music albums without issues, but when i attempt download hi-res FLAC albums, running downloads stop and start downloading other songs from download queue. Here is app log
[finamp.log](https://github.com/UnicornsOnLSD/finamp/files/6539828/finamp.log)

**Comment by asgardius** [comment]
WHITE PLACE from Mashiro Ayano. This album is encoded at 24 bit/48 khz

**Comment by asgardius** [comment]
After switching to a faster network connection i could download any album without issues. This problem could be related to playlist size and network bandwidth

**Comment by UnicornsOnLSD** [comment]
It's probably just the connection dropping and the download failing. Jellyfin downloads don't have any fancy techniques to continue after a failure, so there isn't much I can do about it. This issue would be "fixed" by adding a retry button to the download error screen.

**Comment by Chaphasilor** [comment]
@asgardius the download system has been improved as part of the redesign beta. You can check it out here: https://github.com/jmshrv/finamp/releases/tag/0.9.2-beta

I'll close this issue for now since it should be resolved.
