### ISSUE TITLE
Shuffle is broken on android, and skips songs of playlist

### ISSUE THREAD

**Issue by AbuD3vTs4113** [jmshrv/finamp#482]
Since the last release 0.6.15, the feature shuffle on playlist is broken. I listen some songs and some time after that the playlist was already done. So I can't listen to all my music. If anyone has had this problem before, can you confirm that you are having this bug as well?

Please can you fix it

**Comment by flloschy** [comment]
Shuffle is defaulted to only shuffle 250 songs in one session, can be changed in the settings under audio service.

Its the only thing I can imagine what you are referring to.

**Comment by AbuD3vTs4113** [comment]
But even with playlists of 25 songs playback skips songs, the shuffle don't read every songs of my playlist. I have to go back to the previous version to avoid this bug..

**Comment by AbuD3vTs4113** [comment]
But even with playlists of 25 songs playback skips songs, the shuffle don't read every songs of my playlist. I have to go back to the previous version to avoid this bug..

**Comment by flloschy** [comment]
Just tested with a 28 song playlist (on IOS) (app verison 0.6.15) and all 28 songs appeared in the queue

**Comment by AbuD3vTs4113** [comment]
of course the queue display all songs of playlist after shuffle but the player skips some songs

**Comment by jmshrv** [comment]
@AbuD3vTs4113 could you send logs? Make sure you replicate the bug first - logs are not saved from previous sessions

> Just tested with a 28 song playlist (on IOS) (app verison 0.6.15) and all 28 songs appeared in the queue with the default of 250 shuffled songs

That setting only applies to the "shuffle all" button on the songs tab

**Comment by flloschy** [comment]
Oh. My bad

**Comment by AbuD3vTs4113** [comment]
> @AbuD3vTs4113 could you send logs? Make sure you replicate the bug first - logs are not saved from previous sessions
> 
> > Just tested with a 28 song playlist (on IOS) (app verison 0.6.15) and all 28 songs appeared in the queue with the default of 250 shuffled songs
> 
> That setting only applies to the "shuffle all" button on the songs tab

Here the logs:

MusicPlayerBackgroundTask/INFO] 2023-08-12 14:51:56.432851: Starting audio service

null
[DownloadsHelper/INFO] 2023-08-12 14:52:16.858847: Song eWE.eU~XRjInSdM}M|j[R%D%RjRjR%R%RjbDR%Rjofxut7xuofRjn% exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:16.859556: Song eOD]Sa%1xa%2tR01E1M{WXNGs:ozozxaW=x[slWCf6jFRjkCa}WBjE exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:16.859913: Song exHn]6o$a$%Kxu~oo$jvt6xu%La$jsayWVj[WBaxWBRjoyt7ayWBj[ exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:18.338717: Song eWE.eU~XRjInSdM}M|j[R%D%RjRjR%R%RjbDR%Rjofxut7xuofRjn% exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:18.339330: Song eOD]Sa%1xa%2tR01E1M{WXNGs:ozozxaW=x[slWCf6jFRjkCa}WBjE exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:18.340753: Song exHn]6o$a$%Kxu~oo$jvt6xu%La$jsayWVj[WBaxWBRjoyt7ayWBj[ exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:20.193405: Song eWE.eU~XRjInSdM}M|j[R%D%RjRjR%R%RjbDR%Rjofxut7xuofRjn% exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:20.193915: Song eOD]Sa%1xa%2tR01E1M{WXNGs:ozozxaW=x[slWCf6jFRjkCa}WBjE exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:20.194372: Song exHn]6o$a$%Kxu~oo$jvt6xu%La$jsayWVj[WBaxWBRjoyt7ayWBj[ exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:20.901495: Song eWE.eU~XRjInSdM}M|j[R%D%RjRjR%R%RjbDR%Rjofxut7xuofRjn% exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:20.901742: Song eUGan#WB0c-qInbqInNFxuNFIUNFt8xus;n,ofj[V]t7t7bFNGRjt7 exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:20.901874: Song efLW-PM{~qxa.8-;oLxus:R*~W%MMxaeJ7W;oeV@WVWB_3R*RjofRP exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:20.901996: Song eF8X5-bb00Rj-;-;oLD*WB%29Zn%%MkCRjIAS2-pofM{M{ayxuofM| exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:20.902106: Song e66kL:%M0KE1-o^+t7E1Rjs:NdWVxZs:Ip%NkCM_RPa#^+t69ZM{%L exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:20.902211: Song eREvv,3B;hv~R*R5M{Sz$*xG-pXmWUV@R*n4NGw{xaoft7kVa{WBWU exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:20.902337: Song etQJJ^xu_N%gIB-qRjR*tQV[.7ayD%RjjatRkCt7aykCxufkRjoft7 exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:20.902435: Song eYJHaW~W=|?aV@RiMxRjoeWBM{M|adRjxaM|%3xaM|xtRjjZM{WBof exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:20.902605: Song eZO|X{-;RkxuIo^,t7Rjt7kC00RjRPRjoLtRV@kCbHn%SgV@WBbHae exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:20.902731: Song eZO|X{-;RkxuIo^,t7Rjt7kC00RjRPRjoLtRV@kCbHn%SgV@WBbHae exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:20.902870: Song eRBUg|sp1abv$ksAWBNaayn%9[kV-VnjWCI;a{xGWBR+TIe:w0ofOC exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:20.902985: Song eNC?r]~qayWBof~q-;IUD%WBt7t7oft7%MRjWBofxuxuIUt7ofWBxu exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:20.903137: Song eF9%VMxv0L9FM{-oM|IVx[t7IUIU%2.7Sho}s;smV@IU%2fPRjV[bb exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:21.508815: Song 12eb4ff42783bc91d252a3321263618b exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:21.513756: Song 9207f50556b9b6b600117dcbbaf19e84 exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:21.519540: Song 31566184144f7f950fb114da5ab2f898 exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:21.522479: Song abd48f1362529c483aac4307c3deda41 exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:21.527090: Song 50dae3c5dca943f6ae4bb8a3040aa1e1 exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:21.530050: Song 75cd61f4c40b5ae240cde8f6c159b9de exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:21.535061: Song c050fbc447f5e6867c80ae03df025758 exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:21.537029: Song b7df8ed447e31c6794e277fc5eb44687 exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:21.541548: Song 9401a5f0fdb279c865e2f43636f01ecb exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:21.543984: Song fcc3ea80032a4e4dd35955c62a8f336f exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:21.545209: Song c644187f247295421c25f1709eb14571 exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:21.547119: Song 17529c2c933f1dd0ed75c60ea6904202 exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:21.550035: Song 64b0071a2bba5fb08f39c4f4f6deb63e exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:21.551241: Song 425a2efb56071486984e17a275d7382f exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:21.552476: Song 3f33cdec59023364da802ad5b7e90748 exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:21.554590: Song 37878bc8116e754a527b4643964f4a0e exists offline, using local file

null
[DownloadsHelper/INFO] 2023-08-12 14:52:21.556088: Song bb8561b8a8a1697f233d5cef4340a20b exists offline, using local file

null

**Comment by Chaphasilor** [comment]
I'm guessing the problem is either some messed-up downloads (try going to the downloads page, I think recently a button was added that tries to repair downloads), or that playback of actually downloaded track simply isn't working...

**Comment by jmshrv** [comment]
I'll try to reproduce this in a bit, previous attempts at fixing shuffling resulted in half the queue being skipped on Android. This was tracked in #61

**Comment by AbuD3vTs4113** [comment]
Okay thank you. In the meantime, I will use the version 0.6.14.

**Comment by Chaphasilor** [comment]
Hi @AbuD3vTs4113, could you confirm that this issue is actually fixed in 0.6.18? I'm investigating a similar issue...
