### ISSUE TITLE
Skip to current playing Song in Queue

### ISSUE THREAD

**Issue by AhegaHOE** [jmshrv/finamp#483]
### Current behavior
At this point in time, when you open the queue while playing songs you have to scroll down to the song that's currently playing in order to see what comes up.

### Proposal
For the user it would be simpler and more enjoyable experience to see what's up next at one glance. My suggestion is to put the current playing song at the top of the popped up window so the user can scroll up to see what played in the past and see below what's up next.

### Example Screenshot
![Screenshot_20230810-063617](https://github.com/jmshrv/finamp/assets/73001005/29a7b62e-f07d-4d4a-9b64-94492ba60999)

**Comment by Chaphasilor** [comment]
This is planned as part of the redesign (#220). Current track will be at the top initially, and stay sticky at the top when scrolling down the queue (and sticky at the bottom when scrolling up to previous tracks).  
A beta for the new queue will land soon™
