### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [jmshrv/finamp#486]
https://gitlab.com/fdroid/fdroiddata/-/jobs/4859984062

```
Because finamp depends on flutter_localizations from sdk which depends on intl 0.17.0, intl 0.17.0 is required.
So, because finamp depends on intl ^0.18.0, version solving failed.
```

Could you please take a look? Thanks!

**Comment by jmshrv** [comment]
Looks like the Flutter wrapper wasn't updated for some reason. I'll push a new release to fix :)

**Comment by jmshrv** [comment]
Fixed in 0.6.17 :)

**Comment by linsui** [comment]
Thanks!

**Comment by linsui** [comment]
```
Note: intl is pinned to version 0.18.1 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.
Because finamp depends on flutter_localizations from sdk which depends on intl 0.18.1, intl 0.18.1 is required.
So, because finamp depends on intl ^0.19.0, version solving failed.
You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on intl: flutter pub add intl:^0.18.1
```

https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8317878707

@jmshrv Could you please update flutterw? Thanks!

**Comment by jmshrv** [comment]
Will do :) 

Does this mean that I'll have to make a new tag for F-Droid to pick it up?

**Comment by jmshrv** [comment]
Oh wait this isn't the first time this happened lol, will make an F-Droid only tag when I get around to it

**Comment by linsui** [comment]
Thanks!

**Comment by Chaphasilor** [comment]
Should be port this to the beta too?
