### ISSUE TITLE
END POST

### ISSUE THREAD

**Issue by scientificCommunity** [jmshrv/finamp#488]
Hi, I got `connection failed` after I tap the `NEXT` button, and the final log is 'END POST'.

**Comment by scientificCommunity** [comment]
the `jellyfin server` version is `10.8.10`

**Comment by Chaphasilor** [comment]
Can you reproduce the problem? What happens if you restart the app?

**Comment by scientificCommunity** [comment]
same after restart, and I just input Server Url, Username, and Password, then click the Next Button. 
I find My jellyfin Server did not output any log for Finemp's connection

**Comment by scientificCommunity** [comment]
> same after restart, and I just input Server Url, Username, and Password, then click the Next Button.
> I find My jellyfin Server did not output any log for Finemp's connection

same after restart, and I just input Server Url, Username, and Password, then click the Next Button.
I find My jellyfin Server did not output any log for Finemp's connection

**Comment by scientificCommunity** [comment]
Ios version is '16.1.1', network privilege has been authorized

**Comment by jmshrv** [comment]
Could you send your full logs? This sounds like you're imputing the wrong URL. You need to include the port, as Finamp will default to 80/443 instead of 8096.

**Comment by scientificCommunity** [comment]
> Could you send your full logs? This sounds like you're imputing the wrong URL. You need to include the port, as Finamp will default to 80/443 instead of 8096.

full log :

```
[MusicPlayerBackgroundTask/INFO] 2023-08-16 23:24:23.138870: Starting audio service

null
[Chopper/INFO] 2023-08-16 23:24:42.066735: 

null
[Chopper/INFO] 2023-08-16 23:24:42.066750: --> POST http://192.168.0.104:8096/Users/AuthenticateByName

null
[Chopper/INFO] 2023-08-16 23:24:42.066754: Content-Type: application/json; charset=utf-8

null
[Chopper/INFO] 2023-08-16 23:24:42.066758: X-Emby-Authorization: MediaBrowser Client="Finamp", Device="iPhone", DeviceId="", Version="0.6.16"

null
[Chopper/INFO] 2023-08-16 23:24:42.066764: content-length: 31

null
[Chopper/INFO] 2023-08-16 23:24:42.066766: 

null
LOGIN BODY
[Chopper/INFO] 2023-08-16 23:24:42.066771: --> END POST

null
[Chopper/INFO] 2023-08-16 23:24:52.245866: 

null
[Chopper/INFO] 2023-08-16 23:24:52.245895: --> POST http://192.168.0.104:8096/Users/AuthenticateByName

null
[Chopper/INFO] 2023-08-16 23:24:52.245904: Content-Type: application/json; charset=utf-8

null
[Chopper/INFO] 2023-08-16 23:24:52.245910: X-Emby-Authorization: MediaBrowser Client="Finamp", Device="iPhone", DeviceId="D5, Version="0.6.16"

null
[Chopper/INFO] 2023-08-16 23:24:52.245919: content-length: 31

null
[Chopper/INFO] 2023-08-16 23:24:52.245923: 

null
LOGIN BODY
[Chopper/INFO] 2023-08-16 23:24:52.245934: --> END POST

null
```
