### ISSUE TITLE
Albums, Artists, Playlists and Songs not showing

### ISSUE THREAD

**Issue by brandonssmith** [jmshrv/finamp#492]
I am on Jellyfin 0.6.16 on a google pixel fold (android 13). New phone, it worked fine on my old phone which was not on Android 13.

Albums, artists, playlists and songs are completely empty.  Genre is filled and songs that have been favorited are populated but other than that, nothing else shows.  I have attempted the usual logout, clear cache, clear data routine but it is still the same.

The IPs are correct in the logs.

**Comment by jmshrv** [comment]
That's weird. Could you send your logs?

**Comment by Chaphasilor** [comment]
I'm on Android 13 as well, but on a different build. Can try to install the latest version tomorrow to see if that's the culprit...

Are you sure you haven't accidentally enabled "favorites only" mode? This is the case if the heart icon at the top is filled.

**Comment by Chaphasilor** [comment]
I'll consider this issue fixed for now. If this is still a problem, feel free to re-open/comment...
