### ISSUE TITLE
Latest Release Has An Old Version Number

### ISSUE THREAD

**Issue by TheDarkula** [jmshrv/finamp#494]
As deduced [here](https://github.com/ImranR98/Obtainium/issues/874), the latest release of Finamp has the `0.6.16` tag.

**Comment by jmshrv** [comment]
That's weird, are you pulling the APK from GitHub Releases directly? 0.6.17 only edited F-Droid metadata, so 0.6.16 is practically the same.

**Comment by TheDarkula** [comment]
I have Obtainium pulling directly from GitHub.

**Comment by Chaphasilor** [comment]
According to the release commit, it's definitely not 0.6.16:

https://github.com/jmshrv/finamp/blob/4e9ede8a609cbcbd3a048c613b9d5302beeae250/pubspec.yaml#L18

Maybe Android can't parse the `+38` at the end and therefore falls back to the old version? The problem should resolve itself with the next release anyway...

**Comment by puff** [comment]
Maybe an old release was uploaded accidentally. Decompiling the apk with JADX shows 0.6.16 in the manifest.
![image](https://github.com/jmshrv/finamp/assets/33184334/0013cb0b-dd23-46af-b41b-cf1509613d54)

**Comment by Chaphasilor** [comment]
Could be, but in this case there actually is no difference between 0.6.16 and 0.6.17, since the release was just made to fix the version on F-Droid (which worked).

**Comment by jmshrv** [comment]
Fixed in 0.6.18, which I just pushed :)

**Comment by TheDarkula** [comment]
@jmshrv Thank you so much!
