### ISSUE TITLE
Wrong version uploaded

### ISSUE THREAD

**Issue by mcbelisle** [jmshrv/finamp#499]
Installed latest version but old version is installed on top of old version

**Comment by Chaphasilor** [comment]
Installed from where (Play Store, F-Droid, etc.)? And which version? :)

**Comment by mcbelisle** [comment]
Arm64.  617 is really  6.16

**Comment by Hudzenten10** [comment]
This is the same problem as issue #494. I also have this problem. I am using obtanium to pull the GitHub release, but even if I manually download the 0.6.17 version from GitHub via a web browser and install the apk, when going to settings-->info it shows 0.6.16. This is the arm64 version.

**Comment by jmshrv** [comment]
Closed as duplicate of #494
