### ISSUE TITLE
Manually created playlists not shown when using Jellyfin 10.8.11

### ISSUE THREAD

**Issue by WL-Amigo** [jmshrv/finamp#501]
First, thank you for creating awesome Jellyfin client app!

(I'm sorry for my broken English)

# Description

* Playlists manually created are not shown in Playlist tab.
  * Favorite filter is disabled (icon is outlined)

I confirmed this issue occured with jellyfin-server 10.8.11, and not occured with 10.8.10 .

# Versions

* Finamp: 0.6.16
* Jellyfin: 10.8.11
  * this issue not occured with 10.8.10

# Notes

From log of Finamp, this request sent to fetch playlists (some path and params are masked):

```
http://my-server.local:8096/Users/.../Items?IncludeItemTypes=Playlist&ParentId=...&Recursive=true&SortBy=DateCreated&SortOrder=Descending&Fields=parendId%2CindexNumber%2CsongCount%2CchildCount%2CproviderIds%2Cgenres%2Ctags%2Ctag%2CalbumPrimaryImageTag%2CparentPrimaryImageItemId&StartIntex=0&Limit=100
```

The response for request above didn't contain manually created playlists (only m3u playlists).

But, I tried the request without `ParentId` param:

```
http://my-server.local:8096/Users/.../Items?IncludeItemTypes=Playlist&Recursive=true&SortBy=DateCreated&SortOrder=Descending
```

The response for request above contained manually created playlists (same to results with server version 10.8.10).

I expect that this issue relates to this change in 10.8.11:

> Don't ignore parentId for playlists

https://github.com/jellyfin/jellyfin/releases/tag/v10.8.11

**Comment by Chaphasilor** [comment]
Thanks for letting us know, I'll take a look later...  
Should be a simple fix :)

**Comment by Chaphasilor** [comment]
I just noticed that the Jellyfin web client shows the same behavior. @WL-Amigo can you please confirm that your official Jellyfin web client also only shows scanned playlists and not manually created ones?

**Comment by Chaphasilor** [comment]
Filed a jellyfin issue here: https://github.com/jellyfin/jellyfin/issues/10272

I'd prefer if the underlying problem is fixed in Jellyfin instead of us working around this issue somehow. But given that it will probably be a while before the next hotfix, it might be necessary to include a temporary workaround in the next Finamp release...

**Comment by WL-Amigo** [comment]
I'm sorry for late reply.
Thank you for investigating more detailed cause and filing issue to Jellyfin main repository.

---

Sorry again for late confirmation.
I confirmed issue reproduction described in https://github.com/jellyfin/jellyfin/issues/10272 :

* The manually created playlist is not shown under Home > Music > Playlists, but does show up under Home > Playlists
  * with installation via apt(Debian bullseye arm64), jellyfin-server 10.8.11

So I pinned Jellyfin version to 10.8.10 and I will keep it until the fix is applied to Jellyfin.

```sh
# before do this, install Jellyfin 10.8.10 manually with packages from https://repo.jellyfin.org/releases/server/debian/versions/stable/
$ sudo apt-mark hold jellyfin jellyfin-server jellyfin-web
```

**Comment by AD-Wright** [comment]
If you're running docker then you can change from pulling jellyfin:latest to jellyfin:10.8.10 (that's the equivalent of the apt command).

**Comment by BloodyIron** [comment]
Playlists created on Jellyfin stopped showing up in Finamp with Jellyfin server 10.8.11, but switched to the 10.8.10 docker image and the issue was addressed immediately. This looks to be a reliably provable regression with 10.8.11.

**Comment by jmshrv** [comment]
Jellyfin 10.8.12 has been released, which fixes this bug :)

**Comment by BloodyIron** [comment]
Yay thanks! :D
