### ISSUE TITLE
Music does not respond to volume changes after playing 1-2 songs

### ISSUE THREAD

**Issue by NutchapolSal** [jmshrv/finamp#506]
## Bug description
After playing 1-2 songs, the music player doesn't respond to volume changes unless the app is in foreground or until user tells Finamp to skip to next/last song

2 songs on fresh open (or removing it from app history before opening), then only 1 song after bug has manifested

It will be in this state as long as user does not cause Finamp to jump to another song (⏩️ or double ⏪️)

Seeking, play/pause and "backward to start of song" (single ⏪️) does not take it out of this state

### Fresh app open
- Open Finamp
- Start playing songs
- Wait for current song to finish
- Wait for another song to finish

### Bug has already manifested
- Go into Finamp
- Skip to Next song
- Wait for current song to finish

### Bug results
- Go to iOS home screen or other apps
- Try to change volume (now it doesn't work)
- Go back into Finamp
- Try to change volume (now it works, the music volume updates to the current system volume)
- Repeat the previous 4 steps indefinitely (optional)

### notes
- waiting can be replaced with seeking to the end of songs
- Finamp not responding to volume is most obvious when setting the system volume to 0
- Finamp does not need to be in the foreground for the bug to happen
- Locking the screen with Finamp on screen does not count as being in background

## Device Information
- iOS 16.2 (20C65) on iPhone SE 2022
- Finamp 0.6.16

## Other thoughts
- some callback that needs to be re-registered when autoplaying next song?
- interesting how iOS does not do audio levels by itself and the apps have to handle it

**Comment by jmshrv** [comment]
That's so strange, volume should just be handled by the system. My only thought is your phone is OOMing and struggling to keep up, but I'd feel that you'd notice it. Are you playing heavy files (FLAC/other lossless)? If so, you could try reducing the buffer size in the Audio Service settings.

**Comment by NutchapolSal** [comment]
Nope, I'm using transcoding.

**Comment by NutchapolSal** [comment]
could not replicate using Finamp 0.6.16 on iPad Pro 11' 2020 with iPadOS 16.6.1 (20G81)

**Comment by jmshrv** [comment]
I've got an iPhone 6 lying around somewhere, I'll see if the same thing happens

**Comment by NutchapolSal** [comment]
The app store has updated Finamp to 0.6.18, and now it crashes on playback instead. which I also can't replicate on my iPad. I'm thinking it might be the same bug causing these symptoms.

I want to either try updating iOS or reinstalling Finamp next but that might irreversibly cause the bug to disappear, Are there any log files you are interested?

**Comment by jmshrv** [comment]
I doubt log files are helpful here, go ahead :)

**Comment by Chaphasilor** [comment]
@NutchapolSal over here on 0.6.19 xD  
You mean 0.6.18?

Either way, good thing this doesn't seem to be an issue with Finamp!

**Comment by NutchapolSal** [comment]
0.6.19 was quickly pushed to the app store to fix #509. not yet tagged in the repository though

**Comment by Chaphasilor** [comment]
Ahh I see, could you tag that one @jmshrv?
