### ISSUE TITLE
[Feature request] "Cassette Tape UI"

### ISSUE THREAD

**Issue by JPinSPACE** [jmshrv/finamp#507]
This is a silly feature request, but one that I can't get out of my head so I'm just going to make it and the community can judge if it's worth any effort. I don't know much about phone app development and figured it's worth asking in case it's a) trivial and b) other folks think it's worthwhile.

The new Sony Walkman devices have a feature called the "Cassette Tape UI" which shows an animated depiction of a cassette tape, labeled with the current song, playing while listening to music. This is completely superfluous, but neat and nostalgic. It would be pretty cool if Finamp had a similar screen.
<img width="247" alt="image" src="https://github.com/jmshrv/finamp/assets/6119290/59eeef21-ef05-4bc4-8601-3023b3bdad30">

**Comment by jmshrv** [comment]
It'd be a pretty fun thing to mess about with, although it isn't exactly a P0 🙃 

[Maybe one Flutter gets 3D support](https://github.com/flutter/flutter/wiki/Impeller-Scene) (the Sony example looks to be hand-drawn though, which may be easier)

**Comment by Chaphasilor** [comment]
Ahhrg, I'm not sure if I'd like this. Supporting different "skins" would make the code unreasonably more complicated I think. But maybe I'm wrong. It just seems like a bad idea to me 😅
