### ISSUE TITLE
Conditionally transcode when required on iOS

### ISSUE THREAD

**Issue by aquasync** [jmshrv/finamp#512]
Hi there,

Thanks for Finamp - have been a happy user for sometime on Android, but unfortunately have recently moved back to the dark side! I understand that opus playback isn't possible natively on iOS at present (thanks Apple), but can get it to play if I explicitly enable transcoding in the client.

What I was wondering is if there is a way to only use transcoding conditionally for codecs which are unsupported on the client? If I enable transcoding, then everything gets transcoded, even my MP3 albums etc that would've played just fine. I'm not sure how it works, but when using the Jellyfin iOS client to play an Opus album, it will automatically trigger server-side transcoding (to "256 Kbps TS AAC"), vs direct play for other supported codecs.

Also as an aside - not sure if this is expected, but even after enabling transcoding in the Finamp settings it still comes up server side as "Direct playing", despite saying "Streaming Transcode" on the client. Not sure why that is, as I take it it is being transcoded server side?

This is with latest Finamp, and with Jellyfin 10.8.10.

**Comment by aquasync** [comment]
Ah sorry, I see this is a dupe of #91. Would be particularly useful when #215 lands though.

Maybe you could have three options: Never transcode (current default/direct play), When required (ie for unsupported codecs), Always (useful if you want to compress from higher bitrate but otherwise supported streams?).

**Comment by Chaphasilor** [comment]
Hey @aquasync, thanks for the detailed writeup! Given that this is a duplicate, I'll go ahead and close this issue here, but it would be awesome if you could go ahead and copy your texts to the existing issue because I think there's a lot of value and great ideas in there! We can continue talk about those idea in #91 😁
