### ISSUE TITLE
New libraries do not appear in the hamburger menu until their visibility is unchecked then rechecked in settings

### ISSUE THREAD

**Issue by DouglasNewhouse** [jmshrv/finamp#527]
I created a new music library on my server. In Settings -> Select Music Libraries the library appears and it is checked, but it did not become available in the hamburger menu until I unchecked its box then rechecked it.

**Comment by Chaphasilor** [comment]
A quick look through the code reveals the following:

https://github.com/jmshrv/finamp/blob/4f49d697fc365a1bacc89e5bc4141721563ddd29/lib/screens/view_selector.dart#L66-L89

In short, the new library being checked is a visual bug, *any* music library is checked initially. But it only becomes active after submitting/saving the changes. And the save button only becomes available after making a change in the UI.  
Should be a relatively simple fix :)

**Comment by Chaphasilor** [comment]
I believe this should already be fixed in the beta...
