### ISSUE TITLE
Dsd support

### ISSUE THREAD

**Issue by starnakin** [jmshrv/finamp#528]
The application support dsd file ? And a bit perfect support like android audio player pro is consider ?
Thanks

**Comment by jmshrv** [comment]
Finamp doesn't support DSDs yet as it isn't supported by Android natively. If I ever get around to #177, it'll likely be fixed there.

As for bit perfect support (assuming integration with USB DACs and stuff), that'd be a massive amount of effort that I doubt I'll ever get around to. Android does a good job anyway imo - it'll output as high quality as it can to whatever it's playing to (although I personally luckily haven't fallen down the rabbithole enough to be able to differentiate between different DACs)

**Comment by starnakin** [comment]
> Finamp doesn't support DSDs yet as it isn't supported by Android natively. If I ever get around to #177, it'll likely be fixed there.
> 
> As for bit perfect support (assuming integration with USB DACs and stuff), that'd be a massive amount of effort that I doubt I'll ever get around to. Android does a good job anyway imo - it'll output as high quality as it can to whatever it's playing to (although I personally luckily haven't fallen down the rabbithole enough to be able to differentiate between different DACs)

Ok sad. Thanks for you reply
