### ISSUE TITLE
Playlist changes don't apply in offline mode

### ISSUE THREAD

**Issue by Chedski** [jmshrv/finamp#531]
When I update or create a playlist, the changes don't apply to offline mode unless I force-stop the app, clear its cache, and, in the case of newly created playlists, tap the "download" icon for the playlist.

Expected behavior: Playlist data is updated for offline mode when the Playlists tab is opened / reloaded

**Comment by Chedski** [comment]
Nevermind, clearing the cache doesn't seem to actually work - I have to delete all of the songs in the playlist and then re-download them, which is unacceptable

**Comment by Chedski** [comment]
Deleting and re-downloading (which only removes downloads that aren't downloaded by being part of anything else downloaded, like another album or playlist) works but the list of playlists is not refreshed when switching back to offline mode and will still report the old number of songs.

**Comment by Chaphasilor** [comment]
#460 is supposed to implement just that, but I'm not sure if it's already released as part of the latest version...

**Comment by Chaphasilor** [comment]
The new new download system (#568) will also definitely support that, but again with a manual refresh needed. At some point we could try to scan for changes, and show a notification if there are any. Not sure if fully automatic synchronization will ever be a thing though...

**Comment by Chaphasilor** [comment]
@Chedski coming back to this, are you expecting new playlists to be downloaded automatically? Or what data exactly are you expecting to be available in offline mode? 🤔

**Comment by Chedski** [comment]
@Chaphasilor The actual list of songs in the playlist (ie. when a song is added or removed).

**Comment by Chaphasilor** [comment]
Okay, yeah this should be handled by the new downloads system, as long as you have already downloaded that playlists. Playlists that you haven't downloaded yet are not available in offline mode, including newly created playlists...

**Comment by Chaphasilor** [comment]
@Chedski the download system has been improved as part of the redesign beta. You can check it out here: https://github.com/jmshrv/finamp/releases/tag/0.9.2-beta

Right now the app will automatically synchronize downloaded playlists on startup, and there's an option in the download settings that lets you download all playlists (this should also include newly created playlists).  
Modifying a playlist or adding a new one doesn't immediately re-sync the playlists yet, but I'll try to add that with the next beta update!

**Comment by Chaphasilor** [comment]
So it seems like @Komodo5197 actually already implemented automatic syncs when adding a song to a playlist, just removing from a playlist as well as creating/deleting a playlist is missing :)

**Comment by Chaphasilor** [comment]
Okay, I've implemented this now and it will be part of the next **beta** update. Deleting playlists isn't currently supported by Finamp, but when removing a song from a playlist or creating a new playlist, everything will be properly synced for offline mode now.

**Comment by Chaphasilor** [comment]
@Chedski can you try with the latest beta update (0.9.5) please?
