### ISSUE TITLE
Feature Request: Reorder Playlist

### ISSUE THREAD

**Issue by MrCamel999** [jmshrv/finamp#532]
Apologies if this already exists somewhere, I cannot figure out how to do this though if that's the case.

I would like the ability to reorder the order of a playlist. For instance, if I'm making a playlist of 3 songs and accidentally add them in the order of Song 2, 1, 3, I want to be able to reorder the playlist so it's in the order 1, 2, 3, or even 3, 2, 1 if I wanted, whatever order.

**Comment by jmshrv** [comment]
Duplicate of #100
