### ISSUE TITLE
Playlists tab is not refreshed when switching to offline mode

### ISSUE THREAD

**Issue by Chedski** [jmshrv/finamp#533]
The list of playlists doesn't refresh when switching to offline mode, even if the playlists have changed

**Comment by Chaphasilor** [comment]
What exactly isn't refreshing? The actual listing of playlists, or some info about the playlists like the song count?

**Comment by Chedski** [comment]
If I add or remove a playlist from another device, or even in online mode in the finamp app, that change will not be reflected in offline mode. The song number on the list is not updated at all, and the contents of the playlists aren't updated unless I delete and re-download the playlist.

**Comment by Chaphasilor** [comment]
Ahh so you mean if you modify which songs are inside a playlist.  
Yeah that does happen automatically yet, but you can try going to the "Downloads" page (via the sidebar) and pressing the "Refresh" button there.  
There's also #534 that will add a refresh/sync button within each playlist and improve the reliability of the feature.

But there is also an issue with refreshing the list of playlists/albums/etc. if they are updated/downloaded, which will hopefully be addressed soon!

**Comment by Chaphasilor** [comment]
@Chedski this should be working nicely in the beta version now. Any changes you make to playlists in Finamp should be synced to the downloads right away (might take a minute or so to actually download), and any changes made outside of Finamp should be picked up when the app is started :)
