### ISSUE TITLE
PathAccessException During iOS Restart

### ISSUE THREAD

**Issue by michaelcresswell** [jmshrv/finamp#535]
A PathAccessException is seen intermittently.

![image](https://github.com/jmshrv/finamp/assets/3800846/b28d9cce-95b9-412e-9c58-b3de6f214079)

The sequence leading to this is:
1) Listen to music in offline mode
2) Shut off phone (without closing Finamp)
3) Leave phone off for a while
4) Start phone
5) Go to Finamp
6) See error message

However, I have not been able to reproduce consistently.

Restarting Finamp is enough to get things working again when it does happen.

This screenshot is from Finamp 0.6.19 but the exception has been seen with prior versions as well.

**Comment by Chaphasilor** [comment]
What OS are you using? 🤔

**Comment by michaelcresswell** [comment]
Latest iOS (17.1.1)

**Comment by jmshrv** [comment]
That's... concerning. I haven't seen that myself, but the app should be able to access its own directory.

Storage on Flutter is a nightmare since it doesn't support modern URL-based directory access (ironically pushed by Google in Android).

**Comment by michaelcresswell** [comment]
Turning iOS off and back on again within a minute or two doesn’t reproduce the problem but turning it off for a few hours does.

Not sure what’s going on.

Maybe those container paths change eventually? I’m not familiar with how iOS works under the hood (or Finamp) so just speculation.

**Comment by jmshrv** [comment]
Those paths do change when an app updates, it wouldn't surprise me if something similar happens when the app restarts. This is unrelated, but Finamp used to store absolute paths for downloads and it was a nightmare.

Opening Hive databases should get the correct path every time, I'm leaning towards this being a bug in Flutter or something.

**Comment by Chaphasilor** [comment]
Seems like the base path changes with every app restart, but no idea why it throws a fit when the OS restarts...

**Comment by Chaphasilor** [comment]
@michaelcresswell is this still happening to you? If so, could you try the beta version through Testflight instead?

**Comment by michaelcresswell** [comment]
I still saw this intermittently prior to the updating to the TestFlight beta (I think I was on 0.6.22).

I updated to the 0.9.6 beta and haven't seen it in the first few days of use. I couldn't reproduce it _consistently_ so hard to say for sure.

**Comment by Chaphasilor** [comment]
Alright, I'll close this for now, but if it pops up again on the beta, feel free to re-open or let me know!

**Comment by michaelcresswell** [comment]
Saw this again with the beta so I guess it’s not fixed after all.

Different hive but otherwise identical error message and scenario where it happened. 

iOS 17.6.1, Finamp 0.9.9

![image](https://github.com/user-attachments/assets/575bacee-94ef-4d81-b188-dce16ca1bbcc)
