### ISSUE TITLE
Audio is not playing through bluetooth devices, only through speakers

### ISSUE THREAD

**Issue by deepio** [jmshrv/finamp#537]
Speakers physically attached to the phone work (including the headphone jack and built-in speakers.) Connecting to any bluetooth device plays the music through the phones speakers and not through the bluetooth device. Bluetooth devices tried include cars, earphones, and speakers. None of the devices manage to play on bluetooth but other apps don't appear to have problems. It's possible to play two different songs in two different apps at the same time as one will play on bluetooth and finamp will play on the speaker.

Samsung Galaxy Note 9
Android Version `10`
Kernel version 4.9.118

**Comment by Chaphasilor** [comment]
I take it that other music apps are working fine?  
If it doesn't work at all, it might be a problem with https://github.com/ryanheise/just_audio

**Comment by deepio** [comment]
> I take it that other music apps are working fine? If it doesn't work at all, it might be a problem with https://github.com/ryanheise/just_audio

Yes they do, for example musicolet works fine but I'm not trying to advertise other apps here. Both apps **can** run at the same time such that I can hear two different songs simultaneously on the phone. The audio will be routed to two different outputs (musicolet will play in the bluetooth device, and finamp will play from the builtin speakers.) Usually when you ask another app to play some audio while another is playing the first one stops but this is not the case here.

**Comment by Chaphasilor** [comment]
That is so strange! Do you have another device to test with?  
I wouldn't be surprised if this would be happening due to some Samsung audio output management, they tend to have some more advanced features in that regard.

For me Finamp is always pausing when another app starts playing and bluetooth also works fine.  
I can try to repro this on an S20(?) tonight...

**Comment by deepio** [comment]
It's my only android device. Jellyfin app works fine with bluetooth. And I can do the same dual audio trick with jellyfin as long as bluetooth is enabled.

**Comment by deepio** [comment]
PEBCAK

**Comment by Chaphasilor** [comment]
So what was the issue? ^^
