### ISSUE TITLE
main: Song download indicators don't appear until album view is reopened

### ISSUE THREAD

**Issue by rom4nik** [jmshrv/finamp#540]
On current `main` branch:

https://github.com/jmshrv/finamp/assets/46846000/523f7071-d33c-468e-b517-72ac47786734

At least the indicators still disappear when songs are deleted.

It used to work _some_ time ago :sweat_smile:, I'll try to bisect this later. So far I see that this issue isn't present on current `redesign` branch (89fec629833c8daf49c0362c821bd9c42276ac54).

**Comment by rom4nik** [comment]
Weird, I can't reproduce this anymore on main branch (3ea467767846d3b473a4663b928b4c6168bbb46f now, not sure what commit was there at the time of reporting this issue) and on 0.6.18 (haven't checked that .apk at time of reporting). :eyes:

At least I've verified multiple times that this was working on 0.6.8 and broken on 0.6.9 release builds, even after clean install.

**Comment by Chaphasilor** [comment]
Yeah it's pretty wonky 🙃
