### ISSUE TITLE
Feature Request/Issue: Persistent cache storage across app closures

### ISSUE THREAD

**Issue by TheWicklowWolf** [jmshrv/finamp#544]
I'm using an extended cache as per https://github.com/jmshrv/finamp/issues/239, and that works great!

However, I've observed that when I close the app on Android using "Close all," the cache gets cleared. 
While I understand this might be considered a feature request rather than an issue, I'm wondering if there's a way to retain the cache contents.
This would enable users to seamlessly resume their previous session even after closing all apps and reopening the app.

**Comment by Chaphasilor** [comment]
Given that currently not even the last playing song is remembered across restarts, this really isn't possible to do at the moment.  

To be honest, as long as we're using `just_audio` for music playback this seems like a distant dream, because the caching is probably buried deep within platform-specific code.  
The best idea is probably to use a completely different audio backend, but currently no-one has the time to implement that :(

**Comment by Chaphasilor** [comment]
> Out of interest, how is it done in other apps?
> Is the current session stored and then reloaded at start up?

I don't think other apps actually store the cache normally. If there is a connection, the cache can be re-loaded, and if there isn't a connection the cache won't be of much use anyway.

But I think what you're looking for is currently being implemented in #547. It saves the current queue along with the timestamp in the current songs, and when you close and restart the app it will re-load the songs from the server and let you resume from where you last listened!

**Comment by TheWicklowWolf** [comment]
> But I think what you're looking for is currently being implemented in #547. It saves the current queue along with the timestamp in the current songs, and when you close and restart the app it will re-load the songs from the server and let you resume from where you last listened!

Yes that is pretty much what I was looking for, although I was hoping that you would be able to resume where you left off regardless of the connection status. 

Scenario would be something like this-> You are connected and are playing something (and the buffer has say 10 songs), you close the app/close all. Later you open it with no connection, ideally it would just continue where you stopped and try to pick up a connection as it goes. But that is close enough,and I really appreciate the effort!

Looking forward to the new release 👀

**Comment by Chaphasilor** [comment]
In theory, if you have the songs downloaded it should be able to restore the queue even without a connection, but I'm not sure how well that works currently.

> Looking forward to the new release 👀

It will be part of the beta/redesign early next year :)
