### ISSUE TITLE
[android] Playlist shuffle always starts on first song 

### ISSUE THREAD

**Issue by MattBlackOnly** [jmshrv/finamp#545]
The shuffle function consistently starts with the initial track in the playlist.

Duplicate of:
Closed Issue -> https://github.com/jmshrv/finamp/issues/457
Closed issue -> https://github.com/jmshrv/finamp/issues/61 
Closed PR -> https://github.com/jmshrv/finamp/pull/442

By the way, excellent app!

**Comment by Chaphasilor** [comment]
Oh come on :|

The upcoming redesign beta should really fix the issue, but who knows 🙃

**Comment by MattBlackOnly** [comment]
OK, thanks

**Comment by Chaphasilor** [comment]
I've merged a PR that might fix this, it will be part of the next release!
