### ISSUE TITLE
Is there a way to stop it playing after it disconnects from Bluetooth

### ISSUE THREAD

**Issue by BlueCoffee34** [jmshrv/finamp#571]
As above like jellyfish does. It will auto stop when basicly I turn the car off and the cars Bluetooth stops.

Sorry new to github and didn't know where to ask. Thanks

**Comment by Chaphasilor** [comment]
Are you on Android or iOS, and what version? Usually the system (e.g. Android) should stop music when Bluetooth disconnects, and that's always been working fine for me...

**Comment by BlueCoffee34** [comment]
Apologies after I rebooted my android phone it works as intended. No idea why it didn't auto stop before.
