### ISSUE TITLE
[question] access to files (on IOS)

### ISSUE THREAD

**Issue by flloschy** [jmshrv/finamp#576]
Hi!
to begin, sorry to bother with something somewhat unimportant.

My question is if there is a way to access the music files you download from the app.
I ""need"" to do this because I reset my server and while setting up my hard drive I cleared it but forgot to backup my music. I don't have any backup for that matter (totally my fault by the way), except finamp on my phone

(Sadly and Unfortunately) I'm using IOS so file access is... a thing...

I figured I might ask because Infuse - which im using for videos - does store the files so that one can access it

**Comment by flloschy** [comment]
Thanks for the reply

I did try the backup method, and I am able to access `Finamp > Library > Application Support > download_tasks.sql, libCachedImageData.db` but nothing else. I also looked around the Files and there is nothing connected to finamp.

But I did find the option to add a custom download location inside the finamp settings (settings > Download location > `+`), sadly this is also not that helpful since the app crashes as soon as I select a folder without throwing any error into the logs :/
I'm not sure if this is a bug or some issue with permissions, i mean both are bugs but you know what i mean :p

I'm starting to believe this is not really possible without a native feature by finamp thanks to the locked and limited nature of iOS

**Comment by Chaphasilor** [comment]
And there's no folder called `Finamp > Library > Documents`? I would assume that's where the songs should be.

Adding a new library after you downloaded the songs won't help, as downloaded songs aren't moved or anything.

Does playback in offline mode still work?

**Comment by flloschy** [comment]
There is a Documents folder but its empty, when i open it iMazing just shows a popup saying that since iOS 8.2 apps need to explicitly allow access to this folder (or something Like that, i dont fully remember)

As of playing offline, yeah it still works fine

**Comment by Chaphasilor** [comment]
Okay, maybe I can get the updated config included in the next release. I'll check later :)

**Comment by flloschy** [comment]
That would be great! <3

**Comment by Chaphasilor** [comment]
So I made the necessary modifications in https://github.com/jmshrv/finamp/commit/b4a18056916925610701fcf406332ab4aef5f46c, hopefully that's enough. You'll just have to update to the next release, whenever that hits (next few days/weeks) :)

**Comment by flloschy** [comment]
Thank you soooooo much! You can’t believe how much time you saved me :D 
Really appreciate your work

I'll come back and tell ya if it worked, which is also why im unsure if this issue counts as closed (for now) so I'll leave the decision to you

Cant thank you enough

**Comment by Chaphasilor** [comment]
You can thank me and close the issue if it actually works xD

Fingers crossed!

**Comment by kuflierl** [comment]
Would also love this feature. Good luck on recovering your music

**Comment by Chaphasilor** [comment]
@flloschy just wanted to let you know that even though the redesign beta might be released before the next stable release, you should probably not upgrade to that one before you recovered your media. Wait for the stable release (should arrive soon after), recover your files (if possible), and then you can try out the beta (which *should* migrate your existing downloads to the new download system, but no guarantees) :)

**Comment by flloschy** [comment]
Im not 100% sure what you are saying
As far as im understanding this the next update should be skipped because its a beta and only upgrade when the stable is out. Is this right? Just wanna make sure

btw. thanks for the info :D

**Comment by Chaphasilor** [comment]
The beta will be released soon, which means you can choose between continuing to use the current version (stable), or the beta version (redesign, more features, faster updates). The beta will be available via Testflight, but I'm not sure if it's possible to upgrade to the beta on iOS while keeping the app data.  
So I'm saying that you should not use the version from Testflight (once that becomes available, there will be a release announcement here), but instead wait for the next regular update in the App Store ^^

**Comment by flloschy** [comment]
Alright, will do
Thank you very much for clarifying

**Comment by Chaphasilor** [comment]
@flloschy the update has finally been released: https://github.com/jmshrv/finamp/releases/tag/0.6.20  
It'll probably take a day(?) to get reviewed before it hits the App Store :)  
Please report back if this solved your issue! Best of luck <3

**Comment by Chaphasilor** [comment]
Oh sorry I never responded xD  
Glad that everything worked out for you! <3
