### ISSUE TITLE
Issue with self-signed certificate

### ISSUE THREAD

**Issue by anoo2niem** [jmshrv/finamp#584]
Hi,

I have a jellyfin server under the domain https://jellyfin.home, available locally and via tailscale.
It is a self-signed certificate which is trusted globally on my android device. I can acces the domain without any certificate issues on any browser, the jellyfin app, fintunes, symfonium, ...

However, with finamp (my prefered app) to stream music from my server, i've get this error;

HandshakeException: Handshake error
in client (OS Error:
CERTIFICATE_VERIFY_FAILED: unable
to get local issuer
certificate(handshake.cc:393)

Finamp version 0.6.18

Edit:

Device: Samsung note 20 ultra
Android 13 oneui 5.1

**Comment by Chaphasilor** [comment]
Take a look at #106

There is a work-in-progress branch that adds support for this, but it's not finished yet.

**Comment by anoo2niem** [comment]
I will close this issue as there is indeed an open thread #106.
