### ISSUE TITLE
Finamp loads album cover before track

### ISSUE THREAD

**Issue by catfrightening** [jmshrv/finamp#585]
So over using finamp for about a year I've noticed it loads the album cover at full quality before the song, therefore adding to the amount of time it takes to load the track. I'm not sure if there's some other reason for this but i'd be nice to have the track get priority over the album cover.

**Comment by jmshrv** [comment]
There isn't really an easy way to handle this - album covers are loaded in two places:

1. In the UI, by Flutter
2. In the player (for notifications), by the native platform

I can't really control how each one loads, or in what order.
