### ISSUE TITLE
[Feature Request] Playback reporting for downloaded tracks in online mode

### ISSUE THREAD

**Issue by pbogre** [jmshrv/finamp#587]
Enable playback reporting (scrobbling) to the Jellyfin server for downloaded tracks when in online mode. Currently, when I download a track and then play it even in online mode, it appears that Finamp is not reporting this play to the Jellyfin server, which messes up my scrobbling :)

Thank you for this amazing project.

**Comment by Chaphasilor** [comment]
Oh, I didn't even know that was an issue! In any case, it works as expected in the redesign beta, which should be dropping in the coming weeks :)

**Comment by Chaphasilor** [comment]
@pbogre playback reporting has been improved as part of the redesign beta, and this issue has been fixed. You can check it out here: https://github.com/jmshrv/finamp/releases/tag/0.9.2-beta

I'll close this issue for now since it should be resolved.
