### ISSUE TITLE
[Redesign - Bug] Downloaded album/playlist tracks in wrong order

### ISSUE THREAD

**Issue by lymnyx** [jmshrv/finamp#593]
Not sure if opening an issue at this time for this problem is appropriate, but after recently building the redesign branch as an apk myself, I found that when downloading playlists or albums and then (or at a later point) entering offline mode, the downloaded tracks aren't in the correct order.

Instead they seem to be ordered based on which tracks first finished downloading (previously), which is especially non-ideal when downloading an audiobook ;).

Please let me know if you need any additional information.

Also: Thank you for your work, the redesign is great so far!

**Comment by Chaphasilor** [comment]
Hey, thanks for the report! As for your first question, we'll move discussion to a Discord server once the redesign beta is actually released, with a backup discussion or issue here on GitHub for anyone who doesn't feel like using Discord.

Would you mind trying out the new downloading system and see if that issue still occurs? You can download a relatively recent build from [this link](https://gofile.io/d/dcsOfb) or build it yourself (PR #568).  
I'm pretty sure it's not an issue there anymore, and if it still is we'd really like to fix it! :D

**Comment by lymnyx** [comment]
Yep, just built it myself from source and everything works well, the problem is fixed there.

Thank you!
