### ISSUE TITLE
Landscape Doesn’t Fit on iPhone13 Mini

### ISSUE THREAD

**Issue by JRGonz** [jmshrv/finamp#595]
This is a bit cosmetic but I noticed when in landscape the player does not properly fit the screen of an iPhone 13 Mini. The buttons for the player hang off the bottom of the screen. 

![IMG_1971](https://github.com/jmshrv/finamp/assets/28549491/c7a9d75f-8c8a-43fd-966a-82d270d8a153)

**Comment by Chaphasilor** [comment]
Hi, I'll try to fix this with the redesign by using a 2-column layout in landscape mode like most other music players :)

**Comment by Chaphasilor** [comment]
Hi, would you mind explaining the two screenshots? The first one is while unfolded in landscape mode, and the second one is half-folded? 🤔

A two-column layout is definitely planned, but maybe we can improve the regular scaling further!

**Comment by Merconix** [comment]
Hey, of course! I'll throw in terrible photos taken from another phone, might make it clearer... sorry for the image spam.
The first one is unfolded, and rotated landscape just like a normal phone - but it's aspect ratio means it's very tall in portrait and wide in landscape.
![20240227_230514](https://github.com/jmshrv/finamp/assets/41351832/cb0735fd-9931-4688-9f76-b7c0d57e2e53)
The second is the small external display, which is very squared
![20240227_230540](https://github.com/jmshrv/finamp/assets/41351832/20cc611a-4583-483f-a86a-e071bbf3f121)

Unfortunately contributing is out of my remit at the moment, but I'd be happy to test anything you need.

**Comment by Chaphasilor** [comment]
@Merconix I'd guess you already tired this out? Is this better in 0.9.4/0.9.5?

**Comment by Merconix** [comment]
> @Merconix I'd guess you already tired this out? Is this better in 0.9.4/0.9.5?

Significant improvement! All fits on the little screen as you would hope:

![Screenshot_20240405_115337_CoverScreen](https://github.com/jmshrv/finamp/assets/41351832/ed6d3aed-acbb-4a67-8bc9-8c4ec8dafa20)

**Comment by JRGonz** [comment]
Is there a way to testflight it for iOS?

**Comment by Chaphasilor** [comment]
@JRGonz of course! You can find the link in the release notes of each beta release, in the expandable section.

Here it is: https://testflight.apple.com/join/UqHTQTSs

**Comment by JRGonz** [comment]
> @JRGonz of course! You can find the link in the release notes of each beta release, in the expandable section.
> 
> Here it is: https://testflight.apple.com/join/UqHTQTSs

When trying to do this i am getting a message saying "This site can't be reached" adn it is saying that it is an unsupported URL.

**Comment by JRGonz** [comment]
Got it. It looks great now! Thank you so much.
