### ISSUE TITLE
Can't login to Jellyfin Server 10.9.0

### ISSUE THREAD

**Issue by MSchaefer83** [jmshrv/finamp#596]
I get the error message:

Error
type 'Null' is not a subtype of type 'bool' in type cast.

I tried it with different devices. 
Even a new installation of Jellyfin does not help. I am using the docker image of Jellyfin.

Here the log:
{"User":{"Name":"User","ServerId":"0f9a78294c564a97922cd5f24908cef5","Id":"4b0cb26d09e5422db3240775877bf765","HasPassword":true,"HasConfiguredPassword":true,"HasConfiguredEasyPassword":false,"EnableAutoLogin":false,"LastLoginDate":"2024-02-13T13:29:23.7421902Z","LastActivityDate":"2024-02-13T13:29:23.7421902Z","Configuration":{"PlayDefaultAudioTrack":true,"SubtitleLanguagePreference":"","DisplayMissingEpisodes":false,"GroupedFolders":[],"SubtitleMode":"Default","DisplayCollectionsView":false,"EnableLocalPassword":false,"OrderedViews":[],"LatestItemsExcludes":[],"MyMediaExcludes":[],"HidePlayedInLatest":true,"RememberAudioSelections":true,"RememberSubtitleSelections":true,"EnableNextEpisodeAutoPlay":true,"CastReceiverId":"F007D354"},"Policy":{"IsAdministrator":false,"IsHidden":true,"EnableCollectionManagement":false,"EnableSubtitleManagement":false,"IsDisabled":false,"BlockedTags":[],"AllowedTags":[],"EnableUserPreferenceAccess":true,"AccessSchedules":[],"BlockUnratedItems":[],"EnableRemoteControlOfOtherUsers":false,"EnableSharedDeviceControl":true,"EnableRemoteAccess":true,"EnableLiveTvManagement":true,"EnableLiveTvAccess":true,"EnableMediaPlayback":true,"EnableAudioPlaybackTranscoding":true,"EnableVideoPlaybackTranscoding":true,"EnablePlaybackRemuxing":true,"ForceRemoteSourceTranscoding":false,"EnableContentDeletion":false,"EnableContentDeletionFromFolders":[],"EnableContentDownloading":true,"EnableSyncTranscoding":true,"EnableMediaConversion":true,"EnabledDevices":[],"EnableAllDevices":true,"EnabledChannels":[],"EnableAllChannels":false,"EnabledFolders":[],"EnableAllFolders":true,"InvalidLoginAttemptCount":0,"LoginAttemptsBeforeLockout":-1,"MaxActiveSessions":0,"EnablePublicSharing":true,"BlockedMediaFolders":[],"BlockedChannels":[],"RemoteClientBitrateLimit":0,"AuthenticationProviderId":"Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider","PasswordResetProviderId":"Jellyfin.Server.Implementations.Users.DefaultPasswordResetProvider","SyncPlayAccess":"CreateAndJoinGroups"}},"SessionInfo":{"PlayState":{"CanSeek":false,"IsPaused":false,"IsMuted":false,"RepeatMode":"RepeatNone"},"AdditionalUsers":[],"Capabilities":{"PlayableMediaTypes":[],"SupportedCommands":[],"SupportsMediaControl":false,"SupportsPersistentIdentifier":true},"RemoteEndPoint":"192.168.223.204","PlayableMediaTypes":[],"Id":"cd1e138ab70d3175229a7cec9314fd61","UserId":"4b0cb26d09e5422db3240775877bf765","UserName":"martin","Client":"Finamp","LastActivityDate":"2024-02-13T13:29:23.9331168Z","LastPlaybackCheckIn":"0001-01-01T00:00:00.0000000Z","DeviceName":"Nokia 5.3","DeviceId":"95fc7a4772e03543","ApplicationVersion":"0.6.18","IsActive":true,"SupportsMediaControl":false,"SupportsRemoteControl":false,"NowPlayingQueue":[],"NowPlayingQueueFullItems":[],"HasCustomDeviceName":false,"ServerId":"0f9a78294c564a97922cd5f24908cef5","SupportedCommands":[]},"AccessToken":"9393bec4188144a49b9608bf36441933","ServerId":"0f9a78294c564a97922cd5f24908cef5"}
<-- END HTTP

**Comment by MSchaefer83** [comment]
Super :-) Thank you.

**Comment by Chaphasilor** [comment]
@MSchaefer83 the beta versions are now available via Google Play and TestFlight, you should be able to log into your 10.9 server with them 😁

**Comment by Chaphasilor** [comment]
We should probably backport this fix to the stable version though 👀

**Comment by MSchaefer83** [comment]
Great job! It works and looks really good. Thank you very much. Can I support this project? There is no sponsor information for this project.

**Comment by Chaphasilor** [comment]
> Great job! It works and looks really good. Thank you very much. Can I support this project? There is no sponsor information for this project. 

Thanks for the feedback <3

@jmshrv recently sunsetted his sponsor profile and pointed his sponsors over to my profile instead, so I guess that's the closest you can get to sponsoring the project. I'm not planning to stop working on Finamp any time soon, since I'm constantly listening to music myself ^^

**Comment by Chaphasilor** [comment]
The stable channel will also be able to log into 10.9 servers with the next release :)

**Comment by Chaphasilor** [comment]
@MSchaefer83 thank you so much <3  
Was there any recent change that prompted this? :)

**Comment by MSchaefer83** [comment]
@Chaphasilor Hey, sure - I got my salary.
I told you I wanted to support you. I just forgot at first. 
You're doing a good job.

**Comment by Chaphasilor** [comment]
Much appreciated!

I just wish I had more time and skill to fix some of the bigger issues, but we'll get there eventually!
