### ISSUE TITLE
Persist custom header across all requests

### ISSUE THREAD

**Issue by mkozjak** [jmshrv/finamp#599]
Hi!

Would it be possible for Finamp to persist a specific header I could use for my reverse proxy auth procedure in order to let Finamp through?

I use a strong authentication system that fronts all my services and this way I cannot use Finamp when I want to access it via my proxy.

For example, I'd like for the app to be able to access jellyfin through https://home.example.com/jellyfin (proxy) that'd check whether the app is sending a specific (unique?) header and let it go through to the backend (jellyfin) if it is.

Currently I can't see an http header that the app is sending across all requests.

**Comment by Chaphasilor** [comment]
Hi! So you just need a way to set a number of custom key-value pairs to use as headers somehow?

**Comment by mkozjak** [comment]
> Hi! So you just need a way to set a number of custom key-value pairs to use as headers somehow?

Yes, and they'd need to be available in all requests towards the backend. Either that or it needs to respect persisting headers if the proxy demands it.

**Comment by mkozjak** [comment]
@Chaphasilor and obviously I can test this feature on TestFlight! Just send me an invite.

**Comment by Chaphasilor** [comment]
How are you using other Jellyfin clients. Afaik none of them support custom headers, so maybe you should overthink your setup?

It's doable to implement, but I feel like it's not really worth it to support this use case 🤔

**Comment by mkozjak** [comment]
The only JellyFin clients that work are web-based, since they are able to redirect me to my 3rd party auth service (I'm using vouch-proxy with nginx). No 'native' apps are able to do that, but I see on other repositories it's a requested feature.

+1 on rethinking my setup, basically removing jellyfin for music altogether.

The implementation of this feature is so complex that it's not worth it to have at all? I think I'm not the only one guarding jellyfin behind a reverse proxy.

**Comment by Chaphasilor** [comment]
I was talking about using the reverse proxy for security, not ditching Jellyfin for music, but you do you ^^  
The feature isn't hard to implement, I'm just not sure if there would be any other users beside you.  
I can try to send you a custom build in a few days that adds support for it :)

**Comment by mkozjak** [comment]
I know the main idea was the reverse proxy, but I currently don't see a way to make this work aside something like an http header.

Lemme rethink my strategy a bit and if I still feel like the app should have this, I will return back here. Thanks!

**Comment by mkozjak** [comment]
Actually, I guess it makes sense that there's so few of us requesting this type of a feature on mobile clients. I have decided to move away from reverse proxying to vpn. Vpn is less user-friendly, but what can you do.

**Comment by Chaphasilor** [comment]
@mkozjak I noticed that Symfonium seems to support custom headers, so maybe that's an option for you? It's a paid and closed-source app, but it does have a ton of features :)

**Comment by mkozjak** [comment]
@Chaphasilor thanks, I did hear about that one before. No need, since I switched to VPN. Everything works with this app.

**Comment by aldenparker** [comment]
I know this is a closed issue, but I think it is worth looking at again with the rise of pangolin. Not super hard to set up and is a nice feature to have it you are using that setup
