### ISSUE TITLE
[Feature Resquest] Remember song and play position on open/close

### ISSUE THREAD

**Issue by natedawg** [jmshrv/finamp#60]
Finamp should remember the last playing song and play position when opening. This can allow bluetooth devices to continue playing when a device connects.

**Comment by UnicornsOnLSD** [comment]
That sounds like it'll be pretty easy to add, I'll look into it :)

**Comment by internetfreak** [comment]
Seconding this, the app is really great for now but that's the only thing I currently miss for using it (haven't used it too much, but I'm trying to increase usage). Especially if you listen to longer mixes it's easy to lose progress in the current version.
Thanks for your work

**Comment by internetfreak** [comment]
Don't mean to pressure on this, but how big is the chance to have this in the future? As it got stated in another issue that the next release is almost done I don't think this could still be implemented quickly, so maybe for the release after the next one? Getting a new phone soon and I plan to rely only on Finamp for my music, so this is the only "blocker" for me (still using Finamp, it's only inconvenient to try to remember where you were when iOS kills the audio session)

**Comment by djohnson1865** [comment]
Just here to give another endorsement to this. I'm already using Finamp as my primary/only music playback solution on Android. Losing playback position/song is my only problem with the app at this point.

**Comment by UnicornsOnLSD** [comment]
Note - there should be an option to enable/disable per-library as some people won't want it remembering the song position

**Comment by vodkapmp** [comment]
This really is the only missing feature that is keeping me from completely switching away from my subsonic setup.
Being able to get in my car in the morning and not have to fiddle with my phone to get my music going is an absolute minimum requirement for a music app for me.

**Comment by richlawson** [comment]
I would also love to see this feature.

**Comment by Chaphasilor** [comment]
This will be part of the redesign beta :)

**Comment by Chaphasilor** [comment]
@natedawg @richlawson @internetfreak @djohnson1865 the queueing system has been improved as part of the redesign beta, and the last played queue will now be restored after a restart. You can also switch between other, previously saved queues.  
You can check the beta out here: https://github.com/jmshrv/finamp/releases/tag/0.9.2-beta

I'll close this issue for now since it should be resolved.
