### ISSUE TITLE
Consider reducing the size of blocks in grid view for tablets

### ISSUE THREAD

**Issue by n00b12345** [jmshrv/finamp#601]
On tablets (eg. Samsung Galaxy Tab), the grid view leads to huge blocks or grids for album/artist covers. Could you consider reducing the size or creating an option to reduce the size of these blocks?

Thank you for making Finamp.

**Comment by jmshrv** [comment]
You can make album covers smaller by increasing the cross-axis count in Settings > Layout & Theme :)

**Comment by Chaphasilor** [comment]
Hi! There's a two setting under "Layout & Theme" with "Grid Cross-Axis Count" in the name, you can use those to customize how many tiles are shown in a row. Increasing these values should decrease the size.  
Does that solve your problem? 🤔

**Comment by n00b12345** [comment]
> You can make album covers smaller by increasing the cross-axis count in Settings > Layout & Theme :)

Thank you so much ❤️
