### ISSUE TITLE
[0.9.3-beta] Download started icon is covered by side menu (IOS)

### ISSUE THREAD

**Issue by cochcoder** [jmshrv/finamp#611]
When you download your entire music library through the side menu, the icon that lets the user know that the download has started  is covered by the menu, as shown below. This most likely happens on Android phones as well, I don't have an android phone to test this hypothesis though. 

![image](https://github.com/jmshrv/finamp/assets/103969142/b0216401-501b-422e-a197-a471121462c5)

**Comment by Chaphasilor** [comment]
You mean the confirmation message with the white background that is shown above the mini player?  
Yes that is unfortunate, but I'm planning to redesign the menu anyway so I'll probably leave it like this for now.

But thanks for reporting it, really good catch! 😁
