### ISSUE TITLE
[0.9.3-beta] Wrong looping when skipping at the end of an album in "loop one" mode

### ISSUE THREAD

**Issue by pinsarda** [jmshrv/finamp#615]
#### Description of the bug : 
When skipping the last song of an album in "loop one" mode, the progress bar resets but the song keeps playing as if nothing happened. The same goes for the last song of a playlist.

#### To reproduce : 
- Start any last song of a playlist/album
- enable "loop one" mode (looping for a single song not the all album)
- try skipping

#### Possible desired behaviour : 
- start from the beginning of the song
- do nothing and not reset the progress bar
- restart at the first song of the playlist

(The last option seems the more coherent with the rest of the existing system to me)

**Comment by Chaphasilor** [comment]
As you already seem to have noticed, this has been fixed with 0.9.4/0.9.5! Let me know if you have any other issues with the queue!
