### ISSUE TITLE
Track Order within Album gets shuffled on Offline Mode

### ISSUE THREAD

**Issue by lukaslindnermusic** [jmshrv/finamp#618]
Hey there, 
I don't know if you know this already, I have not found the bug on here so I thought I make up a new discussion here.
I downloaded a playlist with 4 albums in it, and somehow it did not download two tracks on two of the albums so I navigated to the individual albums and hit download again on them.
Then I realized that the order is "random" when in Offline mode. 
![IMG_4557](https://github.com/jmshrv/finamp/assets/8149031/87b13c1f-8dc5-42d4-b9de-88b6b5538aef)

When I disable Offline Mode:
![IMG_4558](https://github.com/jmshrv/finamp/assets/8149031/228d9707-6a3b-4f7a-90f0-d458243a7f00)

...the order corrects itself, but back in Offline Mode, it is shuffled again.
I tried deleting the playlist and downloads and re-downloading the albums, but when hitting delete and accepting, the album does get removed from the downloaded list in the menu and does not appear anymore in offline mode, but it still has the blue download-icons next to them, and when I re-download the albums, it happens really quickly, which makes me assume that the old downloads did not get deleted properly. And of course, the track order bug still is there. 

Is this a known bug? Is there a way to solve it besides deleting the actual album from jellyfin and re-adding it? 

Thank you 😊 

Oh yeah, from the pictures it gets clear that I am using Finamp on iOS, but here the specs:

Jellyfin Latest 10.8.13 on a Docker Container on my Synology DS920+
iPhone 14 Pro with iOS 17.3.1
Finamp Version 0.6.20

I don't know if the bug was present in the previous version.)

**Comment by lukaslindnermusic** [comment]
Update: 
I have re-installed the whole app and can confirm now, that (for me) the shuffle-ing of the track order of downloaded albums in Offline Mode happens with every album downloaded using the new version 0.6.20.

I also added the logs of an album download to this comment.
Is this bug only happening to me or is it a general bug in the app?

Thank you for your help 😊 

[Finamp Download Log 2024-03-02 Kopie.docx](https://github.com/jmshrv/finamp/files/14470554/Finamp.Download.Log.2024-03-02.Kopie.docx)

**Comment by lukaslindnermusic** [comment]
Update 2: With the Beta of the Redesigned UI, it seems that the issue already is resolved.

**Comment by Chaphasilor** [comment]
Hi, thanks for the report!

It could be that the ordering issue was introduced with the last update, I'll take a look. But it's good to know it doesn't happen in the beta. The download system there is brand new and way more advanced, so I'm glad that everything is working as it should!
