### ISSUE TITLE
Download individual songs.

### ISSUE THREAD

**Issue by Bitwolfies** [jmshrv/finamp#62]
If there’s an option for it I can’t find it, would be a nice qol option to add if possible.

**Comment by UnicornsOnLSD** [comment]
This should be easy to add, I think I did the backend stuff for it a while ago. The only issue would be whether or not to also save the parent. Having the song only show up in the songs tab will be a bit clunky, but you could also argue that downloading one song in an album shouldn't download the whole album.

**Comment by Bitwolfies** [comment]
> 
> 
> This should be easy to add, I think I did the backend stuff for it a while ago. The only issue would be whether or not to also save the parent. Having the song only show up in the songs tab will be a bit clunky, but you could also argue that downloading one song in an album shouldn't download the whole album.

If you mean should it still display as an album even with one song, id say yes thats how id prefer it.

**Comment by drazil100** [comment]
Same. I never use the songs tab in any music app I ever use. Anything I have that isn't part of an album I go out of my way to edit the metadata on to say it's album is "No Album" by "Various Artists" so I always know where to find the loose songs. If I am only downloading part of an album id still like to find it in the album I know it's a part of.

**Comment by perniczech** [comment]
I'm with the others on this one, I just tried the app today (was waiting for a Play Store release, I'm lazy) and it actually threw me off a little when I added a single song into a test playlist, downloaded the playlist and then didn't see the song's album in the album section.

**Comment by UnicornsOnLSD** [comment]
I could probably make it so that downloading a single song also adds the album to offline mode.

**Comment by Bitwolfies** [comment]
> 
> 
> I could probably make it so that downloading a single song also adds the album to offline mode.

That is the best course of action imo.

**Comment by rodcramp** [comment]
Linked with downloading, when downloading a Genre ALL tracks, i.e. likely different Genres, from an album are downloaded.
This would be okay if in offline mode you can filter by Genre, however at this point you can't..
(Am a N00B, apologies if not appropriate to mention this on this #)

**Comment by UnicornsOnLSD** [comment]
Going to note that in #213 as I will need to model genres, which may be pretty complex

**Comment by Chaphasilor** [comment]
@Bitwolfies the download system has been improved as part of the redesign beta. You can now download individual songs using the song menu.  
You can check the beta out here: https://github.com/jmshrv/finamp/releases/tag/0.9.2-beta

I'll close this issue for now since it should be resolved.
