### ISSUE TITLE
[Redesign] Videos in playlists don't show up correctly

### ISSUE THREAD

**Issue by Danar435** [jmshrv/finamp#621]
While it's not properly supported in Jellyfin, you can add videos in playlists. Videos work like songs in Finamp, but with the redesign, opening the playlist results in a broken song list. Note that I can still play songs and the queue works just fine.

![image](https://github.com/jmshrv/finamp/assets/60707126/c73d5b2c-54d1-4731-9d67-4328eaec96d6)

**Comment by Chaphasilor** [comment]
@Danar435 this has finally be released with 0.9.5. You should now be able to browse and play all your music videos with Finamp again! :D
