### ISSUE TITLE
Can't remove songs from queue with gestures off

### ISSUE THREAD

**Issue by Void345** [jmshrv/finamp#622]
Hiya 🙂 

I have gestures off because I kept catching the next/previous track gesture when trying to switch apps by swiping the bottom of the screen, but it seems like it's not possible to remove songs from the queue when these are off.

Is there some other way to do it that I'm missing?

**Comment by Void345** [comment]
Thanks for getting back so fast! :D
That's all I've noticed at the moment, I'll let you know if I find anything else.

**Comment by Chaphasilor** [comment]
Getting back to this, I think you're using the stable/normal version, and not the beta, correct? Because on the beta it *was* possible to remove tracks from the queue before. I've fixed that now and added the button as a replacement, but that got me confused about your issue ^^

**Comment by Void345** [comment]
Yeah, I'm using the stable version at the moment. I'll grab the beta now and see if I can do it on there.

**Comment by Chaphasilor** [comment]
@Void345 there should now be the proper button if you have gestures disabled, and swiping to remove from queue shouldn't be possible anymore

**Comment by Void345** [comment]
Yep, looks good to me. Thank you!
