### ISSUE TITLE
[0.9.3-beta] Add to Queue not working in Offline Mode

### ISSUE THREAD

**Issue by lukaslindnermusic** [jmshrv/finamp#626]
Hi 😊

When long-pressing an album in album list view while in Offline Mode and then trying to Add it to Queue, an error gets displayed (failed host lookup). The same with Shuffle to Queue and the two Next Up options. Looks like these functions dont get that I am in offline mode.
However, when I click on the album and add it via the album view, it works.

(I don‘t know if this issue is already known but I havent found it here. Sorry if this is a duplicate.)

Specs:
Finamp 0.9.3-beta
iOS 17.3.1 on an iPhone 14 Pro
Jellyfin 10.8.13 - Docker on Synology DS920+

**Comment by Chaphasilor** [comment]
Ahh, good catch. Yeah that makes sense, in the album list we don't have the tracks yet so those need to be fetched first. Not sure if that never was implemented for offline mode or if it got buried at some point, but that should be relatively simple to fix.

I'll take a look tomorrow!

**Comment by Chaphasilor** [comment]
Well it wasn't exactly *tomorrow*, but it will be part of the next update, coming this week!

**Comment by Chaphasilor** [comment]
@lukaslindnermusic can you confirm this is working now? Or did I miss something?

**Comment by lukaslindnermusic** [comment]
> @lukaslindnermusic can you confirm this is working now? Or did I miss something?

sorry for the late reply on this, I forgot to try it when the new update was released, but I did now and everything works fine now 👍 💯 

Thank you! 😊
