### ISSUE TITLE
Playlist 

### ISSUE THREAD

**Issue by princzsaharan** [jmshrv/finamp#631]
I have set my playlist in specific order, when you download the playlist for offline, that order is messed up. For iPhone

**Comment by Chaphasilor** [comment]
Which version? 0.6.20?

**Comment by princzsaharan** [comment]
Yes, it is 0.6.20.

**Comment by Nexusnui** [comment]
This seems to be the same problem as [this issue](https://github.com/jmshrv/finamp/issues/634).
