### ISSUE TITLE
Can't access playlists

### ISSUE THREAD

**Issue by Mowmoh** [jmshrv/finamp#633]
Hello,

After updating my Jellyfin server to 10.9 I can no longer find any of my playlists.
I am using the redisign beta and I can see playlists on other apps.

Thank you for this awesome app 😃

**Comment by Chaphasilor** [comment]
This is probably related to #501

I'll try asking the server devs what the plan for playlists is, going forward.

**Comment by Chaphasilor** [comment]
Playlists should be accessible again. There currently is a bug on the server that prevents loading automatically-created playlists, but any playlists you created manually (or through plugins) should be there.
