### ISSUE TITLE
Offline track list out of order

### ISSUE THREAD

**Issue by eaott** [jmshrv/finamp#634]
On several recently-downloaded albums, when I switch to offline mode, the track list is out of order after selecting that album from the Albums tab. When hitting "play" it plays this order as well, not the original track listing.

Example orderings:
3, 8, 6, 17, 9, ...
1, 4, 3, 5, 2
23, 20, 5, 18, 17, ...

From what I can tell, it's not sorting based on length or alphabetically (even ignoring stopwords).

Track numbers match correct titles, and go back to being in order when I switch to online mode.

I use the default internal storage /data/user/0/com.unicornlsd.finamp/app_flutter/songs

Environment:
Google Pixel 4a (5g)
Finamp 0.6.20
Jellyfin 10.8.13 running on Ubuntu 22.04.1

**Comment by Nexusnui** [comment]
This also effects playlist that where redownloaded after the recent update. Playlist downloaded before the update are still displayed in the correct order.

**Comment by Nexusnui** [comment]
This seems to be the same problem as [this issue](https://github.com/jmshrv/finamp/issues/631)

**Comment by Chaphasilor** [comment]
Okay, I just made an attempt to fix this. The bug is related to the new syncing functionality added with the last update. My fix will probably reduce performance for very large playlists, but the ordering should be correct now.  
Would anyone like to test this before we publish the update?

**Comment by Chaphasilor** [comment]
This should be fixed now. You might have to re-download the affected collections

**Comment by rnbastos** [comment]
I have this same problem but found a workaround: not leaving the field "disc" blank, in tracks metadata... after setting it to "1" in all tracks of an album, offline album was back to normal order...
