### ISSUE TITLE
[Redesign] Change Play and Shuffle button design

### ISSUE THREAD

**Issue by snppls** [jmshrv/finamp#635]
The Play and Shuffle buttons are too prominent and distracting in it's current state IMO.

I would propose something like the mockup presented here. It involves reducing the size of the buttons slightly and removing the color - it also incorporates a drop down arrow in place of the 3 dot hamburger menu thing (which currently feels disconnected from the current Play and Shuffle buttons). I believe it also keeps the design logic of other parts of the app where icons are represented by black or white outlines only.

![play](https://github.com/jmshrv/finamp/assets/156883144/768db799-1847-462b-967b-37c155e834bc)

**Comment by Chaphasilor** [comment]
The current design is only temporary, for making it possible to use the new queue features before the new design is finished. Take a look at https://github.com/jmshrv/finamp/issues/220#issuecomment-1242713949 and https://github.com/jmshrv/finamp/issues/220#issuecomment-1242791022 for a mockup of how it should look in the end. The actual elements might still change, depending on the features that are available and planned.

**Comment by lukaslindnermusic** [comment]
Is a redesign of the album/playlist/artist headers still planned @Chaphasilor ?

If no: How about something like this - which matches your recently redesigned long-press menus?

<img src="https://github.com/user-attachments/assets/d8edd3a5-ef5b-4264-8587-887f5ff6095d" width="300"/>

**Comment by Chaphasilor** [comment]
That's a nice idea, yes!

Should be a bit more colorful, but that's easy to add :)
