### ISSUE TITLE
Ios: playback does not resume after interruption.

### ISSUE THREAD

**Issue by Bitwolfies** [jmshrv/finamp#64]
After Using the mic or something else that requires the speaker, audio does not resume after control is handed back. Cannot be started in control centre, must be unpaused in app.

**Comment by UnicornsOnLSD** [comment]
I couldn't reproduce this in the built-in iOS recorder app on an iPhone 6. Can you give a specific example where it stopped?

**Comment by Bitwolfies** [comment]
iPad OS, using the keyboard mic.

**Comment by jmshrv** [comment]
Couldn't reproduce on an iPad simulator, assuming that this has fixed itself
