### ISSUE TITLE
problem when playing audio in flutter

### ISSUE THREAD

**Issue by marycanonce** [jmshrv/finamp#644]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to load asset: "assets/assets/music/Those_Bygone_Years.mp3".
The asset does not exist or has empty data.
#0      PlatformAssetBundle.load.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:324:9)
<asynchronous suspension>
#1      AudioCache.fetchToMemory (package:audioplayers/src/audio_cache.dart:99:22)   
<asynchronous suspension>
#2      AudioCache.load (package:audioplayers/src/audio_cache.dart:130:31)
<asynchronous suspension>
#3      AudioCache.loadPath (package:audioplayers/src/audio_cache.dart:139:26)       
<asynchronous suspension>
#4      AudioPlayer.setSourceAsset (package:audioplayers/src/audioplayer.dart:421:23)<asynchronous suspension>
#5      AudioPlayer.setSource (package:audioplayers/src/audioplayer.dart:348:5)      
<asynchronous suspension>
#6      AudioPlayer.play (package:audioplayers/src/audioplayer.dart:214:5)
<asynchronous suspension>
#7      _MainState.build.<anonymous closure> (package:music_player_app/main.dart:40:13)
<asynchronous suspension>

**Comment by Chaphasilor** [comment]
As far as I can tell, this is completely unrelated to Finamp? 🤔  
We're not bundling assets, we're not using the `audioplayers` package, and we have none of the referenced files in the project...

**Comment by DKSingh1604** [comment]
Exception has occurred.
FlutterError (Unable to load asset: "assets/audio/audio.mp3".
The asset does not exist or has empty data.)


The exception shows error in the correct file directory. It is showing error even though the path is correct, audio is there and audio is working fine. It shows error when I try to tap and play the individual song in the app.
