### ISSUE TITLE
Memory Runaway? 

### ISSUE THREAD

**Issue by aracnacon** [jmshrv/finamp#653]
![D5AF12CE-B443-43D7-B5BE-B5EF41D88C79](https://github.com/jmshrv/finamp/assets/3085282/22c6a7fe-2b01-40ce-8bcd-b3812afd57ef)

**Comment by Chaphasilor** [comment]
Did you download a large playlist or something similar? That's a known issue with the stable version, which is fixed in the beta. You can try out the beta through Testflight :)

**Comment by aracnacon** [comment]
Yes it is a large PL. Can you send me an invite for beta in Testflight?

**Comment by Chaphasilor** [comment]
Here's the link: https://testflight.apple.com/join/UqHTQTSs

You can also find it in the beta release announcement, which you should definitely check out to see what's new: https://github.com/jmshrv/finamp/releases/0.9.2-beta

**Comment by aracnacon** [comment]
Beta runs much better, thank you!
Brandon Hixson  865.226.9148

**Comment by Chaphasilor** [comment]
Awesome!

**Comment by aracnacon** [comment]
Night and day differences in the 2 versions.
Brandon Hixson  865.226.9148
