### ISSUE TITLE
[Redesign][Bug] artist top songs sorting borked

### ISSUE THREAD

**Issue by Tiefseetauchner** [jmshrv/finamp#654]
When clicking a song in the top songs list of an artist that has the same listening amount as another song the wrong song sometimes plays

Mainly reportkng this so I don't forget it, I'll use a more defined algorithm for sortkng the queue and the list here

**Comment by Chaphasilor** [comment]
Awesome. There we also requests to change the order of albums from alphabetic to release date, maybe we can tackle that in the same PR :)

**Comment by Tiefseetauchner** [comment]
So I understand it correctly, when pressing play on the artist the albums are sorted by alphabet?

The display seems correct, at least on whatever build I'm running

![Screenshot_20240328-114848.png](https://github.com/jmshrv/finamp/assets/48085877/f721106e-0d84-49a3-a3c1-245e139295d4)

**Comment by Chaphasilor** [comment]
The related issue is #609 ^^

**Comment by Tiefseetauchner** [comment]
I commented there, I think it requires more discussion on that thread
