### ISSUE TITLE
[Redesign][Feature Request] Toggle for haptic feedback/vibration on button tap

### ISSUE THREAD

**Issue by Ivanf1** [jmshrv/finamp#657]
Hello!

In the redesign version of the app, an haptic feedback/vibration is produced on some buttons tap. I, personally, would prefer to not have any feedback of this kind when a button is tapped.

I think a toggle could be added in the Interactions section of the Settings page. The default would be to leave enabled haptic feedback/vibration.

If this is something that you think may be worth to add, I can start to work on it.

**Comment by Chaphasilor** [comment]
Hey, yeah that sounds like a very reasonable request! Should be not a lot of effort to add this really, so I can add this in the coming days.

But if you want to contribute this yourself, feel free to do so! The [contribution guidelines](https://github.com/jmshrv/finamp/tree/main/CONTRIBUTING.md) should help you get started, and then it's just copying a setting and renaming a few variables, adding a could of new strings to the translations, and using the settings helper to check if the vibration should be enabled.  
Maybe the vibration stuff could also be wrapped in a class to only have one global place where the settings are checked...
