### ISSUE TITLE
Selecting a song from a downloaded playlist in offline mode causes a random song to be played.

### ISSUE THREAD

**Issue by ArialCCAA** [jmshrv/finamp#667]
On the 0.9.3 migration fix patch, selecting a song from a downloaded playlist on offline mode causes a random song to be played.

https://github.com/jmshrv/finamp/assets/82137984/4d484fdb-ce6b-486f-ac49-eafd45c699b9

**Comment by Chaphasilor** [comment]
Hmm, I can't reproduce this. Could it be that you downloaded the playlist using stable version 0.6.20 (which has a bug where the order of downloaded albums and playlists is wrong), and then upgraded to 0.9.3?  
Could you please try deleting the playlist from your phone, and then downloading it again?

**Comment by ArialCCAA** [comment]
I uninstalled the app and reinstalled it, and the problem is still happening. It's actually also happening when in online mode now.

**Comment by ArialCCAA** [comment]
Seems like the issue went away with 0.9.5 for me. Weird though that other users were not able to reproduce this. I use a Poco F5 with stock miui if that's of any use.

**Comment by Chaphasilor** [comment]
Well I'm happy it's fixed now. Let me know if the issues pops up again!
