### ISSUE TITLE
[Feature request] Play next

### ISSUE THREAD

**Issue by YamiYukiSenpai** [jmshrv/finamp#669]
I'd like to have a feature where when I select "Play Next" for a song(s), it'll slot itself after the currently playing song.

**Comment by Chaphasilor** [comment]
That feature should already be there. If you long-press a song, there should be an option to "Play next", even in the stable/normal version.  
In the beta version, this is even more powerful, where there is a separate "Next Up" queue that you can add more songs to, either at the beginning or at the end :)

**Comment by YamiYukiSenpai** [comment]
Aah! Apologies.  I sent it on the wrong project

**Comment by Chaphasilor** [comment]
Haha no worries. Just out of curiosity, which project was the request actually intended for, if you don't mind telling? :D

**Comment by YamiYukiSenpai** [comment]
> Haha no worries. Just out of curiosity, which project was the request actually intended for, if you don't mind telling? :D

it was for [Supersonic](github.com/dweymouth/supersonic)
