### ISSUE TITLE
Not playing specific songs

### ISSUE THREAD

**Issue by Norakthes** [jmshrv/finamp#67]
I would be playing my playlist on my Nubia Z20 (NX627J) running Android 9, and some specific songs would not play with direct play. If I enable transcoding the songs would play, but of course with lower quality (these are lossless FLACs).

[Flutter Logs](https://github.com/UnicornsOnLSD/finamp/files/6802561/flutterLogs.txt)

**Comment by UnicornsOnLSD** [comment]
Could you send a `mediainfo` (https://mediaarea.net/en/MediaInfo) of one of those FLACs? It looks like it has a HEIC or something in there, which could be confusing the player since HEIC support on Android isn't great.

**Comment by Norakthes** [comment]
[Here](https://github.com/UnicornsOnLSD/finamp/files/6803684/MediaInfo.txt) is the mediainfo, and [here](http://norakthes.dk/02.%20%E5%A4%A9%E7%90%83%E3%80%81%E5%BD%97%E6%98%9F%E3%81%AF%E5%A4%9C%E3%82%92%E8%B7%A8%E3%81%84%E3%81%A7.flac) is one of the FLACs in question, if needed.

**Comment by epicgamer11** [comment]
BUMP

Having the same issue here on my FiiO X5 3rd Gen.

It's all fine and dandy on my Huawei P40 Pro, but since I don't use that one for music. I am kind of a bit bummed that it doesn't work on my dedicated music player. It tried and the files all can get played by the stock music player, but not by finamp unless I turn on transcoding.
[mediainfo.txt](https://github.com/UnicornsOnLSD/finamp/files/7799600/mediainfo.txt)

**Comment by UnicornsOnLSD** [comment]
This is likely related to #22. For some reason, not every Android phone comes with a FLAC decoder. There are apps you can get to show all of the supported codecs on your phone. As I said in that issue, ExoPlayer (Android's media framework) does have a FLAC addon to play FLACs on devices without encoders.

**Comment by epicgamer11** [comment]
Yup, seems like that's the issue. I can find no FLAC decoder on the device. Weird that the Stock Music Player still plays them.
I would love see this fixed soon, since I wish to only have a single application for my music on my device.

**Comment by UnicornsOnLSD** [comment]
Maybe every other player includes the FLAC plugin lol, I was surprised too when I found that some phones don't include FLAC decoders. The other issue was posted by someone with a dedicated media player too, which you'd probably only want to play FLACs through

**Comment by epicgamer11** [comment]
Indeed, would love to see this plugin in finamp too. ^^

**Comment by Chaphasilor** [comment]
superseeded by #91
