### ISSUE TITLE
[Bug] Playback content and UI not match

### ISSUE THREAD

**Issue by ha-ku** [jmshrv/finamp#671]
When starting playback from any position and switching to the next song, the next song information is displayed in the UI but the played track remains unchanged.
I’m using the 0.9.4-beta version of Finamp.

**Comment by Chaphasilor** [comment]
You're on iOS 17.4?

**Comment by ha-ku** [comment]
I'm on Android 14.

**Comment by Chaphasilor** [comment]
On Android? Okay that changes things. Would you mind uploading a short screen record showing exactly what you'de doing? 

I haven't managed to reproduce it on my own phone yet...  
And maybe also take screenshots of all your settings, in case that's the issue?

**Comment by ha-ku** [comment]
> On Android? Okay that changes things. Would you mind uploading a short screen record showing exactly what you'de doing?
> 
> I haven't managed to reproduce it on my own phone yet... And maybe also take screenshots of all your settings, in case that's the issue?

Here's the screen record: https://github.com/jmshrv/finamp/assets/18721230/4b33aa4d-dfb7-4043-881a-87a6937f56af

Here's my settings:
![share_4580550784985585430](https://github.com/jmshrv/finamp/assets/18721230/0f59249e-0439-4c9f-8acb-60daa1216065)
![share_4799162640428299047](https://github.com/jmshrv/finamp/assets/18721230/74dbbc75-32af-4560-8e43-1f7b7546f546)
![share_6380697078861946634](https://github.com/jmshrv/finamp/assets/18721230/50544327-767c-4d71-bd11-7b6e8791f909)
![share_6486283633497103633](https://github.com/jmshrv/finamp/assets/18721230/acd05233-6187-43b3-94e2-f08b272d53aa)
![share_6796857581357201597](https://github.com/jmshrv/finamp/assets/18721230/7e0ae308-ba1b-4e6a-b4f8-1755df0d2e0b)
![share_8613288461794414748](https://github.com/jmshrv/finamp/assets/18721230/f2caa4d0-4675-4124-bd59-6e6c4a460991)

**Comment by ha-ku** [comment]
> On Android? Okay that changes things. Would you mind uploading a short screen record showing exactly what you'de doing?
> 
> I haven't managed to reproduce it on my own phone yet... And maybe also take screenshots of all your settings, in case that's the issue?

I did some additional testing and found that this behavior can be triggered by enabling transcoding.

**Comment by snppls** [comment]
I have a similar issue but have created a separate bug report. I'm using iOS 17.3.1 and Finamp 0.9.4. Finamp will update the track info (such as song name and track length) but keeps repeating the same song indefinitely. Turning off transcoding appears to fix the problem.

**Comment by Chaphasilor** [comment]
@ha-ku thanks for the details. I've managed to confirm that transcoding is the problem, and have also figure out why, and what to do about it.  
I'll push an update soon!

**Comment by ha-ku** [comment]
@Chaphasilor Thank you for your dedication! Looking forward to the next release.
