### ISSUE TITLE
[Bug][0.9.4 beta] Can‘t play tracks when switched to offline mode while online-only queue active

### ISSUE THREAD

**Issue by lukaslindnermusic** [jmshrv/finamp#672]
Hey there 😊

with the new beta version, in offline mode, I can‘t play any music (album, tracks,…) through clicking when I had an active queue in online mode (with tracks that are not downloaded) and then paused, switched to offline mode while the queue still exists and then reopen the app later. it just says error once and then I can‘t play anything.
I have to either restore an offline-only-tracks queue or switch back to online and play a downloaded album (which opens up a new queue).

Picture below 😊 

Thank you for your help 😊 
Lukas
![IMG_4764](https://github.com/jmshrv/finamp/assets/8149031/52982c3a-6496-4cb8-8a6d-dd99ee2ba386)

**Comment by lukaslindnermusic** [comment]
Wait:

Switching back to online and tapping on a play button does not work either. You first have to add a downloaded album to next up, then it will play and only then you can play any album directly which starts a new queue.

**Comment by Chaphasilor** [comment]
Hmm. There are issues with playing back downloaded items on iOS, but this seems unrelated.

Could you get me some logs?

**Comment by lukaslindnermusic** [comment]
Hi.

Here is a little screen recording demonstrating the bug (the video was too big for Github so I uploaded it as a not listed youtube video):
https://www.youtube.com/watch?v=VvkhLfb65Ik

And here is the log for the screen recording demo:
[Finamp_Issue672_Demo1_finamp-logs.txt](https://github.com/jmshrv/finamp/files/14893120/Finamp_Issue672_Demo1_finamp-logs.txt)


(Please note that this also happens with queues that have more than one item left. I just happened to choose an album with just one track for the demo)

**Comment by Chaphasilor** [comment]
Thanks for the info. It seems to be related to the audio processing on iOS.  
It *might* get fixed by some changes I made to the queue behavior for the next update, but we'll see 😅

**Comment by Chaphasilor** [comment]
@lukaslindnermusic can you try again with 0.9.5?  
Also, I did see your issue about renaming everything to tracks, I just didn't get to it yet ^^

**Comment by lukaslindnermusic** [comment]
> @lukaslindnermusic can you try again with 0.9.5?
> Also, I did see your issue about renaming everything to tracks, I just didn't get to it yet ^^

I tried it, with 0.9.5, the issue is gone 😊 
I still got the error once, but playing other albums by pressing "Play" worked right away. 
And in my second try, I didn't even got the same error message anymore but a formatted error that the queue could not be restored with the "Retry" option, which seems to be an intended behavior 👍 

Thank you for your great work!
