### ISSUE TITLE
[Bug] Finamp crashes on iOS when playing any song

### ISSUE THREAD

**Issue by snppls** [jmshrv/finamp#676]
On iOS (latest version) the app (0.9.4) crashes almost 90% of the time whenever I choose a song to play. It doesn't seem to make any difference what the song is or what file format it is in. The only workaround I can find is to add the song to the queue first and then navigate to it from there.

**Comment by snppls** [comment]
Update - It seems like having the repeat track option enabled from the player window creates the crashes. If it is enabled, choosing any other song crashes the app 90% of the time.

**Comment by Chaphasilor** [comment]
Interesting. I think I know where the problem might be coming from, and why it's only an issue on iOS.

But still, are you able to share a video of the issue, just to be sure?

**Comment by snppls** [comment]
Interestingly after restarting the app I was able to play songs just fine while the repeat track option was selected and I couldn't recreate the issue. But... if I then added a song to the queue while repeat was still on, the app would crash when choosing other songs. Maybe it has something do with how queue and repeat are interacting?

Not sure if this video is helpful. I can record using another phone if thats better.


https://github.com/jmshrv/finamp/assets/156883144/ce35c1b5-21ff-4414-a299-2069246f6aa4

**Comment by Chaphasilor** [comment]
I sadly can't give you anything to test because Apple is Apple, but I think I made some changes that could fix this issue 😅  
I guess we'll see...

**Comment by Chaphasilor** [comment]
@snppls can you try again with 0.9.5?

**Comment by snppls** [comment]
Hello, I've been testing for the last few days on 0.9.5. I am no longer experiencing any crashes. The problem seems to be resolved now. Thank you for the pushing the fix so quickly.

**Comment by jmshrv** [comment]
The redesign beta has a new downloads system, so your issue probably isn't applicable here. Performance in the old system was pretty bad, I'd recommend you try out the redesign beta to see if your issue is fixed there - https://github.com/jmshrv/finamp/releases/tag/0.9.5-beta

**Comment by ExpatUK** [comment]
FWIW, on iOS 14 the app is pretty reliable however seems to reliably crash when Google Maps (and only Google Maps?!) is in the foreground for more than about 45 seconds. Makes listening with driving a real pain! Last release didn't have this issue.
