### ISSUE TITLE
[Bug] Finamp plays one song indefinitely 

### ISSUE THREAD

**Issue by snppls** [jmshrv/finamp#678]
Finamp will repeat the current song indefinitely even when the option has been turned off. The song details will change in the player window along with the track length but it will still be playing the first song. Using the next and forward buttons just replay the same song. The only way to play the next song is to manually select it. Turning off transcoding appears to fix the problem. I'm using iOS 17.3.1 and Finamp 0.9.4.

**Comment by Titaniumtown** [comment]
I can reproduce this issue on grapheneOS with finamp 0.9.4

**Comment by Chaphasilor** [comment]
Thanks for the report. Yes, transcoding doesn't work on 0.9.4, I've already identified the problem and implemented a fix. Will push an update later today!

**Comment by snppls** [comment]
Fantastic news! Thank you so much!!!

**Comment by Chaphasilor** [comment]
I'm guessing this isn't a problem any longer?

**Comment by Titaniumtown** [comment]
@Chaphasilor correct, I can no longer reproduce the issue. Thank you for all your hard work, extremely appreciated!
