### ISSUE TITLE
[Redesign] Artist pages fail to show albums

### ISSUE THREAD

**Issue by natedawg** [jmshrv/finamp#682]
When viewing an artists page there are no albums listed only the top songs list. The `Albums` header text flashes on the screen for a half second before the top songs list is displayed.

**Comment by Chaphasilor** [comment]
Could you share a video and logs of the issue?  
Also, which device and server are you using?

**Comment by natedawg** [comment]
I upgraded from the last stable version to 0.9.5-beta. Before getting the logs I decided to clear the app cache/data and it worked. Now I can see artist albums. This is on android and running jellyfin 10.8.13
