### ISSUE TITLE
[Feature Request] Themed/Material/Adaptive Icon Support

### ISSUE THREAD

**Issue by MidnightSlicer** [jmshrv/finamp#686]
I would like to see Finamp get [themed icon](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive) support. I have never worked in Flutter, but it seems possible to do based off [this](https://medium.com/@Toglefritz/add-android-themed-icon-support-to-your-flutter-app-203a7b49d37b) post. I will have time to do it myself in a few weeks, but I just wanted to make sure it is not something that is already in the works. Thank you!

![Screenshot_20240407-145418](https://github.com/jmshrv/finamp/assets/135987269/1ca59aa3-612a-46a6-bbef-98eaab8302d1)

**Comment by Chaphasilor** [comment]
You should try the beta version (available through the Play Store or in the releases section). It should already have adaptive icon support!

**Comment by MidnightSlicer** [comment]
@Chaphasilor I just now opted in, uninstalled and reinstalled (to make sure there wasn't anything weird) and it is not implemented. Strangely, even though the Google Play store says I am in beta I am still on version 0.6.20 according to the in-app about screen. I will keep you updated in case the Play store is just being weird and not giving me the beta yet.

**Comment by MidnightSlicer** [comment]
Aha! Now I'm actually enrolled and got an update. Adaptive icons are added. Thank you! :D

**Comment by Chaphasilor** [comment]
Perfect! Let me know if you have any issues with the beta.  
You should also check out the full release notes here on GitHub (https://github.com/jmshrv/finamp/releases) and join the Discord server (linked in the release notes) for easier discussion and bug reporting dueing the beta :)

**Comment by camperboy1000** [comment]
Look like the latest beta release (0.9.7) broke this. Finamp is no longer themed on my home screen.

**Comment by MidnightSlicer** [comment]
I also see that too. Must be a regression.
Thank you,
Dylan
***@***.***
Sent from Proton Mail Android
-------- Original Message --------On 5/23/24 12:43 PM, Jacob Highfield  wrote:
Look like the latest beta release (0.9.7) broke this. Finamp is no longer themed on my home screen.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/jmshrv/finamp/issues/686#issuecomment-2127722657",
"url": "https://github.com/jmshrv/finamp/issues/686#issuecomment-2127722657",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by camperboy1000** [comment]
Looks like this has already been fixed in #741 as stated in #742
