### ISSUE TITLE
[BUG] Shuffle all button in wrong tab

### ISSUE THREAD

**Issue by Kan-El** [jmshrv/finamp#691]
If i reorder the tabs in settings so that the songs tab isn't last, the shuffle all button stays on the last tab. 
This happen on both the android and IOS app using version 0.9.5

**Comment by Chaphasilor** [comment]
Thanks for the report, and sorry for "ignoring" this issue. I read the notification and confirmed it, just never got around to replying.  
This should be (mostly) fixed with the next update :)

**Comment by Kan-El** [comment]
Thanks! This seams to works as expected now on version 0.9.6

**Comment by Chaphasilor** [comment]
Wonderful!
