### ISSUE TITLE
Issues with artists following library move

### ISSUE THREAD

**Issue by Beezerphd** [jmshrv/finamp#698]
![Screenshot_20240425-193853](https://github.com/jmshrv/finamp/assets/168127651/bd16f1b5-c7a1-4a17-89a2-b4137dc545cb)
![Screenshot_20240425-193835](https://github.com/jmshrv/finamp/assets/168127651/2e272fc2-5b2d-4b11-94df-a7d8fdb82e9c)
I've recently moved my entire library to a different location and all is fine on jellyfin. 

However my finamp app seems to have issues with the artists tab. 

Choosing any artist will display almost every album in my library. 

It's also the same list of albums regardless of which artist I choose. 

I've tried clearing the application cache. Deleting and reinstalling and still the same issue. 

I'm using Android and version 0.6.21

**Comment by kazango** [comment]
This bug was introduced in the last update and has apparently now been fixed (yesterday), just waiting on it being pushed to the iOS/android app stores

**Comment by Chaphasilor** [comment]
update should be live now :)
