### ISSUE TITLE
BUG - V9.5 Beta - when searching in offline mode, the tapped song is not selected

### ISSUE THREAD

**Issue by enduring78** [jmshrv/finamp#701]
Hi! I have been using the Finamp 9.5 beta for a few weeks now, and it looks and feels really nice!

One minor bug I have noticed is that when I am using offline mode and search for a song in the 'songs' tab and tap the wanted song, instead of the song I tapped it starts playing the Xth song from the top. 

Steps to reproduce:
- Download some music
- Switch to offline mode
- Search for a song you downloaded, let's say it is number 3 in the result list
- Tap on it to play
- You will see, that instead of playing it, it starts playing the 3rd song from the full list of downloaded songs instead of the one you selected.

**Comment by Chaphasilor** [comment]
Thanks for the report! This will be fixed with the next beta update :)
