### ISSUE TITLE
Playback stops when phone locks

### ISSUE THREAD

**Issue by mcarlton00** [jmshrv/finamp#703]
Just started happening a few days ago.

1. Shuffle play favorites
2. Set phone aside
3. Phone will play the first track with no issues
4. Phone will either immediately stop after the first track or play a few seconds of the second track and then stop
5. Unlock phone, will start playing again (usually a different track than the one it already started)

Based on the logs, it looks like when the device locks all playback reporting stops working because of DNS issues.  Not sure if this also affects playback itself, but it appears so on my device.   Happens both on wifi and mobile data.

[finamp-logs.txt](https://github.com/jmshrv/finamp/files/15138515/finamp-logs.txt)

Device info:
Pixel 6a
Android 14
Finamp version: 0.6.21 (latest google play is letting me have)

**Comment by Chaphasilor** [comment]
If there are DNS issues, could you please try downgrading to 0.6.20 to see if it's working there?

**Comment by mcarlton00** [comment]
downgraded to 0.6.20 and everything functions as expected.  5 songs in right now.  Scrolling through the logs only difference i see is no playback reporting failures even when it's locked

**Comment by Chaphasilor** [comment]
The only changes that might be relevant are that our http library was updated, the target SDK was changed from 33 to 34, and we updated the header used for authentication.  
Here's a custom build with a lower target SDK and updated http library: https://gofile.io/d/UgVyR0  
You can install it along-side the regular app to try it out.

**Comment by mcarlton00** [comment]
That test version also works correctly, songs played without issue on the lock screen.

I then uninstalled both the test version and 0.6.20 and installed the 0.6.22 apk and the problem is back.  Switched back to test version and everything good.

**Comment by jmshrv** [comment]
Had a bad feeling changing that, damn you Google Play for nagging me

I can push a new build on API 33 for now, although Google will force API 34 in like 6 months or so

**Comment by jmshrv** [comment]
Release fixed, looks like it works :)

**Comment by Chaphasilor** [comment]
@mcarlton00 did the DNS issues also go away with the test build, and re-appear with 0.6.22?

**Comment by mcarlton00** [comment]
Correct.

0.6.21 - borked
Linked test build - Good
0.6.22 - borked
0.6.23 - Good

**Comment by Chaphasilor** [comment]
That's so weird. Let's hope that issue resolves itself by the time we are forced to bump the sdk target again 😅
