### ISSUE TITLE
No Android UI integration

### ISSUE THREAD

**Issue by ethanarns** [jmshrv/finamp#704]
To make sure it wasn't just me, I checked with the main JellyFin app, and it worked. There is no music widget in the pull-down drawer where notifications are for FinAmp. It also will repeatedly pause in the background despite having background usage enabled, as well as the same settings the working JellyFin app has. I think something has gone wrong with the Android UI integration.

Steps
1. Open FinAmp
2. Start playing a song
3. Drag from the top of the screen to pull down the notifications screen
4. There is no widget

Device info:
Pixel 8
GrapheneOS (Android 14)
0.6.21 (Play Store)

**Comment by ethanarns** [comment]
Using the 0.9.2-beta seems to have fixed it. Not sure what that makes this issue

**Comment by jmshrv** [comment]
Sounds related to #703, will fix now

**Comment by jmshrv** [comment]
Oh by the way, 0.9.2 is an old beta, there have been quite a few bug fixes since then :)

**Comment by ethanarns** [comment]
That was easy. Thank you.

> Oh by the way, 0.9.2 is an old beta, there have been quite a few bug fixes since then :)

Which should I install?

**Comment by jmshrv** [comment]
[0.9.5](https://github.com/jmshrv/finamp/releases/tag/0.9.5-beta) is the latest redesign beta
