### ISSUE TITLE
Playback metadata for bit rate incorrect for downloads

### ISSUE THREAD

**Issue by solidsnake1298** [jmshrv/finamp#713]
When playing back downloaded files the correct codec is displayed but the bit rate of the original file is shown.

All of the screenshots below should be 192Kbps@OPUS.  Instead they show the original MP3 and FLAC bit rates but the download's codec.

![Screenshot_20240504-182323.png](https://github.com/jmshrv/finamp/assets/137357145/6773f52b-024b-49db-8669-f922d4dc3fb1)

![Screenshot_20240504-182315.png](https://github.com/jmshrv/finamp/assets/137357145/a0b5049d-ea1d-4394-83ff-aabaadbf0cba)

![Screenshot_20240504-182353.png](https://github.com/jmshrv/finamp/assets/137357145/2a6b6483-09b1-46bd-8867-23c40a84cd56)

**Comment by Chaphasilor** [comment]
fixed in 03fbdaa94dc0f3d3ea5ed986f0de7405c98b7d70

Will be part of the next update :)
