### ISSUE TITLE
iOS: audio stops playing when Finamp is backgrounded

### ISSUE THREAD

**Issue by jellersby** [jmshrv/finamp#721]
Finamp had been working great for years... until today! I think it must have been updated to a new version. Now whenever the app is backgrounded, the audio from the app stops completely, as if it's not configured to have a background audio session or something.

iOS 17.4.1
Finamp 0.6.22

Nothing interesting in the logs unfortunately. Just a bunch of successful Jellyfin API requests. Maybe there's a debug-enabled build out there that I can try?

**Comment by jellersby** [comment]
Apologies, this appears to have been a local issue with my phone. After rebooting, Finamp plays audio in the background.

**Comment by Chaphasilor** [comment]
That's a relieve! Thanks for letting me know!  
And I'm glad everything is working again for you :)
