### ISSUE TITLE
Font color of fast scroller 

### ISSUE THREAD

**Issue by libook** [jmshrv/finamp#722]
The fast scroller on the right side of the UI is in black font and is not recognizable above dark album covers.

![微信图片_20240510153656](https://github.com/jmshrv/finamp/assets/3395610/5af30a2b-2d89-42b8-8732-1ee045666e81)

As you can see, I can not see A-G.
Consider adding something like a shadow effect to the text to enhance their recognizability?

**Comment by Chaphasilor** [comment]
I'm guessing you're using version 0.6.23?

You should try out the beta, the fast scroller there shouldn't have that issue, and should be much better in general!

**Comment by libook** [comment]
> I'm guessing you're using version 0.6.23?
> 
> You should try out the beta, the fast scroller there shouldn't have that issue, and should be much better in general!

Yes you are right.

I have looked at the beta, it's better.

How about this effect by adding a white border following the shape of the character so that there is no need for a white background?

![图片](https://github.com/jmshrv/finamp/assets/3395610/14e5da60-fa1a-454d-a45e-e29523dca603)

Of course if you feel the current design is good enough, I respect that choice.

**Comment by Chaphasilor** [comment]
I might try it out. My plan was to shift the covers to the left when redesigning grid view, so that the fast scroller isn't overlaying the covers at all anymore.  
What do you think about that?

**Comment by libook** [comment]
> I might try it out. My plan was to shift the covers to the left when redesigning grid view, so that the fast scroller isn't overlaying the covers at all anymore. What do you think about that?

That way the click area of the fast scroller wouldn't have an overlapping section with the album click area on the right, probably a good idea too.

You can try to see if there is enough display space, after all, the it is always a bit cramped for vertical screens.
