### ISSUE TITLE
[Feature Request] Allow to filter by favorites in offline mode

### ISSUE THREAD

**Issue by enduring78** [jmshrv/finamp#725]
I'm currently using the latest 0.9.6 Beta release, and one thing I have noticed is that when in online mode and connected to Jellyfin, I am able to filter by favorites. 

This isn't possible in offline mode, and thus I have to remember to instead of clicking the heart icon, adding the song to a playlist which is automatically downloaded. 

Steps to reproduce:
- Enable online mode, add a song as favorite
- Click the heart button at the top. Now, all songs marked as favorite will show
- Enable offline mode
- The heart icon at the top disappears, making the favorite feature unusable in offline mode.

**Comment by Chaphasilor** [comment]
Yeah that's a bug introduced with 0.9.7, which will be fixed with the next update. Sorry about that 😅
