### ISSUE TITLE
[Feature Request] Add ability to save and show lyrics offline

### ISSUE THREAD

**Issue by TheParaTiger** [jmshrv/finamp#731]
It's possible that this has been planned already, but i figured having this as a feature request may be useful

It would be awesome to have Finamp download the lyrics file from the Jellyfin servers for offline mode and also show them when the song where the lyrics belong to gets played offline. Right now, Finamp only shows lyrics in online mode (or it's just bugged for me, which could also be the case, i run jellyfin 10.9.1)

Also thanks to the whole team because the redesign looks awesome!

**Comment by Chaphasilor** [comment]
Hey, that is indeed already possible! For that you need to go to the downloads screen (in online mode), and tap the middle button at the top right, which initiates a downloads repair.  
Wait for it to finish and then your lyrics should be available offline too!

It might be that there is a separate bug in offline mode that causes problems, but that should only appear when opening the menu on the player screen in offline mode, and we're working on a fix!

**Comment by TheParaTiger** [comment]
Great! Thanks for the help!
