### ISSUE TITLE
[UI] Option to swap Stop button with Heart button in Android player pane

### ISSUE THREAD

**Issue by AverageHelper** [jmshrv/finamp#736]
Android displays a panel in the notifications drawer with some player controls, and I assume some of these are configurable by the app since the set of available controls varies from app to app.

Currently, and as of the latest Beta, Finamp has a square button that Stops playback. I wonder if there could be a setting added to replace the Stop button with a Heart button, to allow easily marking tracks as Favorite from the notification drawer.

**Comment by weiyideai520** [comment]
Agreed.

Additionally, in Xiaomi Hyper OS, the stop button is blank.
![Screenshot_2024-05-21-14-24-09-920_com miui home](https://github.com/jmshrv/finamp/assets/2784569/77ab17a6-9f39-437f-bce2-51f90b042a10)

**Comment by AverageHelper** [comment]
Same in AOSP. I figure it's meant to be a square "stop" button, but it's so clunky and sharp compared to the other controls it feels kindof odd, lol

**Comment by Chaphasilor** [comment]
Will be added with the next update (heart button + better icon for stop button)
