### ISSUE TITLE
[Redesign] Within lyrics; remove the timestamp next to the line if it's empty.

### ISSUE THREAD

**Issue by MustThinkOfAName** [jmshrv/finamp#737]
In .lrc files, empty timestamped lines are often used to demarcate verses. In my opinion, timestamping should not apply there.

![signal-2024-05-21-205856_002](https://github.com/jmshrv/finamp/assets/60283063/23d76331-e490-493d-9a96-fc6fe88d8ffc)

**Comment by Chaphasilor** [comment]
That's a good point. I'll do that for the 0.9.8 release!
