### ISSUE TITLE
[Bug] Downloaded/offline songs doesn't have lyrics

### ISSUE THREAD

**Issue by Extarys** [jmshrv/finamp#739]
It seems that downloading a playlist still shows those songs has having lyrics on the playlist view, but then when playing that song the UI show that there are no lyrics.

I tried repairing the download while online as suggested by a user, but it didn't fix the issue. I'm on 0.9.7 (latest beta).

Related:
https://github.com/jmshrv/finamp/issues/731

This is _not_ a bug because maybe it's simply not yet implemented. Thanks for the amazing releases, I **really** enjoy Finamp.

**Comment by Chaphasilor** [comment]
Interesting. What do you currently have downloaded? The playlist itself, or only some tracks from that playlist?  

And I assume the lyrics icon is also shown in offline mode?

Either way, if you could get us some logs, that might help diagnose the issue :)

**Comment by Chaphasilor** [comment]
Logs are a bit finnicky still. If you don't mind, just send all of them and I'll take a look at the relevant sections.  

The behavior you are describing is the exact opposite of the title and your original comment though. Could you please confirm that lyrics are *not working in **online** mode*, but working in **offline** mode?  
And if that's the case, do you see the lyrics in the Jellyfin web app?

It could be that lyrics aren't properly cleared from downloads if you remove the lyrics in Jellyfin...

**Comment by Chaphasilor** [comment]
Ahh I see. Yes, I'm able to reproduce the issue and will look into it!

**Comment by palmbladandreas** [comment]
Is this really solved? i have the same problem and I am on the latest beta
