### ISSUE TITLE
Expanded track details panel doesn't render background completely

### ISSUE THREAD

**Issue by Maxr1998** [jmshrv/finamp#744]
When long pressing a track and then expanding the bottom sheet, the background doesn't cover the whole sheet and is instead black translucent.

<details>
<summary>Screenshot</summary>

![Screenshot](https://github.com/jmshrv/finamp/assets/5903699/c4e68d3c-7373-492b-8573-ded323a8d245)
</details>

**Comment by Chaphasilor** [comment]
This only happens when not on the player screen. The playlist actions menu is also affected.

**Comment by Chaphasilor** [comment]
@Komodo5197 I guess this broke when switching to using the generic menu. Mind taking a look?

**Comment by Komodo5197** [comment]
This is most likely related to the CachePaint widget not redrawing with the new size correctly.  It doesn't seem to be reproducing for me though?

**Comment by Chaphasilor** [comment]
I only have the issue in the release build on Android. Could that be it?

**Comment by Komodo5197** [comment]
Maybe?  I’ll try a release build later.

**Comment by Chaphasilor** [comment]
Closing since this has been fixed a while ago :)
