### ISSUE TITLE
Non-square cover arts have incorrect background shadow

### ISSUE THREAD

**Issue by Maxr1998** [jmshrv/finamp#745]
If a cover art isn't square, it's layouted fine, but the drawn shadow still follows a square shape and extends the actual cover art.

<details>
<summary>Screenshot</summary>

![Screenshot](https://github.com/jmshrv/finamp/assets/5903699/2f5e2c9d-b03e-4332-9641-382f448ed209)
</details>

**Comment by jmshrv** [comment]
Fixed in b08b21169c2bcce46cd4e110ecfb1a387e5b67b5, probably not the cleanest solution ever but it was an awkward one to fix :)

**Comment by Chaphasilor** [comment]
Hmm, I feel like there was a reason why I did it in the wrapping container. I think it was directly applied to the image before, but that caused some other issue. We will see xD

**Comment by Chaphasilor** [comment]
@jmshrv I think this broke the blurhash placeholders. They're tiny now instead of filling the whole area...

Haven't bisected it yet though...
