### ISSUE TITLE
Beta 0.9.7 - Favourites/Playlists fail to sync if they contain non-music media (reproducible)

### ISSUE THREAD

**Issue by othyn** [jmshrv/finamp#748]
I think this issue is related and expands on to #746. If a playlist contains any other media, e.g. a TV Episode, Finamp will break saying it cannot sync. The Playlist UI will also break, not displaying anything after the broken list entry. It will turn grey and not display any other tracks post the broken list entry.

You can reproduce the issue by adding a non-music media type to the playlist and sync'ing it with Finamp, e.g. a TV episode or movie/film.

I don't use mixed media playlists, actually it was a nice flag that I'd accidentally put an episode of The Simpsons in a music playlist, however I feel Finamp shouldn't break, it should just ignore media types that it cannot/should not handle instead of throwing an exception.

I have a feeling this is why the favourites sync is breaking on Beta 0.9.7, as outlined in #746. As I also have a lot of media favourited that aren't just songs, and it would make sense given the issues with playlists, favourites may be experiencing the same bug if the sync mechanism is the same implementation. Just a gut feeling, I could and are probably wrong on that!

The main error log lines (in isolation, full contextual logs attached) being:

```
[SyncBuffer/INFO] 2024-05-24 16:43:12.674035: Error downloading children for finampCollection Favorites: Null check operator used on a null value
```

and 

```
[Flutter/SEVERE] 2024-05-24 16:54:35.872718: Unknown baseItemDto type Episode
```

I've attached the relevant parts of the log in text form ([finamp_log.txt](https://github.com/jmshrv/finamp/files/15437103/finamp_log.txt)) and the location in the app logs, and here is a screenshot showing the UI breaking:

![IMG_13E954565FF1-1](https://github.com/jmshrv/finamp/assets/7256684/ad6a80fc-ce7c-41e2-b841-4e0bc24123a2)
![IMG_3247](https://github.com/jmshrv/finamp/assets/7256684/4cce3ef9-5896-4023-9737-06f5195da93f)

**Comment by Chaphasilor** [comment]
Thanks for the detailed report! We're already working on a fix, it will be included in the next update.  
We will probably resort to mostly ignoring "unknown" types, although basic audio playback might be possible for video files :)
