### ISSUE TITLE
Beta 0.9.7 - Color Separation Issue During Device Rotation

### ISSUE THREAD

**Issue by Kotsasmin** [jmshrv/finamp#750]
Description:

When I play a track on Finamp, everything seems alright until I rotate the device from horizontal (landscape) to vertical (portrait) or vice versa. It appears that the two main colors used to create a blurry fading effect of the album cover get separated.

For example, if the colors are red and green, when I rotate my device to a new orientation, the screen splits in half with each color occupying a separate half.

Steps to Reproduce:

1. Install and open Finamp (brand new download).
2. Open a track to play.
3. Click on the mini player
4. Rotate the device from landscape to portrait or portrait to landscape.
5. Observe the color separation issue.

Expected Behavior:

The blurry fading effect of the album cover should smoothly transition between orientations without the colors splitting or separating.

Actual Behavior:

Upon rotation, the screen splits in half with each main color occupying a separate half.

Device Information:

Device Model: Xiaomi Poco X3 NFC
Operating System: MIUI Global 12.0.9 Stable
App Version: Beta 0.9.7

**Comment by Chaphasilor** [comment]
Oh, that bug was fixed in a previous version, but seems to have re-appeared due to recent changes!

@Komodo5197 do you remember how you fixed it last time? It probably got overwritten when merging the desktop PR...

**Comment by Komodo5197** [comment]
This is another symptom of the same cachepaint sizing bug seen on the themed menus, and the fix should cover this too.
