### ISSUE TITLE
Strange Silver Rectangles Appear over The progress bar.

### ISSUE THREAD

**Issue by Blixster77** [jmshrv/finamp#751]
![Screenshot_20240525-072740.png](https://github.com/jmshrv/finamp/assets/146099279/63774594-565c-4487-90b7-3b8ff9b06a23)

This happens to the album cover sometimes as well, I'm not sure what causes it.

**Comment by Blixster77** [comment]
![Screenshot_20240525-073139.png](https://github.com/jmshrv/finamp/assets/146099279/5e439c45-1c4c-4847-803b-1e48ae41dc98)

Just got a screenshot of it happening to the album cover, this is on the redesign beta I'm pretty sure (IDK, my Google play is quite glitchy and "Beta Versions" almost never actually install)

**Comment by Chaphasilor** [comment]
I think this is related to a failed network request, at least in the case of the player screen. I already fixed that bug for the next update.

The error on the album cover is something I haven't encountered before, but probably similar. Could you attach some logs to help diagnose where exactly it's coming from?

**Comment by Chaphasilor** [comment]
Ahh nevermind, the issue on the album cover should be the same problem. You can probably get rid of the issue until the next update by disabling "Show artist images with artist name" in Layout & Theme settings :)

**Comment by Blixster77** [comment]
Thank you!
