### ISSUE TITLE
Beta 0.9.7 - Offline Mode Favorites Filter Playing Incorrect Tracks

### ISSUE THREAD

**Issue by Nerokor** [jmshrv/finamp#752]
When offline mode is active and there's a mix of favorited and unfavorited tracks downloaded, selecting a track with the favorites filter active sometimes results in playing a different track. It seems the player chooses the track displayed in the same position in the unfiltered track list, which may or may not be the intended track depending on their positions.

**Comment by Chaphasilor** [comment]
Thanks for letting me know. I'm not surprised this broke ^^

Will be fixed with the next update!
