### ISSUE TITLE
[Feature Request][Redesign] Lyrics - Display customization options

### ISSUE THREAD

**Issue by endervad** [jmshrv/finamp#753]
Self-explanatory. In particular, I would personally prefer to: 
1. Remove album artwork
2. Remove all timestamps
3. Center the lyrics
4. Decrease font size

Since in Settings > Layout & Theme there's a "Customization" menu now, I assume some options are probably already planned to be added there, but I decided to create an issue anyway. Besides, maybe other people could drop some more ideas about what could be customizable :)

**Comment by Chaphasilor** [comment]
I've added the timestamps and centering options for the next update. The other two will probably follow later :)

**Comment by Chaphasilor** [comment]
I've implemented the remaining two settings (font size and album artwork) for the 0.9.10 release :)
