### ISSUE TITLE
[Bug] Beta 0.9.7 - iOS Search broken / Keyboard not showing up until app restart

### ISSUE THREAD

**Issue by lukaslindnermusic** [jmshrv/finamp#759]
First: I am sorry, I don't have any clue on the exact steps it takes to reproduce this issue.
This just happened twice to me while using the app and both times I did not pay proper attention before the bug occurred.
But maybe some of you can find out why this happens either way.

With the bug, the search field on the top is active, but the iOS keys are not showing up for input so I basically can't type anything (tapping inside the input field does not work).
And this issue stays until I completely close and re-start the app.
Switching the tabs while the bug is "active" does not solve it.
The back-button on the left side of the search field works, but when I open up the search again, the input field comes back but the keyboard itself still won't show up. 

Sorry that I can't give a better description to reproduce this, but I will pay attention and hopefully can comment here again with more details when the bug happens to me again.
In the meantime, maybe someone of you has experienced the same or does already know what it could be. Thanks!

iPhone 14 Pro
iOS 17.5.1
Finamp Beta 0.9.7
Jellyfin Server 10.9.3 (Docker on Synology DS920+)

[Edit: Fixed typos and added device infos]

**Comment by Chaphasilor** [comment]
Others have also reported this issue on iOS. Probably a bug in the Flutter framework itself, maybe it resolves itself with the next update...

**Comment by MrTalala** [comment]
I am having the same issue. Restarting the app didn't fix it, but downgrading to 0.9.6 and back to 0.9.7 seemed to fix it.

**Comment by Chaphasilor** [comment]
I believe this issue was fixed with 0.9.8, so I'm closing this for now...
