### ISSUE TITLE
Pause not working with google pixel buds pro

### ISSUE THREAD

**Issue by luvienm** [jmshrv/finamp#762]
When the pixel bud is pressed to pause the track, it beeps and then continues playing.

Also google assistant is unable to skip to the next track when told to. Same thing, it just stops for a second and then continues playing the same track.

**Comment by Chaphasilor** [comment]
That is very strange. Which version are you using? Does it work in other apps and the official Jellyfin app?

Also, have you tried restarting your phone? We had a few similaf bug reports that resolved after a restart...

**Comment by luvienm** [comment]
That was it, it just needed a reboot. It's a pixel 7 pro and finamp beta
version is: 0.9.7

Amazing work you are doing btw. Thanks.

Hoping for cast support in the future.

**Comment by Chaphasilor** [comment]
Glad to hear that!

Thanks for the kind word <3  
I'm sure we'll get to cast eventually!
