### ISSUE TITLE
[Bug][Redesign] - Listening to whole artist does not allow shuffling after the fact

### ISSUE THREAD

**Issue by Tiefseetauchner** [jmshrv/finamp#767]
Little bug (that's probably my fault)

1. Start playing an Artist
2. Press shuffle

It doesn't shuffle the queue, it continues playing in order

Posting this so I don't forgor

**Comment by Chaphasilor** [comment]
Can't repro on my phone. Can you share a video?

**Comment by Tiefseetauchner** [comment]
Only tried it on Desktop, my bad should've mentioned

[Screencast_20240606_112136.webm](https://github.com/jmshrv/finamp/assets/48085877/4440a87b-31ec-418b-b0f9-c4eea1c507cb)

**Comment by Chaphasilor** [comment]
Yeah that's an issue with just_audio_media_kit in general. Should be unrelated to artist playback.

**Comment by Chaphasilor** [comment]
I'll close this because I think there are similar issues that have been reported elsewhere :)
