### ISSUE TITLE
[Bug] Seek bar does not visually reset to 0 if you skip tracks while paused

### ISSUE THREAD

**Issue by drazil100** [jmshrv/finamp#77]
Title:
![IMG_0338](https://user-images.githubusercontent.com/17794391/125905776-ab95f4fc-4a8c-4fb8-894f-28d51a5cac39.PNG)

**Comment by UnicornsOnLSD** [comment]
That should be an easy fix :)

**Comment by rom4nik** [comment]
Can't reproduce this as of 1ea614d9d55f7408ae14518351b055000d0c91d5, slider and position text go to 0 after skipping.

**Comment by Chaphasilor** [comment]
@drazil100 is this still happening? :)

**Comment by jmshrv** [comment]
Can't reproduce, closing
