### ISSUE TITLE
Playback controls disappear, replaced by grey box

### ISSUE THREAD

**Issue by solidsnake1298** [jmshrv/finamp#770]
I have not been able to reproduce this issue since the first and only occurrence.  But when I pressed next to skip a song the controls disappeared and were replaced by a grey box.  I pressed back to go to the main interface and then maximized the current song and the controls reappeared.  I was able to get a screenshot of the controls disappearing.

![Screenshot_20240605-075530](https://github.com/jmshrv/finamp/assets/137357145/a4a4cb23-a0ce-4497-9e52-50940df0d7ae)

**Comment by Chaphasilor** [comment]
This was probably due to an exception thrown due to a failed network request when rendering the artist image, and should be fixed with the next update :)
