### ISSUE TITLE
Broken interface design 0.9.8

### ISSUE THREAD

**Issue by pepebarrascout** [jmshrv/finamp#775]
Version **0.9.8 on Google Play** has broken the app stylesheet. It is almost impossible to use it.

In the images, the light theme and the dark theme.

<img src="https://github.com/jmshrv/finamp/assets/3188933/14c74862-eac4-426b-8bf4-ae2c1c6b773f" width="300">
<img src="https://github.com/jmshrv/finamp/assets/3188933/816a7592-5840-4093-be11-a615bcb55593" width="300">

**Comment by Chaphasilor** [comment]
Which phone and Android version is that? What are your settings (especially "Layout & Theme"?

Does this happen with every song, or only some? If only some, do the cover images have a special file type?

Can you share logs?

**Comment by Merconix** [comment]
Just tested the latest Google Play beta build on a Galaxy Z Flip 5 running Android 14 and the issue wasn't present.

See below for screenshot, including layout & theme settings - maybe try replicating them on the problematic device and see if the issue persists?
All of my cover songs are embedded into the files themselves (both MP3 & FLAC) so handled in the default Jellyfin manner.

![Screenshot_20240613_120359](https://github.com/jmshrv/finamp/assets/41351832/d476e26f-f358-4904-9580-e062bec03c22)
![Screenshot_20240613_120300](https://github.com/jmshrv/finamp/assets/41351832/c4332f68-ebfa-4544-a0dc-30a888e89cb6)

**Comment by pepebarrascout** [comment]
> Which phone and Android version is that? What are your settings (especially "Layout & Theme")?
> 
> Does this happen with every song, or only some? If only some, do the cover images have a special file type?
> 
> Can you share logs?

Hi @Chaphasilor thanks for your work

Mi phone: **Honor 7 RKY-L03** with **Android 12**
Thumbnails: **embedded** in audio file aac in m4a (In 0.9.7 works fine)
The entire interface fails.
Layout & Theme: Same as the image above of @Merconix 

Google Play version 0.9.8 and Finamp-0.9.8-beta-universal.apk update and fresh install fails (In phone: I deleted cache and data)

Images: Login and logs sections

<img src="https://github.com/jmshrv/finamp/assets/3188933/a3935050-0042-4fb9-a093-bc71b37f8c51" width="300">
<img src="https://github.com/jmshrv/finamp/assets/3188933/bac5ca2c-a339-49fd-8bb2-94455c177bad" width="300">

Logs:

```
sudo adb shell
logcat | grep finamp
```

Launched Finamp 0.9.8 beta and the terminal wrote out this:

> 06-14 09:20:16.266   511   528 E vold    : /data/media/0/Android/obb/com.unicornsonlsd.finamp not exist, return directly.
> 
> 06-14 09:20:17.320  1223  1536 E VerityUtils: Failed to measure fs-verity, errno 1: /data/app/~~OUuq8ER9WWgsoq9PHYK0-A==/com.unicornsonlsd.finamp--PdJC1wbJDqtpAle9jk8XA==/base.apk
> 
> 06-14 09:20:17.696  1223  1536 E VerityUtils: Failed to measure fs-verity, errno 1: /data/app/~~OUuq8ER9WWgsoq9PHYK0-A==/com.unicornsonlsd.finamp--PdJC1wbJDqtpAle9jk8XA==/base.apk
> 
> 06-14 09:30:21.004  1053  3503 E dubaid  : [DubaiStorage.cpp] QueryEntries# Failed to query entries: SELECT name, SUM(usage), SUM(energy) FROM detailed_applications_gpu WHERE name IN ('com.google.android.youtube','com.google.android.googlequicksearchbox','com.google.android.apps.googleassistant','com.touchtype.swiftkey','com.google.android.apps.messaging','com.hihonor.android.thememanager','com.android.vending','com.hihonor.HnMultiScreenShot','com.android.stk','com.google.android.deskclock','com.google.android.gm','com.google.android.dialer','com.hihonor.calculator','com.unicornsonlsd.finamp','com.google.android.apps.maps','com.google.android.contacts','com.android.chrome','com.hihonor.ouc','com.google.android.calendar','com.spotify.music','com.hihonor.filemanager','com.google.android.documentsui','com.hihonor.camera','com.facebook.orca','com.hihonor.photos','com.cxinventor.file.explorer','com.android.settings','com.hihonor.android.fmradio','com.hihonor.soundrecorder','com.google.android.keep','com.hihonor.systemmanager','com.xiaomi.hm.health','com.h
> 
> 06-14 09:30:21.018  1053  3503 E dubaid  : [DubaiStorage.cpp] QueryEntries# Failed to query entries: SELECT name, SUM(active_time), SUM(idle_time), SUM(energy) FROM detailed_applications_tp WHERE name IN ('com.google.android.youtube','com.google.android.googlequicksearchbox','com.google.android.apps.googleassistant','com.touchtype.swiftkey','com.google.android.apps.messaging','com.hihonor.android.thememanager','com.android.vending','com.hihonor.HnMultiScreenShot','com.android.stk','com.google.android.deskclock','com.google.android.gm','com.google.android.dialer','com.hihonor.calculator','com.unicornsonlsd.finamp','com.google.android.apps.maps','com.google.android.contacts','com.android.chrome','com.hihonor.ouc','com.google.android.calendar','com.spotify.music','com.hihonor.filemanager','com.google.android.documentsui','com.hihonor.camera','com.facebook.orca','com.hihonor.photos','com.cxinventor.file.explorer','com.android.settings','com.hihonor.android.fmradio','com.hihonor.soundrecorder','com.google.android.keep','com.hihonor.systemmanager','com.xia
>

**Comment by Chaphasilor** [comment]
Thanks for the info. You mentioned stylesheets in your original comment, do you have made any theme or color modifications on your phone that could be causing this?

**Comment by pepebarrascout** [comment]
> Thanks for the info. You mentioned stylesheets in your original comment, do you have made any theme or color modifications on your phone that could be causing this?

I don't know if the exact term is style sheet, I'm a graphic/web designer and it's the closest thing to what I think is happening.

I haven't modified anything on the phone. Only on Google Play, click update application.

I went back to 0.9.7 and it works perfectly.

On the Amazon Fire tablet, version 0.9.8 works well

**Comment by jmshrv** [comment]
This may be caused by https://github.com/jmshrv/finamp/commit/7ec2ebae964e7718eea9924fbe313e92a5f19395 - Impeller isn't stable on Android just yet, especially since some Android phones can have buggy graphics drivers. I've attached an APK built without Impeller. Could you test this @pepebarrascout /others who are affected by this?

[app-arm64-v8a-release.apk.zip](https://github.com/user-attachments/files/15847739/app-arm64-v8a-release.apk.zip)

**Comment by pepebarrascout** [comment]
> This may be caused by [7ec2eba](https://github.com/jmshrv/finamp/commit/7ec2ebae964e7718eea9924fbe313e92a5f19395) - Impeller isn't stable on Android just yet, especially since some Android phones can have buggy graphics drivers. I've attached an APK built without Impeller. Could you test this @pepebarrascout /others who are affected by this?
> 
> [app-arm64-v8a-release.apk.zip](https://github.com/user-attachments/files/15847739/app-arm64-v8a-release.apk.zip)

Hi @jmshrv thanks for the app

Apparently, that's the problem.
Now it works perfectly, thanks.
_I still can't see the Favorite/Like Button in Media Notification_ but that's not important to me, maybe in the next update.

<img src="https://github.com/jmshrv/finamp/assets/3188933/e0228d0e-ffd1-4368-a59d-600b8566af61" width="300">
<img src="https://github.com/jmshrv/finamp/assets/3188933/f0e54d37-ab39-4397-a5f6-bfa87ba9520f" width="300">

**Comment by jmshrv** [comment]
Thanks for confirming, will make a hotfix Android release tomorrow :)

**Comment by Chaphasilor** [comment]
@pepebarrascout we got a user report that this is happening again on 0.9.13. Does it also happen to you?

**Comment by pepebarrascout** [comment]
@Chaphasilor In version 0.9.13 it works fine. I first installed the app sent me with version 0.9.8 https://github.com/user-attachments/files/15847739/app-arm64-v8a-release.apk.zip and then updated from Google Play to 0.9.13
