### ISSUE TITLE
Beta: Error message on app startup

### ISSUE THREAD

**Issue by G2-Games** [jmshrv/finamp#778]
After I start the application, I get the following error message every time. This issue has occurred since `0.9.7-beta`. 

```
[GlobalSnackbar/WARNING] 2024-06-14 06:10:10.853363: Displaying error: Could not fetch the response for GET BASEURL/Users/b28e34eb92e243b9b2d12a84895b82a1/Items?IncludeItemTypes=Audio&ParentId=464403737a9980e64b5ef6a80bae2f47&Recursive=true&SortBy=ParentIndexNumber%2CIndexNumber%2CSortName&Fields=ChildCount%2CDateCreated%2CDateLastMediaAdded%2CEtag%2CGenres%2CIndexNumber%2CParentId%2CProviderIds%2CTags%2CalbumPrimaryImageTag%2CparentPrimaryImageItemId%2CsongCount%2CMediaSources%2CMediaStreams%2CSortName. Status code: 500, error: Error processing request.

```

**Comment by Chaphasilor** [comment]
Could you try logging out and back in again? It might be that some ID on your Jellyfin server changed, but is still stored in Finamp...

If that doesn't help, maybe running a downloads repair after updating to 0.9.8 might help.  
After the update, go to the downloads screen and click the middle icon at the top right.

**Comment by G2-Games** [comment]
Repairing the downloads worked, sorry for the issue! I do think it would be a good idea to indicate that to the user if possible however. 

This app is amazing, I look forward to trying android auto soon.
