### ISSUE TITLE
[Feature Request] Add quick connect (or OIDC) sign in option

### ISSUE THREAD

**Issue by Tygo-van-den-Hurk** [jmshrv/finamp#779]
Hey! I just installed the app from the apple app store, and when I tried to log in it wasn't possible as I use Oauth/OIDC to manage my users instead of the build in login manager.

Since the app log in screen does not have a button to log in with Oauth (as this is an extention), nor the option to log into the app using Quick Connect. I was basically unable to log in.

I was wondering if it'd be possible to add an option to connect using Quick Connect for those of us not using the build in user management. I don't think it's possible to add a button for OIDC since that's an extention.

**Comment by Chaphasilor** [comment]
You can try the beta through Testflight, link it on the releases page.It already has support for Quick Connect!

**Comment by Tygo-van-den-Hurk** [comment]
Oh cool! I’ll download it real quick. When do you expect to release that build to the public?

**Comment by Chaphasilor** [comment]
When it's ready :P

I know it sounds like a generic response, but I don't want to promote it to stable unless the entire redesign is finished. I do encourage everyone who is willing to use a beta version to switch to that though, while parts of it might break from time to time, it should work much better than the stable version.

I can't really give you a time frame, but I really don't expect it to he finished before the end of the year, unless we get a bunch of new contributors...

**Comment by Tygo-van-den-Hurk** [comment]
No that's totally fair! I'm personally grateful this exists at all. I highly doubt that you'll get **a bunch** of new contributors out of no where as that just doesn't happen out of no where. I would contribute directly if I knew dart, but unfortunately, I haven't had the change to learn anything about it yet.

However I saw that your application isn't available on [NixOS](https://search.nixos.org/packages?channel=24.05&from=0&size=50&sort=relevance&type=packages&query=finamp). I can try and see if I can contribute by adding it to the Nix Packages! That is something that I do know how to do! More exposure never hurt nobody. I've got exams soon, but after that I'd be totally down to try and get it packaged up! 

Maybe some people of there see it and can come and help!

**Comment by Chaphasilor** [comment]
Someone already set up a profile (or whatever it's called) for a Finamp development setup somewhere, if you can't find it I can try to get you a link.  
We also have a Arch packages (src and bin) and a flatpak already, you can definitely take a look at how they are doing it, and adapt it to Nix.  
Let me know if you have any questions.

Regarding Dart and contributing directly, just give it a try if you know how to program! I originally just created design mockups to kick-start the redesign/beta, but when no-one wanted to implement it I did it myself ^^ I'm not a Dart or Flutter pro either.

But if you don't have the time for that I can also understand that :)

**Comment by BloodyIron** [comment]
Yeah I tried the quick connect thing a few times recently and it's pretty dang tasty! Even looks to respect my privacy-by-design architecting of my own ecosystem ;) Unlike Plex. So... yay! \o/

**Comment by Chaphasilor** [comment]
Closing since this is implemented in the beta :)
