### ISSUE TITLE
[Bug] In app play controls disabled after backgrounding app with now playing / play controls screen open

### ISSUE THREAD

**Issue by drazil100** [jmshrv/finamp#78]
On iOS at least (not sure about android) if you put the app in the background for even a second while the Now Playing / Play Controls screen is up the shuffle, previous track, play/pause, next track, and loop buttons all get disabled. The only things you can interact with are the play queue button, the seek bar, and the close Now Play / Play Controls screen arrow. If you interact with the seek bar or minimize the play controls screen and bring it back up everything works just fine.

**Comment by UnicornsOnLSD** [comment]
I've known about this for a while, it's caused by the buttons not connecting to the audio service. They should reconnect when they're disconnected, but they don't sometimes. I'll look into it at some point.

**Comment by Chaphasilor** [comment]
Is this still happening?
