### ISSUE TITLE
Support word-by-word time synced lyrics

### ISSUE THREAD

**Issue by Maxr1998** [jmshrv/finamp#780]
There LRC format has [an extension](https://en.wikipedia.org/wiki/LRC_%28file_format%29#Extensions) that supports syncing lyrics word-by-word. Jellyfin doesn't explicitly support this, but instead simply forwards these timing tags as a part of the lyrics line and expects the client to handle them (see [here](https://github.com/jellyfin/jellyfin/pull/8381#issuecomment-1242758063)).

Currently, Finamp simply displays these word time tags:
![Screenshot_20240615_022625.png](https://github.com/jmshrv/finamp/assets/5903699/565c37a3-c671-42f4-9092-e88bd77302dc)

Ideally, it should fully support them, but at first simply hiding them would be a good start.

**Comment by Chaphasilor** [comment]
The issue you linked is a bit outdated. The most up-to-date discussion I'm aware of is https://github.com/karaoke-dev/LrcParser/issues/40  
So I consider word-by-word lyrics to be unsupported by Jellyfin at the moment, and would like to avoid adding client-side parsing for this.  
Maybe back up your current lyrics (e.g. by renaming to `.lrc.bak`) and then use a script to strip out the timestamps in the actual lyrics file?

**Comment by Maxr1998** [comment]
> So I consider word-by-word lyrics to be unsupported by Jellyfin at the moment, and would like to avoid adding client-side parsing for this.

I see, so we're basically waiting for the library to be fixed and then Jellyfin to offer an additional API with word-by-word support?
 
> Maybe back up your current lyrics (e.g. by renaming to `.lrc.bak`) and then use a script to strip out the timestamps in the actual lyrics file?

Currently it's only a single file so not a real issue, I'd just love to have it supported so that I can grab more of these types of lyrics. But for now I'll wait.

**Comment by andy840119** [comment]
[LrcParser](https://www.nuget.org/packages/LrcParser) package is upload and this update is focus on parsing the time-tag inside the lyric (see A2 extension in the wiki: https://en.wikipedia.org/wiki/LRC_(file_format))
This issue might resolved after Jellyfin upgrade the package.

**Comment by Chaphasilor** [comment]
Since this was added in Jellyfin 10.10, I'll consider this resolved. Updating downloaded lyrics isn't possible without re-downloading at the moment, but that's a separate issue.
