### ISSUE TITLE
Screen does not stay on

### ISSUE THREAD

**Issue by texneus** [jmshrv/finamp#781]
0.9.7 beta - The screen always seems to timeout on me.  There are instances when I want it to stay on, such as when I'm listening at my desk so I can see what's playing and to use the transport controls.  How about a user toggle to keep the screen on/prevent the screen from sleeping while Finamp is playing?  I don't see a way to keep it alive (if there is an option for this, I can't find it).

**Comment by Chaphasilor** [comment]
Hmm, I've simply used an Android quick settings tile that prevents the screen from sleeping. Didn't ever think about adding that to Finamp, since the main content isn't visual. It's probably doable, but I'm not sure. Which platform are you on?

Also, where exactly would you want the screen to stay on? Everywhere, or just in specific scenarios?

**Comment by texneus** [comment]
I'm on Android 12 (I think).  Quick settings in Android 12 became a mess.  There are way too many options now so 99% of them are so buried it's easier to go through system settings.  I never thought of that route, but I don't seem to have a quick setting to keep the screen on anyhow.  Odd.

In anycase, if it just stays on when playing and the "now playing" screen is showing, that would satisfy me.  If doable - I think it would be wise if when playback stops or if playing AND the phone switches to battery the screen sleeps as normal.

**Comment by texneus** [comment]
Sorry, been out for a while.  Yes, I think those conditions should cover it.

**Comment by Sp4rky001** [comment]
> I use an app aptly named "Keep screen on"/which changes the screen timeout using a quick settings toggle.
> 
> Okay, so conditions would be:
> 
> * on player screen
> * playing music
> * charging
> 
> ?

Taking some of your suggestions into account, I created a solution that also includes my own needs.  This is my first attempt at Flutter, so hopefully, my pull request is accepted.

Under "Interactions" two options are added:
 - Keep Screen On: Main Setting -- Disabled, while music is playing, or while lyrics are showing.  For my own use, I only want the screen to stay on while lyrics are showing.
 - Keep Screen On: Only while plugged In -- Ignore the main setting if the device is not plugged in.

**Comment by Chaphasilor** [comment]
This has been fixed for a while now thanks to @Sp4rky001 :)
