### ISSUE TITLE
Update version 0.9.7 to 0.9.8 does not work on KDE desktop

### ISSUE THREAD

**Issue by pepebarrascout** [jmshrv/finamp#787]
In Kubuntu 24.04, **version 0.9.8** of Finamp for desktop does not work.

Installation method: flatpak install com.unicornsonlsd.finamp
Update method: flatpak update
Version 0.9.7 works correctly.

<img src="https://github.com/jmshrv/finamp/assets/3188933/32e69933-138a-4a81-b69d-f1d7f937a3cc" width="300">

**Flatpak info:**
>flatpak info com.unicornsonlsd.finamp

Finamp - Open source Jellyfin music player

          ID: com.unicornsonlsd.finamp
  Referencia: app/com.unicornsonlsd.finamp/x86_64/stable
Arquitectura: x86_64
        Rama: stable
     Versión: 0.9.8-beta
    Licencia: MPL-2.0
      Origen: flathub
   Colección: org.flathub.Stable
 Instalación: system
   Instalada: 95.1 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: cf019438f82affa27630d7800211f433640b30e3a7e7f6351616229bdc3c8436
       Padre: eaf2a060786b54a956d8f3abbf40e8ad91993db32b12d627a69a7e8d81006150
      Asunto: 0.9.8 (db451b46)
       Fecha: 2024-06-17 11:05:24 +0000

**Logs:**

> [Startup/INFO] 2024-06-20 13:52:48.005123: App starting, logging initialized.
[ErrorApp/SEVERE] 2024-06-20 13:52:48.291836: type 'bool' is not a subtype of type 'LyricsAlignment' in type cast
		# 0      FinampSettingsAdapter.read (package:finamp/models/finamp_models.g.dart:173)
		# 1      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:328)
		# 2      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:276)
		# 3      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21)
		# 4      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42)
		<asynchronous suspension>
		# 5      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86)
		<asynchronous suspension>
		# 6      HiveImpl._openBox (package:hive/src/hive_impl.dart:111)
		<asynchronous suspension>
		# 7      HiveImpl.openBox (package:hive/src/hive_impl.dart:142)
		<asynchronous suspension>
		# 8      Future.wait.<anonymous closure> (dart:async/future.dart:524)
		<asynchronous suspension>
		# 9      setupHive (package:finamp/main.dart:221)
		<asynchronous suspension>
		# 10     main (package:finamp/main.dart:80)
		<asynchronous suspension>
		
**To make it work:**
- Uninstall completely and delete all data:
>  flatpak uninstall -y --delete-data com.unicornsonlsd.finamp
- Reinstall:
>  flatpak install com.unicornsonlsd.finamp

It's inconvenient this way, you lose all your custom settings. Since it is a beta version, I am reporting it so that it is not missing from the stable version.

<img src="https://github.com/jmshrv/finamp/assets/3188933/580fc91f-99b6-4d5d-a4ec-bc11af904545" width="300">

Off topic:
How can I collaborate to translate into Spanish?

**Comment by Chaphasilor** [comment]
That was probably an issue that came from our testing to make the flatpak work. The 0.9.7 version wasn't truly 0.9.7, but some state between 0.9.7 and 0.9.8. Sorry about that, but keep in mind that the desktop version hasn't been officially released yet, so it's still in alpha.  
This shouldn't happen anymore in future updates.

Regarding translation: at the moment the text in the beta can't be translated yet, only the text that's in the stable/old version. You can find the link to the weblate project in the readme :)

**Comment by Allexio** [comment]
Hi there, I don't get it, what is the solution to this problem?
I am having it too and I am on the latest flathub build.
Why is this marked as completed?

**Comment by Chaphasilor** [comment]
@Allexio you need to clear all of the app data. Uninstalling might do that, if not you'll need to find out where the app data for the flatpak is stored on your system and delete all Finamp-related data :)

**Comment by pepebarrascout** [comment]
> Hi there, I don't get it, what is the solution to this problem? Do I actually have to uninstall reinstall? I am having it too and I am on the latest flathub build.

Hi @Allexio 

**_To make it work:_**

**Uninstall completely and delete all data:**
flatpak uninstall -y --delete-data com.unicornsonlsd.finamp

**Reinstall:**
flatpak install com.unicornsonlsd.finamp
