### ISSUE TITLE
Add Resume for Album

### ISSUE THREAD

**Issue by ShaikaJar** [jmshrv/finamp#788]
Resume last Playback-State of an Album.
This would be helpfull for Audiobooks and Podcast
The most recently listened-to Item of an Album can already be retrieved from the default-api.
Does someone now of away to retrieve the last position for that item?

**Comment by Chaphasilor** [comment]
I assume you're already using the beta version? If so, you could use the "Restore Now Playing" section in the menu / side drawer to restore a recent queue.
