### ISSUE TITLE
Thoughts on the beta version

### ISSUE THREAD

**Issue by mcgratta144** [jmshrv/finamp#790]
Loving the beta version so far. It looks much more sleek than the one in the Apple Store.

**Comment by Chaphasilor** [comment]
Glad you like it! 😁  
There's more to come :)

We also have a general discussion about the beta that's better-suited for this kind of feedback: https://github.com/jmshrv/finamp/discussions/603

If you have a specific problem or request, you can still create an issue for that of course!
