### ISSUE TITLE
[bug] ios Unable to connect to jellyfin server

### ISSUE THREAD

**Issue by liuwl-j** [jmshrv/finamp#794]
finamp and jellyfin(10.9.6) are both new installations

[MusicPlayerBackgroundTask/INFO] 2024-06-24 08:47:26.001099: Starting audio service

null
LOGIN BODY

⑥
[Chopper]
2024-06-24 08:48:19.885187
LOGIN BODY
訊息
--> POST http://192.168.1.254:8096/Users/
AuthenticateByName
Content-Type: application/json; charset=utf-8 Authorization: MediaBrowser Client="Finamp", Device="iPhone", Deviceld="* ", Version="0.6.22" content-length: 32
{"Username":"*","Pw": "*"}
--> END POST

**Comment by Chaphasilor** [comment]
From the logs it seems like you didn't specify a username or password, but you probably did, right?  
Which version of Finamp are you using?

**Comment by leoreinmann** [comment]
Hello, i also have this bug. I cannot connect to the Finamp app with the same error log as posted, only that username and password is not empty.
I run Finamp on the most recent version (0.6.22) available for me.

**Comment by Chaphasilor** [comment]
Which server version are you using? Is there anything special with you installation? Special characters?

There's also a beta version available through TestFlight, you could give that a try.

**Comment by leoreinmann** [comment]
I am on the server version 10.8.9. The installation is pretty standard, it is running on Docker. There are also no special characters.
But Swiftfin for example is working flawlessly, so I think there is an issue with the particular version Finamp is currently released on the App Store.

I‘ve never participated in TestFlight but I‘ll give it a try

**Comment by jmshrv** [comment]
I'd recommend upgrading to 10.9 if you can - off the top of my head the stable branch *shouldn't* have any issues, but either way, Finamp officially focuses on the latest stable version 

And I'd recommend checking out the beta :D

**Comment by Chaphasilor** [comment]
Is there a particular reason why you're not on 10.8.13 instead of 10.8.9? Finamp should still be compatible to that, even if the official clients (e.g. Android TV) dropped support already. I was running a 10.8.13 server until recently myself.

But 10.8.9 isn't even the latest patch release, so you should definitely upgrade!

**Comment by leoreinmann** [comment]
I updated the version to 10.9.11, but the Swiftfin app still shows 10.8.9, I guess my prior post may had false information and the server may ran on a more recent version.
Anyway, updating didn’t fix the issue, but I now tried the beta version with TestFlight and it worked immediately, discovered even my server and everything! Thanks for the help!

**Comment by jmshrv** [comment]
Awesome, the login flow/server discovery was recreated for the beta, nice to see that it's working :)
