### ISSUE TITLE
Feedback, Beta 0.9.8

### ISSUE THREAD

**Issue by BloodyIron** [jmshrv/finamp#797]
(this is in the Beta v0.9.8 Android client)

I'm playing an album, I have it set to loop the whole album and shuffle is on.

I switch to another album, and suddenly shuffle is now off. So I have to turn it back on.

Can we please have it so the shuffle setting is retained when switching albums or going to individual songs, etc?

**Comment by Chaphasilor** [comment]
Closing as a duplicate of #818 :)

**Comment by BloodyIron** [comment]
Wouldn't that be a duplicate of this, since this was reported _BEFORE_ #818? I'd say close #818 as duplicate of this... @Chaphasilor

**Comment by Chaphasilor** [comment]
Order doesn't matter, and the other issur had a more descriptive title and more discussion going on :)
