### ISSUE TITLE
Beta 0.9.8 (Linux): Flicker when opening hamburger menu

### ISSUE THREAD

**Issue by DSeeLP** [jmshrv/finamp#801]
It flickers when opening the hamburger menu when the miniplayer is there. The flicker doesn't occur when in splitscreen mode.
It only appears when running the app in release mode.

https://github.com/jmshrv/finamp/assets/46624152/f78cfa25-65ec-430f-801a-e0ce5d468438

I am currently trying to package the beta for NixOS.
I tested this on NixOS with my package and the repo inside a devshell to provide the necessary libraries.
It also happens with the provided binaries on Ubuntu 24.04.

**Comment by Chaphasilor** [comment]
Hi, that's a known issue with Flutter itself (https://github.com/flutter/flutter/issue/146807) and has already been fixed upstream (https://github.com/flutter/engine/pull/53103).  
So it should be fixed in an upcoming Flutter version :)

**Comment by Chaphasilor** [comment]
Btw, there's already an m4 desktop file here in the repo, but it seems like you're creating one from scratch during build. Is there a reason for that?  
I'd like to keep things (names, descriptions, etc.) as consistent as possible by reusing metadata across platforms if possible.

**Comment by DSeeLP** [comment]
I didn't want to introduce a dependency on m4 and most packages don't have their install path hardcoded in the desktop file as it is expected that upon installation the programs would be in `PATH`.

**Comment by DSeeLP** [comment]
I tried it with the latest version and it doesn't flicker anymore :)
