### ISSUE TITLE
m4a offline play on iOS

### ISSUE THREAD

**Issue by JakePi3** [jmshrv/finamp#805]
I've transferred some music that I bought on iTunes to Jellyfin, and I noticed that albums which are in m4a format work fine when streaming but don't work at all when in offline mode.

I tried re-downloading the tracks, logs indicated there was some caching going on, so I re-installed the Finamp app after deleting all its data.

I've reinstalled the app twice, only commonality I found is that mp3 albums work fine, but m4a refuse to work in offline mode.

The songs just never start playing, with no indicator of what is wrong.

**Comment by jmshrv** [comment]
That's very strange, iTunes stuff should work in Apple's own playback system lol

Are you on the latest stable (0.6.23), or the redesign beta (0.9.8)? The download system is way better in the redesign, perhaps the old system is failing to download/not downloading correctly

**Comment by JakePi3** [comment]
I'm on 0.6.22 which is the latest available in App Store

**Comment by jmshrv** [comment]
Give the redesign beta a go, you can get it at https://testflight.apple.com/join/UqHTQTSs :)

**Comment by JakePi3** [comment]
Yes it works.  But I had to delete the albums from my iphone and redownload.. Now they work (in the redesign beta)

**Comment by Chaphasilor** [comment]
Yeah, then it might've been an issue with the codec. I believe iOS requires the downloaded files to have a specific file extension that matches the codec of the file, while Android is more forgiving. The old download system probably didn't use the correct extension, hence the issue you experienced.  
If it's working on the beta version, I'd consider this issue resolved :)

**Comment by chatch520** [comment]
I am having this issue now, I am not using the latest beta but I am on the latest version 0.6.25. Is there anyway to get a fix for this?
