### ISSUE TITLE
Latest beta has animation sync issues

### ISSUE THREAD

**Issue by sn0rl9x** [jmshrv/finamp#806]
Animation issues when scrolling library or menus, nauseating desync. Does not happen on 0.9.7 so downgrading solved the issue temporarily. Happening on Samsung Galaxy S9

**Comment by Chaphasilor** [comment]
Hey, can you share a video that shows what exactly is the issue?/:)

**Comment by sn0rl9x** [comment]
Yes for sure, here's an imgur link with the issue.
https://imgur.com/a/u84GRmb

**Comment by sn0rl9x** [comment]
Fixed in latest beta :)

**Comment by Ambient-Impact** [comment]
Can confirm that this also fixes it for me on Galaxy S10+!
