### ISSUE TITLE
Customize playback meta info

### ISSUE THREAD

**Issue by catfrightening** [jmshrv/finamp#815]
I know some people don't wanna see all this info so I think adding a toggle for it in settings would be nice.

![Screenshot 2024-07-19 at 4 38 25 PM](https://github.com/user-attachments/assets/82e569a6-e671-4000-97df-a455980ba69f)

**Comment by GlazedBelmont** [comment]
I second this, on my display, it's cropped out and just looks out of place 
![image](https://github.com/user-attachments/assets/fce657f4-18cc-477c-a9c2-c4c91a235e04)

**Comment by Ammoton** [comment]
I think this is planned.

**Comment by catfrightening** [comment]
> > I second this, on my display, it's cropped out and just looks out of place
> 
> That shouldn't be happening. What device are you using?
> 
> In general, customizing what is shown and what isn't is definitely planned!

I'm using an iPhone 12 with iOS 18.0 (I think it was also happening before I updated to the iOS 18 beta)

**Comment by GlazedBelmont** [comment]
> > I second this, on my display, it's cropped out and just looks out of place
> 
> That shouldn't be happening. What device are you using?
> 
> In general, customizing what is shown and what isn't is definitely planned!

I'm sorry I missed your reply, I'm using an AYN Odin 2 Mini, it's a 5in 1080p display.

**Comment by Chaphasilor** [comment]
@GlazedBelmont would you mind sharing a screenshot of the whole player screen? I'm trying to figure out why it's getting cropped :)

**Comment by GlazedBelmont** [comment]
> @GlazedBelmont would you mind sharing a screenshot of the whole player screen? I'm trying to figure out why it's getting cropped :)
![Screenshot_20241009-151851](https://github.com/user-attachments/assets/6c68f6e0-7298-42f7-afd3-bea89c991d88)

I haven't used Finamp in quite a bit but it seems you may have fixed it since then, I'm not able to reproduce the cropping.

**Comment by Chaphasilor** [comment]
Thanks, that was quick!  
Ahh, so the cropping happend only in landscape mode?  
The cropping at the side and scrolling is expected for now :)

**Comment by GlazedBelmont** [comment]
Yeah on my end it's fine now, it's perfect in vertical mode

![Screenshot_20241009-152430](https://github.com/user-attachments/assets/85082e35-8301-48ba-a0ca-19266c4f83fd)

**Comment by Chaphasilor** [comment]
Btw, this should be available in 0.9.12! Currently it can only be disabled completely, but the code already supports hiding and reordering info, and we have some design mockups for how the customization settings should look like :)
