### ISSUE TITLE
[0.9.8] [UI] Font color on about-screen not adjusting to dark mode

### ISSUE THREAD

**Issue by joseywoermann** [jmshrv/finamp#816]
On the about-screen in settings, some of the text is always black, regardless of whether the app is running in light- or dark-mode.

### Dark mode:
![Screenshot_20240720_004235](https://github.com/user-attachments/assets/924b3faa-6125-4740-aaee-a3ebc185a2fe)

### Light mode:
![Screenshot_20240720_004243](https://github.com/user-attachments/assets/dd452bb8-ae9c-46ac-894e-6d44fb777ecb)

### Additional information:
- Finamp 0.9.8
- Android 14, OneUI 6.1
- Samsung Galaxy A34 5G

If this issue has been posted before already, I couldn't find it.

**Comment by foss-** [comment]
Resolved in https://github.com/jmshrv/finamp/releases/tag/0.9.9-beta
