### ISSUE TITLE
Playing From Album shows wrong album.

### ISSUE THREAD

**Issue by drazil100** [jmshrv/finamp#837]
So I am on a long roadtrip and queued up several albums by playing from the first album (Blue Rescue Team) and adding the other albums to the queue. It's displaying the name of the first album at the top even though I have moved to the second album. 
![image](https://github.com/user-attachments/assets/a3cffaae-e3e1-4bdc-80a2-a24c82e3263e)

**Comment by Chaphasilor** [comment]
The queue name is based on how you initially started playback, so that's expected. But I agree that we can do better, if you really add an entire album to the queue, it should display the proper source, like it does when you add an album to Next Up.  
Should be easy enough to change!

**Comment by Chaphasilor** [comment]
I believe this should be fixed with the latest update...  
Let me know if not!
