### ISSUE TITLE
Unable to figure out downloading

### ISSUE THREAD

**Issue by FragrantArmpit** [jmshrv/finamp#838]
Perhaps I'm blind but I cannot find any way whatsoever to download the audio. The only thing I found is the "offline mode" which is always empty since I can't figure out how to download.

**Comment by lukaslindnermusic** [comment]
![IMG_5419](https://github.com/user-attachments/assets/f3169813-b37e-49d4-94aa-d0cb48645e8f)
![IMG_5420](https://github.com/user-attachments/assets/e36ba56b-9bbf-4be0-8640-4f98a6a8edfb)

**Comment by FragrantArmpit** [comment]
> ![IMG_5419](https://github.com/user-attachments/assets/f3169813-b37e-49d4-94aa-d0cb48645e8f)
> 
> ![IMG_5420](https://github.com/user-attachments/assets/e36ba56b-9bbf-4be0-8640-4f98a6a8edfb)
> 
> 

I assume this is the beta design. I just use the normal one.

**Comment by jmshrv** [comment]
The download button is still in the top right of albums/playlists in the stable branch. I'd recommend you give the redesign beta a try by the way, there's basically no downside :)

**Comment by FragrantArmpit** [comment]
> The download button is still in the top right of albums/playlists in the stable branch. I'd recommend you give the redesign beta a try by the way, there's basically no downside :)

Oh so that's that it was. I was trying to download from the "songs" tab. Anyway, playlists never worked for me, it says an error occurred or something when I try to create one.

Regarding the beta design: I'm not sure if I want to install some additional app or whatever (I'm in iOS) and if there really is no downside then you should probably just release it.

**Comment by lukaslindnermusic** [comment]
> Regarding the beta design: I'm not sure if I want to install some additional app or whatever (I'm in iOS) and if there really is no downside then you should probably just release it.

I've only contributed very little until now (but I'm planning to contribute more in the future), but as far as I know it:
The Redesign itself is not finished yet. While the functionality is improved and everything is more useable than with the current public version, I think, finishing everything that is on the agenda/scheduled for the redesign and then releasing it as a finished product/new version is more reasonable and understandable than releasing a next version where the design of a specific menu changes again the version after that etc.
