### ISSUE TITLE
[BETA] Android Auto only on google play builds

### ISSUE THREAD

**Issue by Titaniumtown** [jmshrv/finamp#841]
I was trying to get android auto working and it seems to only work with builds from the google play store, not from the actual github release. Am I missing something? I try to use obtanium where I can.

Thanks

**Comment by Chaphasilor** [comment]
Hey, seems like you missed a small section in the release notes stating:

> **Please Note: Android Auto support only works if you installed Finamp via the Google Play Store!**
> 
> It is possible to get it working for alternative installation methods as well, but that requires enabling developer options, which you should only do if you know what you're doing!

That's a restriction imposed by Google, not us, so it's out of our hands :)
