### ISSUE TITLE
replace queue

### ISSUE THREAD

**Issue by meonkeys** [jmshrv/finamp#843]
The 0.9.9 beta is awesome!

Just curious about the "replace queue" function. Is that gone for good? Not a huge deal, I can adapt. And I personally prefer the new behavior with queues (how they auto-create based on the current album/playlist). My kids used to build queues manually with "replace queue" feature and they were wondering about it.

**Comment by jmshrv** [comment]
In the redesign you can just swipe down on the now playing bar to clear the queue, so there isn't much need for the Replace Queue button :)

**Comment by Chaphasilor** [comment]
Hey! Adding to what James said, you could also go into customization settings and disable the instant mixes there. Then, when you tap a track, it will replace the queue with just that track. And of course if you play an album, artist or playlist, it will also replace the current queue :)

**Comment by meonkeys** [comment]
Cool, thank you, that is helpful.

And we just discovered "Add to Next Up"... that's exactly what they wanted!

Really, *really* loving this redesign!!
