### ISSUE TITLE
[Feature Request] Downloaded icons for albums page, playlists page, etc

### ISSUE THREAD

**Issue by drazil100** [jmshrv/finamp#85]
Something that apps like YouTube music do that's really nice is that you don't have to go into an album, playlist, or whatever to tell if an album, playlist, etc is download. 

![image](https://user-images.githubusercontent.com/17794391/126383729-ba595eba-05fa-4cf5-81a9-dc2ea46d1bb1.jpeg)

It would be nice to have something similar in finamp at some point in the future once a lot of the more important issues are taken care of.

**Comment by UnicornsOnLSD** [comment]
I was thinking of adding something like that, should be able to do it when I rework the download indicator and how download status is tracked.

**Comment by stefan1983** [comment]
👍🏻
