### ISSUE TITLE
Apple Carplay / Android Car Support?

### ISSUE THREAD

**Issue by phillipunzen** [jmshrv/finamp#852]
Hello! 
I use Jellyfin to sort my music collection. Is it possible that the Apple Carplay or Android Auto app will get support? To select the album, etc., I always have to pick up my phone. 

Thank you!

**Comment by Chaphasilor** [comment]
Hey, the beta version already has support for Android Auto! You can join the beta through the Play Store.  
CarPlay isn't supported yet due to external limitations, so I can't really give an ETA for that :)

**Comment by keithZmudzinski** [comment]
> Hey, the beta version already has support for Android Auto! You can join the beta through the Play Store.  
> CarPlay isn't supported yet due to external limitations, so I can't really give an ETA for that :)

Wanted to ask if there's any update on CarPlay? 

Are there still external blockers? If you need someone to spend dev time to get it working, I'd be interested in lending a hand.
