### ISSUE TITLE
Finamp is not remembering last played song

### ISSUE THREAD

**Issue by Stitch10925** [jmshrv/finamp#853]
I often listen to music in the car using Finamp. Sadly enough Finamp is not remembering where I stopped listening. I need to start Finamp again, select the album again and hope I remember what the last song was I was listening to so I can start it again.

It would be nice if Finamp would remember this information.

There was a similar issue before that was resolved, it seems like it is back now.

Finamp verion 0.6.23 on Android.

**Comment by Chaphasilor** [comment]
Hi, you should give the beta version a try! That already has this feature, as well as Android Auto support, so it should be a much better experience for you :)  
You can find the latest downloads on the [releases page](https://github.com/jmshrv/finamp/releases) and join the beta directly through the Play Store.
