### ISSUE TITLE
redesign-beta: Tracks fade in when starting play

### ISSUE THREAD

**Issue by atomheartother** [jmshrv/finamp#865]
Tracks have a very slight fade-in if I have nothing currently playing then play a new track, meaning if the song starts at second 0 I miss the first note. Letting the track play then seeking back to 0s (without pausing) does play the very first few ms so they are in buffer, they're just being faded in.

If this isn't a bug and is a feature, I recommend making it a setting.

**Comment by Chaphasilor** [comment]
These are all some very weird bugs you're reporting, and I'm surprised no one else has supported them so far.  

Which version of Finamp are you using, which Jellyfin server version, and on what device are you using Finamp? :)

**Comment by atomheartother** [comment]
I'm aware of that, but all I can do is report them :>

Finamp: 0.9.9
Android version: 14
Device: Samsung Z Flip 5

**Comment by atomheartother** [comment]
I have tried all morning to reproduce this bug, couldn't, I was using a cheap DAC I never use when I was testing yesterday so I'm chalking this one up to "not Finamp" until proven otherwise and closing.
