### ISSUE TITLE
redesign-beta: Letter scroll indicator persists

### ISSUE THREAD

**Issue by atomheartother** [jmshrv/finamp#880]
I use hand gestures to navigate on my phone. When I try to exit some Finamp screens by swiping from the right edge inward, sometimes Finamp will register the touch and understand it as "I want to go to this letter" in the alphabetical sidebar.

However since my touch exits the app, the touch is never ended, instead the app quits. When you have something playling, this just puts the app to sleep instead of completely closing it, so now when I reopen the app the letter is stuck on the screen forever.

Reproduction steps:
- have an android phone
- enable gesture navigation 
- open the app
- play something 
- go to any screen with alphabetical sort
- try to swipe to exit the screen
- the bug occurs

Screen recording:

https://github.com/user-attachments/assets/7225fdf1-debd-4f4f-9011-10d2faabfe04

**Comment by Chaphasilor** [comment]
Yeah, that has been bugging me for a while too. Should mostly be fixed with the next update :)

**Comment by Chaphasilor** [comment]
This should be fixed now :)
