### ISSUE TITLE
Cannot select more than one music library at a time, playlists unaffected

### ISSUE THREAD

**Issue by firegodjr** [jmshrv/finamp#886]
Currently you are only able to select a single library at once. My music is split between multiple libraries, and I'd really like the option to select multiple libraries on the sidebar and have their content be combined on the main page. It seems like playlists are able to play from multiple libraries, it just isn't possible to see all the content at once.

**Comment by Chaphasilor** [comment]
Hey, yeah this is currently not possible and it will probably take a while before we can get that to work. The way Jellyfin does things means that fetching data from multiple libraries isn't straight-forward. So don't expect this any time soon!  
Playlists are library-independent.
