### ISSUE TITLE
[Feature Request] Improved Lyrics UI

### ISSUE THREAD

**Issue by JoshuaVandaele** [jmshrv/finamp#887]
Currently, lyrics are shoved to the side at a fixed size on the Desktop app, making it quite hard to read them particularly on larger monitors.

![image](https://github.com/user-attachments/assets/d61da2f7-e41b-42d5-9b9a-f3c30c25a61e)

I'd quite like to be able to put them full screen like Spotify or Apple Music does.

<img src=https://github.com/user-attachments/assets/1d819b92-8f20-4294-8918-b6273cc2c959 width="49%"/> <img src=https://github.com/user-attachments/assets/6c1a5393-3e7b-40d2-a228-9cfff1a3fa7a width="50%"/>

**Comment by BaccanoMob** [comment]
Try Settings > Layout & Theme > Uncheck `Allow SplitScreen mode`?

Doing so should display the right half to full display.

**Comment by JoshuaVandaele** [comment]
The problem with "Splitscreen Mode" is that it  does not provide access to essential media controls (such as duration, pause, next/previous, etc.) in the Lyrics view, making it very inconvenient to use. Because of this, I don't currently find it a viable option.

**Comment by Chaphasilor** [comment]
@JoshuaVandaele in the lyrics view you should still have all of these controls, splitscreen or not. Also, it is possible to resize the right panel to be bigger, just hover over the border between the two panels and drag it to the left :)

**Comment by JoshuaVandaele** [comment]
@Chaphasilor Oh, I didn't know I could resize the right panel, that's perfect! Albeither, the lyric view in Splitscreen doesn't appear to have these controls in splitscreen, as seen below:
![image](https://github.com/user-attachments/assets/bf9a72d5-4542-4e4c-bed3-a0e678e36872)
Since my issue is resolved, I'm going to close this, however if the behavior above is undesirable feel free to open a new one. :)

**Comment by Chaphasilor** [comment]
Hmm. That seems like a regression that we accidentally introduced. I'll take a look!
