### ISSUE TITLE
Pause playing when muted

### ISSUE THREAD

**Issue by BaccanoMob** [jmshrv/finamp#889]
If the volume is 0 or muted, to avoid needlessly work in the background, the app should refuse to play (and throw a toast/snackbar message saying `Raise the volume for me to sing for you.` or something).

It should auto pause if the volume is set to 0 when playing.

**Comment by kuflierl** [comment]
I could see audio processing being turned off to save cpu and network. But pausing the music is non-standard standard behavior. I don't think this should be default behavior.

**Comment by Chaphasilor** [comment]
I'm afraid this is some custom behavior that I'm not a fan of. I recommend giving Symfonium a try if you can spare a few dollars, I know that it supports exactly this (pausing if the volume becomes 0. Refusing to play when volume is 0 also not possible there).  
I myself sometimes cast audio to my multi-room setup, where I set the phone's volume to 0 to avoid unsynchronized audio :)  

I'd be willing to accept a PR that implements the automatic pausing if volume is 0, but won't implement it myself, sorry!
