### ISSUE TITLE
[BUG] Multiple libraries don't show correctly

### ISSUE THREAD

**Issue by velamvela** [jmshrv/finamp#89]
Having two libraries is causing issues, I have audiobooks and music

The audiobooks section doesn't show any files, doesn't list albums, but lists Artists(but with no files)

**Comment by UnicornsOnLSD** [comment]
I'm going to add audiobook tabs since they do apparently use different media types, I just assumed they would go under "Audio". Multiple music libraries does work though.

**Comment by jmshrv** [comment]
Closing as duplicate of #231
