### ISSUE TITLE
library view becomes unreadable due to white overlay when using alphabet letters for navigation in dark mode

### ISSUE THREAD

**Issue by foss-** [jmshrv/finamp#890]
In previous versions there was the issue of slow scrolling when using alphabet letters to navigate the library: https://github.com/jmshrv/finamp/issues/694

In 0.9.10 there is a regression in that the library gets stuck whenever using alphabet letters for navigation.

1. open finamp (library loads just fine)
2. scrolling the library works, but as soon as any alphabet letter on the right is tapped on any category

**Currently** a white overlay shows and library is barely readable in dark mode. The slow scrolling continues until the destination letter is reached, but interaction is no longer possible in the category that now shows with overlay. No scrolling or opening album details etc.

When switching category there is no overlay (yet) until again an alphabet letter is tapped. When switching back to previous category the overlay still is there and obstructing access.

**Expected** no overlay should be shown.

Android 13.1
Finamp 0.9.10

<img src="https://github.com/user-attachments/assets/8d949484-208e-4631-8715-589c892fa913" width="450">

**Comment by Chaphasilor** [comment]
Thanks for the report. It seems like this only happens in release builds, not development build, that's why I didn't notice it. I'll try to fix it ASAP!

**Comment by Chaphasilor** [comment]
@foss- would you mind giving the attach version a try? It's a release candidate that installs alongside the actual version. You'll have to log in to your server separately.
[Finamp-0.9.11-beta_preview.zip](https://github.com/user-attachments/files/17028111/Finamp-0.9.11-beta_preview.zip)

**Comment by foss-** [comment]
Installed and tried to sign-in but ran into following situation:

With Quick Connect enabled for the user, should finamp find the server on local network? I see `Servers on your local network: Scanning for servers…` but that never finishes or finds the server. Once I manually enter the server URL I am then able to use QuickConnect as expected. While desktop says `You have successfully authenticated your device!` finamp only shows a tiny exclamation mark in a circle in the middle of the screen which no further info or way to interact. Exiting and re-opening finamp again brings me to that view.

Any ideas how to proceed?

**Comment by Chaphasilor** [comment]
Hmm, that's odd. Could you post a screenshot?  
The scanning for servers is independent from Quick Connect, but requires your server to be configured correctly. Does that work in the regular beta version? You can log out and back in without losing downloads or settings to try it out :)

**Comment by foss-** [comment]
Regular beta also doesn't find server. For the main Jellyfin app there is a button `Use Quick Connect` which then shows the code right-away without having to paste the server URL. So this is a feature request for another issue I guess.

Beta and debug version show the same screen. Requested screenshot:
<img src="https://github.com/user-attachments/assets/885ff3d4-eb09-4e64-a20f-00d1a29eb3f0" width="350">

After closing and re-opening beta does open normally, while debug build still shows the exclamation mark screen. Hmm.

**Comment by Chaphasilor** [comment]
Oh, that's a new issue I guess 😅 I take it the back button also doesn't work?  
In the regular build, can you share the logs after logging in please? Maybe it contains some info about what's going on.

Re: Jellyfin app & Quick Connect, I wouldn't know how the Jellyfin app would be able to use Quick Connect without knowing your server's URl. But maybe their scanning is somehow better. Feel free to open a separate issue if you can reproduce this!

**Comment by foss-** [comment]
Uninstalled and re-installed debug build. This time login worked as expected and I can confirm the overlay issues is resolved in the debug build 🎉

**Comment by Chaphasilor** [comment]
Hmm, that's strange 😅 Let's hope others don't face the same issue...
