### ISSUE TITLE
[Bug] List goes gray and interaction disables when using fast scroller / alphabet list (beta 0.9.10)

### ISSUE THREAD

**Issue by AverageHelper** [jmshrv/finamp#892]
On Android, under the latest beta (0.9.10), tapping the letters on the side to scroll to a different section causes the list to go gray. The list appears to scroll to the correct place, but now there appears to be a gray wall preventing further interaction with the list or the scroll letters.

The only workaround at the moment appears to be to restart the app, avoid touching the letters, and scroll the list manually.

**Comment by Chaphasilor** [comment]
Hey, that bug has already been reported in #890 and a new update with a fix should hit the stores any hour now! :D

**Comment by Chaphasilor** [comment]
Update should be live now, and the bug should be fixed :)
