### ISSUE TITLE
Hours truncated from runtimes

### ISSUE THREAD

**Issue by SightSpirit** [jmshrv/finamp#893]
Since updating to 0.9.10 (and including 0.9.11), all times, including total and track runtimes, have only been displaying minutes and seconds, with hours not displaying. For example, an album that runs for 4 hours, 8 minutes, and 38 seconds (4:08:38) is showing up as running for "08:38."

This affects all views, apparently, including the Now Playing card, when a track is over an hour long.

App version: 0.9.11 (Google Play)
OS: Android 14
Device: Google Pixel 7a

**Comment by Chaphasilor** [comment]
Ah yes, thanks for the report!

I touched the time duration code to add screen reader labels for accessibility and probably made one change too many.  

Should be super simple to fix, I'll take a look!

**Comment by Chaphasilor** [comment]
Will be fixed in the next update :)
