### ISSUE TITLE
[Feature Request] Option to exclude from shuffle

### ISSUE THREAD

**Issue by AlmaPlata** [jmshrv/finamp#906]
I don't know if it could be possible to add an option to songs/albums (maybe even artists?) to exclude them from the all songs shuffle. 

In my case, I have lots of videogame OST's along all the rest of my music, and some of them have SFX's and the likes, so it'd be cool to be able to exclude them from the general shuffle of the library.
Meanwhile I get around it by having a playlist with everything except those entries, but it's not so convenient as i have to add every new song/album to that playlist every time.

**Comment by NutchapolSal** [comment]
I think this would require a change in [Jellyfin core](https://github.com/jellyfin/jellyfin) first.

PS. it sounds like this info should be part of the songs themselves, not something that is managed and stored in Jellyfin. Is there a metadata tag for specifying if a song should be excluded from shuffle?

**Comment by Chaphasilor** [comment]
Hey, yeah as @NutchapolSal mentioned this is basically impossible to add until the Jellyfin server itself supports this functionality. We only request a random set of track from the server when shuffling, and any exclusion would need to happen there. 

It's not too far-fetched, basically it would be an attribute similar to the favorite status that can be added per-item, and filtered upon. If someone really wanted to add this, it would probably not be too complicated to make a PR to the Jellyfin repo, and I could image it being accepted.  
I'll close this issue for now, but feel free to let me know if the server should add support for this at any point!
