### ISSUE TITLE
[Bug] Audio glitches without transcode

### ISSUE THREAD

**Issue by 10kmotorola** [jmshrv/finamp#910]
only has happened to some files ive downloaded from soundcloud. file plays fine directly or via the jellyfin web ui ... if linking the mp3 would help just let me know

demo: https://files.catbox.moe/txk93q.mp4

**Comment by Chaphasilor** [comment]
Can you share some info about the source audio file? Which codec and container (file extension) is it using?  
Also, which device are you using?

**Comment by 10kmotorola** [comment]
```
Audio
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 3
Format settings                          : Joint stereo / MS Stereo
Duration                                 : 2 min 39 s
Bit rate mode                            : Constant
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 kHz
Frame rate                               : 38.281 FPS (1152 SPF)
Compression mode                         : Lossy
Stream size                              : 2.44 MiB (100%)
Writing library                          : LAME3.99.3
```

im using a 2021 motorola edge with Android 14 and LineageOS 21-20240925-NIGHTLY-berlna

**Comment by Chaphasilor** [comment]
@10kmotorola could you try it with this version please: https://gofile.io/d/IeiVOf  
It will be install alongside the regular version, so you'll have to log in again.

**Comment by 10kmotorola** [comment]
Issue still persists D:

**Comment by Chaphasilor** [comment]
Okay, then I have no idea what could be done about it. Seems like your Android version simply has issues with that specific track. If everything works when transcoding, you might wanna use ffmpeg or something similar to permanently convert the file to another format or simply re-encode it...
