### ISSUE TITLE
[bug] Track times >=1h not displayed correctly

### ISSUE THREAD

**Issue by jgoguen** [jmshrv/finamp#913]
Finamp 0.9.11-beta, iOS 18 on both iPhone 15 Pro Max and iPad Air 13" M2.

When a track duration is one hour or more, the time display is not always correct. In the track listing and the player details views, only minutes and seconds are shown. The mini player does correctly show the full time, as shown in the screenshots. Both the elapsed and remaining times are displayed wrong. The track progress bar is correct.

Track listing and mini player:
![image](https://github.com/user-attachments/assets/426a808e-6230-4995-b87c-ee0bdb5a3dd2)

Player details:
![image](https://github.com/user-attachments/assets/f3050a0b-6e2c-4929-b78e-1b2aed09c373)

Player details with track progress, >1hr remaining in track:
![image](https://github.com/user-attachments/assets/c378811a-3015-4490-bb9f-59f9accbd73d)

Player details with track progress, <1hr remaining in track:
![image](https://github.com/user-attachments/assets/acbbad63-1c2d-48c5-aeb7-9922e35a9177)

Player details with track progress, >1hr elapsed time:
![image](https://github.com/user-attachments/assets/bf3e3855-58ae-4c9f-ba56-54a17408f2c3)

**Comment by lukaslindnermusic** [comment]
This is already mentioned in https://github.com/jmshrv/finamp/issues/893 and will be fixed in the next update, according to @Chaphasilor 😊 

But I can confirm, its the same with my library and app install 😊
