### ISSUE TITLE
iPad with headphones forces foreground for audio

### ISSUE THREAD

**Issue by jgoguen** [jmshrv/finamp#914]
Finamp 0.9.11-beta, iPad Air 13" M2.

When using headphones only, Finamp must be in the foreground to play. Switching to any other app causes Finamp to fade out. The iOS pull-down notifications shows the player controls, but the Play button is greyed out. This only happens with headphones, without headphones connected I can switch to another app or lock the device and Finamp keeps playing as expected. iPhone also works as expected, headphones or not I can switch apps or lock and Finamp keeps playing.

**Comment by jgoguen** [comment]
I don't know what might have happened but today it's all working fine. The only thing I can think of different is today I've turned on Stage Manager, but turning it off and even forcibly restarting Finamp afterwards doesn't make it start fading to silent when switching apps again.

**Comment by Chaphasilor** [comment]
Hmm, well I'n glad that it's working again! I've also had Finamp crash when switching to bluetooth headphones on desktop, so there could be a related issue, but desktop support is in alpha anyway and there probably isn't much we can do anyway...

But let me know if it pops up again 👍🏻
