### ISSUE TITLE
Audio transcoding information

### ISSUE THREAD

**Issue by HanaO00** [jmshrv/finamp#916]
Hello I don't really know if this is an issue or no, in the Finamp android client I activated the transcoding in AAC but jellyfin in the dashboard says that there is no transcoding and that the media is read without transcoding

**Reproduction steps**

1. In the finamp settings (android) enable transcoding (AAC)
2. In the jellyfin dashboard, look at the information about transcoding

**What is the current bug behavior?**

The transcode log is created, the media sent is in AAC but jellyfin says that there is no transcoding, even with a different source (flac, or other...)

**Infos**

Android 14 / Finamp 0.9.11 / Jellyfin 10.9.11

**Comment by Chaphasilor** [comment]
Hey, yes that is a known issue. Finamp is transcoding (you can check the transcode logs on the server), but we still haven't figured out how to let the server know that. Jellyfin's documentation is pretty lackluster...
