### ISSUE TITLE
[Feature Request] Add an 'Up Next' Queue

### ISSUE THREAD

**Issue by 9vult** [jmshrv/finamp#92]
In Spotify, when you play from a playlist, album, etc, it begins "Playing From xyz". Then, if you swipe on a song to add it to the queue it adds it to the "Up Next" section. Anything in Up Next gets played before the next item in Playing From.

I'd like to see this Up Next queue added to Finamp, so I can have a playlist running but queue songs to play next as I please.  Perhaps have a swipe left add to Up Next and a swipe right add to the bottom of the queue? (currently both directions add to the bottom of the queue)

**Comment by bambadon** [comment]
This is a great suggestion!

**Comment by drazil100** [comment]
I would personally like to see play queue functionality similar to base jellyfin. I would like to see the play queue represent what is actually coming next and if set to shuffle have the queue show up in shuffled order as I mentioned in #75 but also I would like the ability to insert a song both directly after the song that is currently playing or at the end of the queue
![Screenshot from 2021-08-03 20-20-26](https://user-images.githubusercontent.com/17794391/128107145-046efeb7-20d9-4435-be5e-557749a58e08.png)

**Comment by mueslimak3r** [comment]
I agree with all prior comments and I'll add that currently the "queue" doesn't allow selecting songs. So I can't start and album then choose a different song from the queue

**Comment by UnicornsOnLSD** [comment]
@mueslimak3r That feature was added with #115, it just hasn't been released yet

**Comment by jmshrv** [comment]
The UI has been designed for the redesign (#220), it'll be implemented there
