### ISSUE TITLE
[Feature Request] Restore Tracklist/Playback Progress When Switching Between Libraries

### ISSUE THREAD

**Issue by AubinF** [jmshrv/finamp#920]
Hi,

First, I want to say how much I love Finamp—fantastic job on the beta, it's amazing! 🔥

I wanted to suggest a small improvement for tracklist restoration. Right now, the app restores the track list I was listening to when I reopen it, which is super handy. But when switching between libraries, the tracklist stays the same.

Would it be possible to restore the tracklist specific to the library I'm switching to? I often switch between music and audiobooks (which I treat as a separate music library), so it would be really helpful if the app could remember the last tracks for each library separately. It would make using the app even smoother, especially for audiobook playback.

Thanks a lot for considering this!

**Comment by Chaphasilor** [comment]
Hey, so technically it would definitely possible. But I'm not sure if that use case is general enough for other users.  
You are aware that you can manually restore specific queues through the "restore now playing" screen?

Maybe prompting the user if they want to switch queues could work. I'm actually not opposed to keeping track of which queues were started from which library (at least while multiple libraries can't be selected st once), but I'm not sure about the automatic restoring part.

I think there was some development towards remembering playback position for tracks on the server, maybe that could also help here if Finamp would use that?  
Would love to hear more of your thoughts!

**Comment by AubinF** [comment]
Hi @Chaphasilor ! 

You are absolutely right. The "restore now playing" screen which I have never really checked until now can estore the tracklist and even -as per my tests-  the playback position. That's another pure quality of life feature from the beta I suppose :) 

SoI'm happy to close this issue now.
