### ISSUE TITLE
[Question] ReplayGain (Volume Normalization) ID3 tags recognized

### ISSUE THREAD

**Issue by psyburr** [jmshrv/finamp#924]
My entire audio library is tagged using Picard, including ReplayGain tags added using the ragain plugin. With that being said, I've noticed some tracks the ReplayGain (RG) tags are respected for some tracks and are ignored for others. My question is as follows:

> What are the tags that finamp will recognize with respect to ReplayGain?

I am thinking that those that are ignored may be recordings that I've applied a true peak value outside of finamp's recognized limits, or are being applied with all _ ALLCAPS or something else, _I'm not at my desktop at the moment to do a further investigation of my library to determine any more but did think it would be helpful to know what the actual tags are that I should be using first and go from there._

**Comment by Chaphasilor** [comment]
Hey, sorry for the late response  We try to have as little custom behavior or parsing in Finamp as possible, so we only ever use the metadata provided by the server. So your server is probably not picking up the tags correctly!  
Make sure you have "Enable LUFS scan" turned on for your music library.
