### ISSUE TITLE
[Enhancement] Better transition to offline mode when server cannot be reached

### ISSUE THREAD

**Issue by cyberwolfie1** [jmshrv/finamp#925]
I have a Jellyfin-server that runs on my home network. Whenever I commute to work and want to listen to music, if I have not already enabled offline mode as I get out of reach of my WiFi, Finamp will start spamming me with errors. 

```
ClientException with SocketException:
Connection failed (OS Error: Network is unreachable, errno = 101), address = internal.ip.address.to.server, port = 8096, uri=http://internal.ip.address.to.server:8096/Users/<item_id>
```

This will pop up one at the time, and depending on how long it takes me to switch to Offline mode, it can go on for a while. It is quite annoying, as it keeps buzzing for a while.

It would be nice if this transition was better handled. I think Audiobookshelf handles this perfectly. It tries to connect, and if it can't, it automatically transitions to offline mode with a visual cue that you are not connected to your server.

Additionally, something that would be nice would be to have the option to configure a fallback-server. My Jellyfin-instance is exposed to the internet via a reverse proxy, but I don't want all my traffic leaving my home network when I am at home, so I have not configured it to connect to my external domain. However, if we could configure a fallback-server so that when the main server is unreachable, it will attempt to connect to the fallback-server before going to offline mode, if that also fails. That would be the ideal behavior in my world.

I am otherwise very happy with Finamp, and I love the redesign. :)

**Comment by Chaphasilor** [comment]
Hey, please add your thoughts and suggestions to the existing issue: https://github.com/jmshrv/finamp/issues/620  
Better error handling is definitely planned, but I'm not sure when that will happen.
