### ISSUE TITLE
No sound, no download. Tried to different Android phones

### ISSUE THREAD

**Issue by taladro** [jmshrv/finamp#928]
Hi, I´ve installed the latest beta 0.9.11
I log into my server (tried two different users), see the libraries. When I try to play it doesn´t sound at all.
Tried downloading and I get the orange icons with the error. Tried mp3´s and flac. Tried on and off transcoding. Nothing happens. Thanks for your help-
[finamp-logs.txt](https://github.com/user-attachments/files/17451815/finamp-logs.txt)

**Comment by Chaphasilor** [comment]
Hey, thanks for the report!

When you try to download the files, the server responds with status 404 (not found) and "Error processing request" for some reason. Could it be that your setup in special in some way?

Would you mind sharing a screen recording of you trying to play and download something? Maybe that tells me more about what's going on...

**Comment by taladro** [comment]
Hi, here is the video: https://fromsmash.com/KV_6SNZLmJ-ct

**Comment by Chaphasilor** [comment]
Thanks. Everything *looks* in order. Was that with transcoding enabled or disabled?  
It seems like the metadata and images for your tracks to download fine, just the actual tracks are the problem.  
I'm wondering if it could be some sort of permission issue on your server? Do any other clients also have problems with playback or downloading?  
Also, could you try if the non-beta version of Finamp is working?

**Comment by taladro** [comment]
Hi, tried with the non beta, tried with another user, tried putting on and off the audio transcoding from the server. Nothing changes. What I saw that was curious is that the server dashboard shows progress on playing mp3´s thru finamp but on the client nothing happens (and the clock doesn´t move)

**Comment by Chaphasilor** [comment]
Ah okay. Best check your server logs in that case. Could be a permission issue or something.  
The server dashboard showing playback progress is expected, since the progress is reported "manually" to the server whenever playback status changes. It might make sense for us to add additional error handling to avoid showing progress if there are playback errors, that's true.
