### ISSUE TITLE
AAC files categorize under Disc 0

### ISSUE THREAD

**Issue by 10kmotorola** [jmshrv/finamp#929]
AAC files on the same album with other formats display under "Disc 0" despite disc 1 being clarified in the metadata. I'm on a motorola edge 2021 running LineageOS 21-20241016-NIGHTLY-berlna.

**Comment by Chaphasilor** [comment]
Is the album structure correct on the server?

**Comment by 10kmotorola** [comment]
Yeah. I actually looked into it on the Jellyfin desktop client & the issue is there too ... so it seems to not be an issue with Finamp specifically. this can probably be closed & I'll make an issue at Jellyfin?

**Comment by Chaphasilor** [comment]
Yeah that would be the best way forward. Hope they'll sort it out soon!
