### ISSUE TITLE
[Feature request] Preserve repeat setting between sessions.

### ISSUE THREAD

**Issue by drazil100** [jmshrv/finamp#93]
Right now if you are playing something and have it set to repeat 1 or all and you switch to anything else (picking a song or play/shuffle at the top of an album) it will preserve the repeat setting. If you press the stop button or close the app however the setting gets reverted to play all and stop the next thing you play.

Not sure if this is a bug or intentional but I would like to just have my repeat preference carry over between play sessions.

**Comment by Chaphasilor** [comment]
Just implemented this as part of #484 😁

**Comment by Chaphasilor** [comment]
@drazil100 this feature is near and dear to me and has now been released as part of the redesign beta! You can check it out here: https://github.com/jmshrv/finamp/releases/tag/0.9.2-beta

I'll close this issue for now since it should be resolved.
