### ISSUE TITLE
Repeated lines in lrc parsed only once

### ISSUE THREAD

**Issue by psyburr** [jmshrv/finamp#935]
I'm not sure if this is a bug within finamp or jellyfin, but when lines in an lrc file are meant to be repeated at a later time in the song, they are not. Instead they are only displayed for the first time that is listed when multiple timings are entered in series on a line. Below you can see an example where lines should be displayed a second time later in the song.

```
[01:27.58]Looking for a clue
[01:30.14][02:41.69]I've been crawling on my belly
[01:33.17][02:44.70]Clearing out what could've been
[01:36.05]I've been wallowing in my own confused
```

For this song line 2 & 3 should be repeated roughly 1 minute later, however at that time the lyrics that preceed it in the file for those times remain, only to resume once another unique line occurs. Kodi parses the these correctly and you will find a number of lrc sources have files hosted like this. I was hoping maybe we could get finamp to parse these the same way Kodi does and that they could be displayed again. I didn't want to tag this as a bug because I'm not entirely sure that it is one since it still parses lyrics correctly, just not for lines that are entered like this and that are meant to be repeated.

**Comment by Chaphasilor** [comment]
This is an issue with the Jellyfin server, which should actually already be fixed with the recently released Jellyfin 10.10!  
Finamp doesn't parse lyrics itself, but just uses whatever the server returned.
