### ISSUE TITLE
presenter

### ISSUE THREAD

**Issue by senolfndk** [jmshrv/finamp#942]
Where can I get the server url? I'm a beginner in this field.

**Comment by Chaphasilor** [comment]
https://jellyfin.org :)  
You need to set up your own personal Jellyfin server, and then Finamp can connect to that server. You also need to bring your own music collection.

**Comment by senolfndk** [comment]
> https://jellyfin.org :)  
> You need to set up your own personal Jellyfin server, and then Finamp can connect to that server. You also need to bring your own music collection.

![Screenshot_20241104-171643.jpg](https://github.com/user-attachments/assets/337d1d6b-021b-41a0-8c7a-dd03a8dfb23e)

🤔

**Comment by Chaphasilor** [comment]
Please visit that URL in your browser, the website has all the info and explanations you need.  
To give Finamp a try, you can use https://demo.jellyfin.org/stable as the server URL

**Comment by senolfndk** [comment]
> Please visit that URL in your browser, the website has all the info and explanations you need.  
> To give Finamp a try, you can use https://demo.jellyfin.org/stable as the server URL

🤔![Screenshot_20241104-173031.jpg](https://github.com/user-attachments/assets/31d8011e-bef5-46f1-b67c-af83fb082185)

**Comment by senolfndk** [comment]
> This is not a support forum. Please use our Discord server for that: https://discord.gg/xh9SZ73jWk
> 
> But the name is `demo` and the password field stays empty.

Discord is closed in Turkey

**Comment by Chaphasilor** [comment]
Yes, if you have a Jellyfin server set up, you can add your music to the server. https://jellyfin.org/docs/

**Comment by senolfndk** [comment]
> Evet, eğer bir Jellyfin sunucunuz varsa, müziğinizi sunucuya ekleyebilirsiniz. https://jellyfin.org/docs/

Thanks bro for your help
