### ISSUE TITLE
Generate queue by genere tag

### ISSUE THREAD

**Issue by RandomQueries** [jmshrv/finamp#950]
Yep! It's possible to generate a queue based on Genere tag? I tried touching numbers of tracks and it not work. Any solution or it's not implemented. Thx! From sunny Catalonia.

**Comment by Chaphasilor** [comment]
Hey, yes it is possible!  
1. Go to the "Genres" tab
2. Long-press on the genre you want to add to the queue, then select "Add to mix" in the menu
3. (Optional) Select additional genres to be included in the mix, if desired
4. Click the blue button at the bottom right corner to start the mix

This will shuffle all tracks from the selected genres.
