### ISSUE TITLE
[Bug] Only M3U playlists shown, no jellyfin created ones

### ISSUE THREAD

**Issue by WisdomCode** [jmshrv/finamp#951]
Thank you for developing this app that has been my daily driver for years now!

I am currently testing the beta, and it fixes all issues I had with the stable release from F-Droid. 
However, it also introduced a new problem: In the tab Playlists, I can only see playlists added to jellyfin by m3u, while all playlists generated in Jellyfin itself are ignored, even those created in the app. Strangely enough, if I choose to add a song to a playlists, all the playlists appear for addition. They just don't show up in the tab...

App Version: 0.9.2-beta
Jellyfin Version: 10.10.1
Tested on Android 14 June Patch

EDIT: I just realized, even stranger, I can see the playlists created by jellyfin if I'm in offline mode, but only then.

**Comment by Chaphasilor** [comment]
Hey, check out the release page, there are several new version, you're using the original beta release. The current version is 0.9.11, and we are in the process of releasing 0.9.12!

There, these issues you're describing should be fixed :)

**Comment by WisdomCode** [comment]
Ah, silly me, indeed it is fixed in the newer version! I got this version from the link in the currently officially shipped app, hence the confusion.
Thanks for elaborating, closing the Ticket.

**Comment by Chaphasilor** [comment]
Yeah, having the link point to the initial release isn't ideal, but was easier than looking up the latest release automatically. The initial release also has the most information available.  
But since you're not the first one being confused by this, I'll put up a notice for the 0.9.2 release that explains where to find the latest release.
