### ISSUE TITLE
"Finamp has crashed" on app close (Testflight Beta, IOS)

### ISSUE THREAD

**Issue by CaffeinatedOpe** [jmshrv/finamp#953]
I got the new beta update, and I've noticed a weird bug where whenever I manually close the app from the app switcher, I get an error popup saying that finamp has crashed.
Possible details of importance: 
- Testflite
- app version 0.9.12
- jellyfin server version 10.10.0, docker hosted through reverse proxy
- IOS 18.0.1
- iphone 15 pro
- 18.61 gb of music/metadata
- message appears in both online and offline modes, playing or paused
- no data appears in the logs about the crash
If there is any other helpful information I can provide, or anything else i can do to assist, please let me know

**Comment by Chaphasilor** [comment]
Thanks for the report!

Does this also happen if you *stop* the queue before closing the app? You can currently only stop it by swiping down on the miniplayer (which might also trigger the one-handed mode).

Could you still export the logs by using the "share" button on the logs page? That will include logs from previous app launches, not just the current launch.

Also, do I understand correctly that you didn't have this issue with previous beta versions? Or did you only switch to the beta with this update?

**Comment by CaffeinatedOpe** [comment]
Closing the cue does indeed prevent the crash message. I've been using the beta for a decent amount of time, and only noticed this bug after the most recent update. Here are the logs, immediately after closing the app once with the cue stopped, then once with it running. Here is a link to the logs (GitHub iOS wouldn't let me upload the file): https://drive.google.com/file/d/1ngHxXIQMTHwQv4dO_XhqHEC1hrI1E_N4/view?usp=drivesdk

**Comment by Chaphasilor** [comment]
Interesting, that definitely helps pinpoint the issue. Seems to be something about the player/queue being still active in the background, and then getting force-closed when you close the app.

By the way, you should be able to upload logs by using the "add image" button and then selecting the text file instead. Ideally remove the leading `!` afterwards :)

**Comment by CaffeinatedOpe** [comment]
I tried that, but it I got a pop about being unable to upload the "image"

**Comment by Chaphasilor** [comment]
Huh. Works on Android, strange decision to prevent it on iOS.

Anyway, I noticed some downloads running, could you make sure that all downloads are fully finished before closing the app (without stopping the queue), and check if you still get the error?

**Comment by CaffeinatedOpe** [comment]
No downloads were running or queued, and the crash still occurred

**Comment by Chaphasilor** [comment]
This is a bug in our audio player dependency and [has been fixed in the latest version](https://pub.dev/packages/just_audio/changelog#:~:text=Fix%20dealloc%20crash%20on%20iOS/macOS). This will be included in the next beta update!

**Comment by CaffeinatedOpe** [comment]
Nice, I'm glad it got figured out!
