### ISSUE TITLE
[Beta] Crash when changing songs

### ISSUE THREAD

**Issue by Harteex** [jmshrv/finamp#962]
I'm getting crashes when changing songs within an album.
To reproduce:
1) Open any album
2) Press a song to start playing it
3) Now press the next song (for some reason it stops playing)
4) Press it again to actually start playing the next song
5) Continue doing the above by changing to the next song in the album and eventually it crashes

**Comment by Chaphasilor** [comment]
What version are you using? Can you please share logs?  
Also, any info about that album (size, codec, downloaded or not) would help!

**Comment by Harteex** [comment]
Using the latest version on Google Play.

This is Finamp version 0.9.12+112 (Signature A7217FD431D22ECBBECF8FE07336576047DCD8D9BD29040491F9D57D94A543C7), installed via com.android.vending.
Device info:
Android 14 on SM-S921B (e1sxeea)

This happens on multiple albums, but seems to crash on different songs in different albums?
The album I've been reproducing it the most on is 9 songs, mp3s. Not downloaded.

Crashes right after the log entry:
[MusicPlayerBackgroundTask/INFO] 2024-11-22 11:27:38.635703: Queue completed.

For the full log, I would prefer to share it privately with you, I hope that's ok. I've sent an email.

**Comment by Harteex** [comment]
I uninstalled the app and reinstalled it, and that seems to have fixed the problem. If the problem arises again I can re-open the issue or create a new one. Thanks!
