### ISSUE TITLE
Spatial audio support

### ISSUE THREAD

**Issue by ikunfans** [jmshrv/finamp#966]

**Comment by ikunfans** [comment]
my phone support spatial audio and i have some dolby atoms music , when i play music direct ，it support spatial audio  function？

**Comment by jmshrv** [comment]
On iOS, spatial audio is supported, and should "just work" if you have multichannel music. I'm not 100% sure on Android, but since Finamp just uses Android's built-in media player, it should work

**Comment by ikunfans** [comment]
> On iOS, spatial audio is supported, and should "just work" if you have multichannel music. I'm not 100% sure on Android, but since Finamp just uses Android's built-in media player, it should work

Thank you. Are there any plans to support m4a Apple Lossless? This format is not currently supported,I have some music with this format

**Comment by jmshrv** [comment]
ALAC is supported on iOS, although not on Android since Android's native player libraries don't support ALAC
