### ISSUE TITLE
Cleaning up "orphaned" downloads

### ISSUE THREAD

**Issue by ilya-zlobintsev** [jmshrv/finamp#97]
Partly a duplicate of #76

I have the following situation: I've downloaded some albums with finamp, after that I've made some restructuring/metadata updates on the jellyfin server, leading to the same songs/albums now having different item IDs. Now I can download them again (which is expected, since they're different items according to the server), but when browsing in offline mode I end up having duplicates.

I assume the behaviour is similar when simply deleting items from the server.

It would be nice if there was a way to remove all items that no longer exist on the server, because right now you can't even remove them manually: the non-existent (but downloaded) albums don't show up in online mode, and in offline mode the remove button is greyed out.

**Comment by UnicornsOnLSD** [comment]
This should be fixed when I add syncing, which will be added in the next release.

**Comment by Y0ngg4n** [comment]
Issue still exists
